### ISSUE TITLE
System.IO.Path is blocked for .NET Framework only

### ISSUE THREAD

**Issue by danmoseley** [ashmind/SharpLab#1050]
I'm not sure why it's blocked but if it's a security thing it should probably be blocked for either both or neither .NET Framework and .NET Core.

eg 
https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAmAjAWAChMAGAAk1wDoBJAeQG4iicyANMgbyLN7J745sXZoT7jKATgAUABQCGcABZUA4gFM4AMWQAbXQuXSARAGMQAHQvGAlDaaEAvo6A==
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6ASQHkBua60+gDXoBvavTH1R40iWE8q4hUwCcACgAKAQwwALZgHEYGAGI4ANqc06VAIjAgAOvesBKZ9yoBfD0A=

**Comment by ashmind** [comment]
Thanks for reporting! .NET Core is using a newer security model, which is less restrictive.
Backporting it to .NET Framework would require a bit of effort, which is why the models are different.
