### ISSUE TITLE
Site is not opening, problem with CDN

### ISSUE THREAD

**Issue by megapro17** [ashmind/SharpLab#1124]
![image](https://user-images.githubusercontent.com/16743370/167469132-d8e639b9-d08c-49fb-ab71-01574e3d8ae9.png)

It can't load resources from two sites, with ERR_SSL_PROTOCOL_ERROR error
http://slpublic.azureedge.net/assets/2021-11-13-1343/app.min.css
https://slpublic.azureedge.net/assets/2021-11-13-1343/app.min.js

Opening HTTP page:
`<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0jlV5YgAAAAB29w4FGd9fS6tewIYCTHKmU1RPRURHRTA4MTUARWRnZQ==`

**Comment by ashmind** [comment]
Thanks for reporting! Hmm, based on descriptions it sounds like a temporary outage on Azure side.
I am not seeing any issues at the moment -- I'll close for now, but please let me know if you see anything further.

**Comment by megapro17** [comment]
No, it's still doesn't work with the same error from cdn.
However, it does open when using VPN.
Is it because I'm located in Russia?

**Comment by ashmind** [comment]
Ah I see -- it might be related, but not sure. I'll leave this open and will think more about this.
If you can get any more details on `ERR_SSL_PROTOCOL_ERROR` that would be useful as well.

(I have a feeling http is probably disabled anyways, so the error message on http might not tell much)
