### ISSUE TITLE
default(T) is considered same as "new T()" where T is a struct, IL code doesn't show a difference. 🐞 

### ISSUE THREAD

**Issue by sabitkondakci** [ashmind/SharpLab#1127]
### Sharplab v2 IL :
```csharp

 // in release mode

public void M() {
      var model = new StructModel();
      // IL_0000: ret
}
    
public void N() {
     var model = default(StructModel);
     // IL_0000: ret
}
```

###  ILSpy IL :
```csharp

// in release mode

public void M() {
      var model = new StructModel();
     // IL_0000: newobj instance void StructModel::.ctor()
     // IL_0005: pop
     // IL_0006: ret
}
    
public void N() {
     var model = default(StructModel);
     // IL_0000: ret
}

**Comment by svick** [comment]
Is `StructModel` the same in both cases? In particular, does it have parameterless constructor?

**Comment by sabitkondakci** [comment]
> Is `StructModel` the same in both cases? In particular, does it have parameterless constructor?

This seems like a .NET6 issue, Sharplab is running on .NET5 this is why it makes a difference.

**Comment by sabitkondakci** [comment]
> Is `StructModel` the same in both cases? In particular, does it have parameterless constructor?
