### ISSUE TITLE
Changing branch resets editor content

### ISSUE THREAD

**Issue by KeterSCP** [ashmind/SharpLab#1154]
Steps to reproduce:
- Open SharpLab web page
- Enter something in the editor
- Change the branch

Expected behavior:
- Input stays the same

Actual behavior:
- Input is reset

Regression?
- As far as I remember, it was working fine before

Known workaround:
- Before changing the branch, press F5 key to refresh the page, after that input is cached and preserved between branch changes.

**Comment by ashmind** [comment]
Thanks for reporting! Likely a regression from recent UI rewrite to React — I'll try to take a look asap.

**Comment by ashmind** [comment]
This is now resolved.
