### ISSUE TITLE
Add option to disable all aditional SharpLab features

### ISSUE THREAD

**Issue by OwnageIsMagic** [ashmind/SharpLab#1160]
Currently SharpLab fails to run on valid code such as ` _ = ((((((0))))));` or due to some bugs in IL rewriter. Can you add option to disable any additional pre-processing introduced by SharpLab to get around those limitations?

**Comment by ashmind** [comment]
Thanks for reporting! Yep I can add it as a power-user feature, something like `[assembly: DisableILRewriting]` -- I'll update once that's done (no timeline promises).

**Comment by ashmind** [comment]
This is now resolved -- you can use `[assembly: NoILRewriting]` to disable IL rewriting.
Notes:
1. Feature is not implemented for .NET Framework -- please create a new issue if it's needed
2. Feature may take some time (up to a day) to deploy to Roslyn branches (e.g. `main`)
