### ISSUE TITLE
Directory.EnumerateFiles(".") result?

### ISSUE THREAD

**Issue by Daynvheur** [ashmind/SharpLab#1163]
Hi, I don't know how to phrase that, but maybe it could be a potential issue that `Directory.EnumerateFiles(".")` actually enumerates over `C:\Deployments\2021-12-18-1100\`?

Found that by error, trying to run `var lines = File.ReadAllLines(@"file://C:\Users\xazf743\source\some.txt");`, the error gave the target path: `System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : '`**`C:\Deployments\2021-12-18-1100\`**`file:\C:\Users\xazf743\source\some.txt'`

Have a nice day.

**Comment by ashmind** [comment]
Thanks for reporting! That _should_ be OK as that specific folder is not expected to contain any secrets, and you shouldn't be able to write to it -- but please let me know if you find anything that looks like a secret or a key.

This helped me find another issue though (with environment variables).

**Comment by Daynvheur** [comment]
I didn't find any secrets nor keys (out of blue, I wasn't specifically looking for some), glad to have helped.

Closing this, as everything's fine!
