### ISSUE TITLE
[connection lost, reconnecting…] on Semi-auto-properties branch

### ISSUE THREAD

**Issue by Xapier14** [ashmind/SharpLab#1173]
See: https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLTIgWwJaqnGAe1QAcFCTkAaAExAGoAfIA
![image](https://user-images.githubusercontent.com/26619890/180648782-4f55c14f-a5d0-4b17-84bc-eee4b0e450d8.png)

**Comment by ashmind** [comment]
Thanks for reporting! This branch does not have recent successful builds in Roslyn CI, so I might not be able to resolve this, other than by providing a better error. I'll keep it open to see if that is eventually resolved on Roslyn side.
