### ISSUE TITLE
Exception on main branch

### ISSUE THREAD

**Issue by KeterSCP** [ashmind/SharpLab#1178]
Steps to reproduce:
- Open SharpLab page
- Select `main` branch

Expected result:
- Everything works fine

Actual result:
- `System.MissingMethodException: Method not found: 'Microsoft.CodeAnalysis.Diagnostics.IdeAnalyzerOptions Microsoft.CodeAnalysis.Diagnostics.IdeAnalyzerOptions.GetDefault(Microsoft.CodeAnalysis.Host.HostLanguageServices)'.` Exception is thrown. Branch is not usable

**Comment by steviegt6** [comment]
[This commit](https://github.com/dotnet/roslyn/commit/9ed06bdad97da0812f3471df2541a7aa8ec737d1) in [dotnet/roslyn](https://github.com/dotnet/roslyn) changed the signature of `IdeAnalyzerOptions::GetDefault` recently.

**Comment by John0King** [comment]
now sharplab.io is broken because this issue

**Comment by ashmind** [comment]
Thanks for reporting! @John0King I would expect this only affects the "main" Roslyn branch but not the Default?

**Comment by ashmind** [comment]
This is now resolved.
