### ISSUE TITLE
Invalid code when decompiling simple F# not (isNull x) into C#

### ISSUE THREAD

**Issue by ForNeVeR** [ashmind/SharpLab#119]
Consider this simple code:

```fsharp
open System

type C() =
    member __.notNull x = not (isNull x)
```

(see https://sharplab.io/#v2:DYLgZgzgPg9gDgUwHYAIDKBPCAXBBbAWAChjsNEUBhACgEoUBeYlFlPfAIwQCcUB9PgDokMbADkArsGAoAHoxQjsKagEsIk6XNpA)

It decompiles into that:

```csharp
using Microsoft.FSharp.Core;
using System;
using System.Reflection;
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: FSharpInterfaceDataVersion(2, 0, 0)]
[CompilationMapping(SourceConstructFlags.Module)]
public static class _
{
    [CompilationMapping(SourceConstructFlags.ObjectType)]
    [Serializable]
    public class C
    {
        public C() : this()
        {
        }
        public bool notNull<a>(a x) where a : class
        {
            return x == null ? 1 : 0 == 0;
        }
    }
}
namespace <StartupCode$_>
{
    internal static class $_
    {
    }
}
```

That statement `return x == null ? 1 : 0 == 0` is very strange because it doesn't compile in C#.

**Comment by ashmind** [comment]
@ForNeVeR Thanks for reporting!
The decompilation is currently handled by an external component (ILSpy). The version I'm using is somewhat outdated -- I'll try updating to latest sometime later and I'll let you know if they've fixed it.

**Comment by ForNeVeR** [comment]
If they aren't, I'll eventually raise the issue on the ILSpy repo, thanks.

**Comment by ashmind** [comment]
Checked and it still happens in latest stable release (2.4), so worth rising with them.
The essence of the problem is pretty simple:
```
x == null ? 1 : 0 == 0
```
should be read as 
```
(x == null ? 1 : 0) == 0
```
and simplified into 
```
x != null
```
(considering all boolean conditions are ints in IL anyway)

**Comment by ForNeVeR** [comment]
@ashmind it's nice to see that the problem is fixed. Could you please clarify? The source of the problem was in your code? Should I close the issue on ILSpy side?

**Comment by ashmind** [comment]
@ForNeVeR Yep I'm going to clarify, just didn't expect such a quick reaction :)
The deployment might take 5-15 mins, so not worth retesting now.

**Comment by ashmind** [comment]
@ForNeVeR The main bug that caused invalid C# was in my code (that's fixed now).
However the generated code — `((x == null) ? 1 : 0) == 0` — is still awkward.

So given all details in your report, might be worth updating it to an enhancement instead of closing — but up to you.

**Comment by ForNeVeR** [comment]
Thanks for the fix and for the clarification. I've updated the ILSpy issue and reclassified it as an enhancement.
