### ISSUE TITLE
error CS9064: Target runtime doesn't support ref fields.

### ISSUE THREAD

**Issue by John0King** [ashmind/SharpLab#1197]
`error CS9064: Target runtime doesn't support ref fields.`
`Types with embedded references are not supported in this version of your compiler`

I'd like to know what happened under the `ref` , but it seems it's not support

**Comment by ashmind** [comment]
Thanks for reporting -- what was the code that caused this issue?
Generally I would expect this to work now, since SharpLab was migrated to .NET 7 after this issue was reported.

**Comment by John0King** [comment]
I don't does is work or not,  because it keep connecting  and not  be connected  when using the "main"  branch 
<img width="817" alt="image" src="https://user-images.githubusercontent.com/13639146/204718423-9345568f-8cbe-472c-9229-6203057b4a88.png">

**Comment by John0King** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13639146/204718911-0d97e056-eb7d-41d6-80d3-f539983bb0dc.png">
