### ISSUE TITLE
Recursive generics result in a long compilation

### ISSUE THREAD

**Issue by VladimirReshetnikov** [ashmind/SharpLab#1223]
Not really a bug report, just a concern. Recursive generics can be used to create a [“compiler bomb”](https://codegolf.stackexchange.com/a/69200/8063) (which results in a very long compilation and huge output). Example:
```csharp
class Z<A,B,C,D>
{
    class X : Z<
        Z<Z<X,X,X,X>,X,X,X>,
        Z<X,X,X,X>,
        Z<X,X,X,X>,
        Z<X,X,X,X>>
    {
        class Y : X.X.X.X { }
    }
}
```
Compilation of this small fragment of code takes about 10 min and produces 2.8 MB output. I expect that variations of this pattern would consume much more resources (I decided to stop experiments at this point). Consider imposing time/memory constraints to keep the service responsive (but feel free to ignore my suggestion if you think it's not a serious issue).

**Comment by ashmind** [comment]
Thanks for reporting! I'll need to check and adjust the guards for this case.

**Comment by ashmind** [comment]
This is now limited on default branches (e.g. Default, x64).
Roslyn branches such as `main` might take a day or two to update.
