### ISSUE TITLE
Hide generated embedded attributes

### ISSUE THREAD

**Issue by OwnageIsMagic** [ashmind/SharpLab#1228]
Since #885 first screen-full of output look like this:
```
namespace Microsoft.CodeAnalysis
{
    [CompilerGenerated]
    [Embedded]
    internal sealed class EmbeddedAttribute : Attribute
    {
    }
}
namespace System.Runtime.CompilerServices
{
    [CompilerGenerated]
    [Microsoft.CodeAnalysis.Embedded]
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Parameter | AttributeTargets.ReturnValue | AttributeTargets.GenericParameter, AllowMultiple = false, Inherited = false)]
    internal sealed class NullableAttribute : Attribute
    {
        public readonly byte[] NullableFlags;

        public NullableAttribute(byte P_0)
        {
            byte[] array = new byte[1];
            array[0] = P_0;
            NullableFlags = array;
        }

        public NullableAttribute(byte[] P_0)
        {
            NullableFlags = P_0;
        }
    }
    [CompilerGenerated]
    [Microsoft.CodeAnalysis.Embedded]
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Method | AttributeTargets.Interface | AttributeTargets.Delegate, AllowMultiple = false, Inherited = false)]
    internal sealed class NullableContextAttribute : Attribute
    {
        public readonly byte Flag;

        public NullableContextAttribute(byte P_0)
        {
            Flag = P_0;
        }
    }
}
```
It looks interesting on the first time you see it, but after some time you getting sick scrolling this all the way down to yours 5 lines of real code.

Maybe you can add check box for some common compiler options (/checked, /nullable, /features:strict (is it still valid?))?

As quick workaround I suggest adding `// #nullable disable` to the top of default template.

**Comment by ashmind** [comment]
Thanks for the suggestion. I'll think on how to improve this. Maybe in the first iteration I should auto-scroll to the actual content, or change the code sorting to put all generated attribute definitions at the end.

**Comment by ashmind** [comment]
This now sorts user code to the top. Do you feel this solves the problem, or more active hiding is still needed?

**Comment by OwnageIsMagic** [comment]
Looks great. Can the same thing to be done with IL view?

**Comment by ashmind** [comment]
Good point, I'll do that as well (probably tomorrow).

**Comment by ashmind** [comment]
IL/ASM ordering is now updated as well.
