### ISSUE TITLE
Please show IL opcode comments as tooltips

### ISSUE THREAD

**Issue by alrz** [ashmind/SharpLab#124]
It's annoying when you want to copy/past IL and use it somewhere (like a test).

I'd prefer showing a tooltip just like how ILSpy does.

**Comment by ashmind** [comment]
@alrz Sure, makes sense.
This feature was contributed by @i3arnon so I'll cc him as well.

/cc @i3arnon — I hope you don't mind.

**Comment by i3arnon** [comment]
Of course... sounds like an improvement.
I would take a look myself, but I'm on vacation in the US.

**Comment by thomastay** [comment]
Hi, i was looking through old commits and found this code. I personally can't find the tooltips working for me (mouse hover over IL does nothing), and these IL comments would be super helpful for a beginner like me. Am I doing something wrong?
