### ISSUE TITLE
file scoped types (C# 11)

### ISSUE THREAD

**Issue by OwnageIsMagic** [ashmind/SharpLab#1240]
https://sharplab.io/#v2:EYLgtghglgdgPgMygGwKYAIDOAXATgVwGNt0AFAWACgBvK9e9AAQBZ0ANACk0IHsAHVABN0uVAjLo+ASnTUAvlTlA===
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/file

```
error CS0116: A namespace cannot directly contain members such as fields, methods or statements
error IDE1007: The name 'file' does not exist in the current context.
```

works on main roslyn branch, but probably also should on Default

**Comment by ashmind** [comment]
Thanks for reporting! This is now updated.
