### ISSUE TITLE
Support static constructors in disasm view

### ISSUE THREAD

**Issue by MichalPetryka** [ashmind/SharpLab#1264]
It'd be great if SharpLab could show generated (non-tiered) codegen with static constructors present. This wouldn't require them to be run, they'd just need to be present.

**Comment by svick** [comment]
I believe this is a duplicate of https://github.com/ashmind/SharpLab/issues/346.

**Comment by MichalPetryka** [comment]
> I believe this is a duplicate of #346.

Yeah, haven't checked but it looks like there already are #346 and #197. @ashmind Is there any progress on those?
