### ISSUE TITLE
Keystrokes are lost in mobile view

### ISSUE THREAD

**Issue by alrz** [ashmind/SharpLab#127]
Also, would be nice to completely disable autocomplete in mobile view for an uncluttered experience.

**Comment by ashmind** [comment]
Parts of it come from CodeMirror, so I might not be able to do much -- but I'll check.

**Comment by alrz** [comment]
works like a charm. thanks!

**Comment by ashmind** [comment]
@alrz Lol I don't think it's fully deployed yet :)

**Comment by alrz** [comment]
It was really annoying before, I didn't hit it with a quick test at least. :D

**Comment by ashmind** [comment]
Should be better now (well, as much as CodeMirror update can do) -- I've also disabled autocomplete, but can't fully disable autocapitalization due to browser issues.
