### ISSUE TITLE
Discrepancies in decompiled C# and IL/asm.

### ISSUE THREAD

**Issue by Vlad-Stryapko** [ashmind/SharpLab#128]
Consider the following snippet:

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgAwAERAjANwCwAUA0QMwUBMZAwmQwN4NlBFVkQAsZALIAKNADsYZCAgDmAVzBx5ASh70hZfnv1CAbkrKy4AdwBqStBGAY4AMQD2CAIIr1mhQF5FHw15OiNjLjdZKDdnADoAdQQ0eAAZOTgpS1t7R2d3L2C/LTD9AF8GMqA

In Debug build, IL and asm for a local variable 'newVariableForArgument' is produced as expected. However, decompiled C# doesn't contain this variable at all.

**Comment by ashmind** [comment]
Thanks for reporting! I believe it's caused by ILSpy over-prettifying/over-simplifying the code.
I'll see if there is some setting I can switch to disable it.
