### ISSUE TITLE
Main - Connection lost

### ISSUE THREAD

**Issue by bernd5** [ashmind/SharpLab#1289]
Currently the main branch does not work:

![grafik](https://github.com/ashmind/SharpLab/assets/26689688/d25f605f-254b-42f9-9a6d-43bb0385c3d6)

Could you fix this, please?

**Comment by jnm2** [comment]
This seems to be a recurring issue, anecdotally that affects the main branch more often than not when I'm specifically looking for it. What would it take to address the underlying issue?

- https://github.com/ashmind/SharpLab/issues/1226
- https://github.com/ashmind/SharpLab/issues/955
- https://github.com/ashmind/SharpLab/issues/814
- https://github.com/ashmind/SharpLab/issues/728
- https://github.com/ashmind/SharpLab/issues/614
- https://github.com/ashmind/SharpLab/issues/468

**Comment by jcouv** [comment]
I'm hitting this regularly and I've been unable to use sharplab to investigate roslyn reports as a result. I miss sharplab :-/

**Comment by bernd5** [comment]
@ashmind have you stopped supporting sharplab? The last commit is from May? No response on issues for months...
Very sad!

**Comment by ashmind** [comment]
Hi -- I wouldn't say stopped, but I was definitely taking a break -- with OSS, it is important not to get burned out
Generally SharpLab is designed to self-maintain, but since my uptime monitoring did not catch this type of issue (needs some improvement), I didn't notice main was broken.

I'll aim to fix it soon (this week).

**Comment by ashmind** [comment]
This is now resolved.

**Comment by jnm2** [comment]
@ashmind As of this morning, main moved from Sep 11 to Oct 4, and we're back to "connection lost" indefinitely.

**Comment by ashmind** [comment]
@jnm2 Thanks for the ping, this is now fixed (different root cause, deployment timed out).

**Comment by bernd5** [comment]
@ashmind now we see it again...

![grafik](https://github.com/ashmind/SharpLab/assets/26689688/ef24e42c-34b0-4237-8d2d-fd030149b17f)

**Comment by ashmind** [comment]
@bernd5 Thanks for the ping, fixed.

**Comment by jnm2** [comment]
@ashmind Happening again. #1305

**Comment by ashmind** [comment]
@jnm2 Thanks for pinging! I am currently travelling and can't address this urgently, but I'll aim to take a look on Monday/Tuesday.

**Comment by jnm2** [comment]
@ashmind Thank you! When you're in here, can you move default and x64 to .NET 8 now that it is GA (and LTS)?

**Comment by ashmind** [comment]
@jnm2 I was able to look a bit early, this should be fixed now. Though the root cause (random high CPU on other instance) is not fixed yet, so this might reappear at some point.

> can you move default and x64 to .NET 8 now that it is GA (and LTS)?

Yep it is a good idea and something I am planning to do. But I haven't set time to do this yet. Hopefully this month or early next month.

**Comment by jnm2** [comment]
Thanks so much! Is there a way that a second individual could aid in the effort year over year, both keeping the site up and moving versions forward? I'll volunteer my time.

**Comment by ashmind** [comment]
@jnm2 
> Is there a way that a second individual could aid in the effort year over year, both keeping the site up and moving versions forward? I'll volunteer my time.

Thanks! I appreciate the idea.

Generally if you see branch failing, and can identify the issue (`https://branch_url/mirrorsharp/status` might give useful errors), I am always happy to accept a PR to fix it. However some problems are harder to resolve without access to SharpLab Azure account, e.g. this CPU issue.

Same applies to things like .NET upgrade. I am happy to take a PR to https://github.com/ashmind/sharplab-infrastructure (if we discuss first, as I might be doing the same change already), but I am not sure if the infra in its current state is easy to deploy and test without access to what's already in my Azure. Ideally it's portable, but I never tested it on a different account.

**Comment by MizardX** [comment]
@ashmind It happened again.

![Image](https://github.com/user-attachments/assets/9021cf7c-ad37-4e03-94ba-db0dd5812914)

**Comment by ZzZombo** [comment]
Still an issue for me.

**Comment by andrii-sudakov** [comment]
Happened again

<img width="2486" height="559" alt="Image" src="https://github.com/user-attachments/assets/9dcc3eb9-4ca8-40c4-b0ad-98b946fc53d3" />
