### ISSUE TITLE
Incorrect code decompilation for statically initialized arrays

### ISSUE THREAD

**Issue by CollinAlpert** [ashmind/SharpLab#1303]
Having the following code:
```csharp
enum Test
{
	One, Two, Three
}

static class TestValues
{
	public static Test[] Values { get; } = { Test.One, Test.Two, Test.Three };
}
```

I saw SharpLab generated this interesting static constructor:
```csharp
static TestValues()
{
    Test[] array = new Test[3];
    array[1] = Test.Two;
    array[2] = Test.Three;
    <Values>k__BackingField = array;
}
```

The statement `array[0] = Test.One;` is missing. Here is a link to the reproduction: https://sharplab.io/#v2:CYLg1APgpgdgrgWwAQBUoGcAuBYAUAbzwEgB5GKAGlQHcB7KlACwCcoo8BfPPAAQEYAbEh4AmVBkwA1AIYAbOBjyFcRHgGZhg8VgDaAXSQz5GJPiQBzKJgDcSDkgC8p7ZgB0ZSi9co6DCd5Y2O2tOIA=

**Comment by svick** [comment]
The decompiled C# accurately reflects the generated IL (comments by me):

```cil
        IL_0000: ldc.i4.3
        IL_0001: newarr Test // var array = new Test[3]
        IL_0006: dup
        IL_0007: ldc.i4.1
        IL_0008: ldc.i4.1
        IL_0009: stelem.i4 // array[1] = (Test)1
        IL_000a: dup
        IL_000b: ldc.i4.2
        IL_000c: ldc.i4.2
        IL_000d: stelem.i4 // arrat[2] = (Test)2
        IL_000e: stsfld valuetype Test[] TestValues::'<Values>k__BackingField' // Values = a
        IL_0013: ret
```

It seems the C# compiler does not zero-initialize array elements that were already zero-initialized when creating the array. (Since the value of `Test.One` is `0`.)

So it seems there is nothing wrong with SharpLab.

**Comment by CollinAlpert** [comment]
That makes sense, thanks!

**Comment by CollinAlpert** [comment]
That makes sense, thanks!
