### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by CoolCoderSuper** [ashmind/SharpLab#1305]
Whenever I try and type or do anything I get this .
![image](https://github.com/ashmind/SharpLab/assets/76707331/1741ae1c-8acd-4207-8012-12f6d3b8dc92)
![image](https://github.com/ashmind/SharpLab/assets/76707331/aa669a84-ac82-4099-a066-7db4cfd2f784)

**Comment by ashmind** [comment]
Thanks for reporting!

I can only take a look in a few days, but in the meantime can you try the Default branch? Likely only the `main` branch is broken.

**Comment by ashmind** [comment]
The main branch should now be fixed as well.
