### ISSUE TITLE
Update all to .NET 8

### ISSUE THREAD

**Issue by ashmind** [ashmind/SharpLab#1307]

**Comment by jnyrup** [comment]
Does the "x64" platform also run .NET 8?

This snippet using collection expressions from C# 12.0 compiles and runs on "main", but not "x64".
```cs
int[] M() => [42];
```

:x: [x64](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8BLAOwwG0BdAAgFkAKAShoF4A+GilAJioG4gA==)
:heavy_check_mark:  [main](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPrBBtAugAgFkAKASnwF4A+fbAFgCZcBuIA=)
