### ISSUE TITLE
Return a comment with a hint which functions can be used for debugging

### ISSUE THREAD

**Issue by AlexRadch** [ashmind/SharpLab#1315]
Return a comment with a hint which functions can be used for debugging

**Comment by ashmind** [comment]
Thanks for reporting. The comment still exists when you switch to Run mode?
(unless it was deleted manually from a specific snippet)
![image](https://github.com/ashmind/SharpLab/assets/166396/1cb93f11-cfae-413a-afa8-abd13dc42a1a)

**Comment by AlexRadch** [comment]
> Thanks for reporting. The comment still exists when you switch to Run mode?

Oh yes! It still exists in Run mode. I didn't know that the initial code changes for different modes.
