### ISSUE TITLE
Branch request for return, break and continue expressions

### ISSUE THREAD

**Issue by alrz** [ashmind/SharpLab#132]
Is it possible to add a branch for https://github.com/alrz/roslyn/tree/features/jmp-expr?

**Comment by ashmind** [comment]
@alrz I'll take a look (probably tomorrow), but might not be possible until #111.

**Comment by alrz** [comment]
FYI, my branch is off the https://github.com/dotnet/roslyn/commit/22db878a7bb6daaa69227e3ef12421dab09fd5b5 which is exactly before they've moved to 7.1. :)

**Comment by ashmind** [comment]
Ah OK -- should be fine, just need to fix #69 before I enable the build -- otherwise master will disappear.

**Comment by ashmind** [comment]
@alrz Very lucky point for a fork — so here it goes:
https://sharplab.io/#gist:2594f8d618ff1d23e5b1277bcd0c9ede//alrz-features-jmp-expr

I've disabled autobuild for the night so I can monitor that it doesn't break any branches -- but generally it will be built once per day.

**Comment by alrz** [comment]
This is awesome! re "Very lucky point for a fork" that was no coincidence. :)
