### ISSUE TITLE
Bump F# compiller to 8 version

### ISSUE THREAD

**Issue by rstm-sf** [ashmind/SharpLab#1326]
Currently the F# code compiled with [version 6 of the compiler](https://github.com/ashmind/mirrorsharp/blob/65e40783ed4acd24107eb8e34c6dcd244e9f9bb2/FSharp/FSharp.csproj#L21-L22), we need bump to version 8

Similar https://github.com/ashmind/SharpLab/issues/1229

**Comment by rstm-sf** [comment]
Done: https://github.com/ashmind/SharpLab/commit/f4a0269f7b5f9dccb97cc033773a083c47099bde

**Comment by ashmind** [comment]
@rstm-sf This will take a bit more time unfortunately, original commit did not update properly.

@psfinaki FYI -- I am seeing some challenges with the Run mode. I think SharpLab was never able to compile `target:exe` (some complexity with code not finding a `win32manifest` file), but previously I could pass the AST directly to the compiler, then rewrite the resulting IL to approximate an exe entry point. However the API has changed and I can no longer do this, so it seems I have to actually support exe properly.

This might take a bit of time to figure out.

**Comment by ashmind** [comment]
All done now. 👍

**Comment by psfinaki** [comment]
Thanks a lot @ashmind!
