### ISSUE TITLE
Web Site Is Returning "Service Unavailable"

### ISSUE THREAD

**Issue by JasonBock** [ashmind/SharpLab#1329]
Right now, if I visit sharplab.io...

![image](https://github.com/ashmind/SharpLab/assets/904213/a9fe2909-18af-436f-92e3-586ce57f30fc)

Didn't know how else to report this other than an issue here.

**Comment by 94sedighi** [comment]
@ashmind any info about this?

**Comment by bernd5** [comment]
@ashmind Can we help you?

**Comment by ashmind** [comment]
The issue should now be resolved. Thanks for pinging me!
Not sure on the root cause just yet, will look into it.
