### ISSUE TITLE
Undo (CTRL-Z) / String interpolation bug

### ISSUE THREAD

**Issue by Logerfo** [ashmind/SharpLab#133]
Steps to reproduce:
1) [Go to this sharplab code](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgAwAERAjANwCwAUEQMwUBMZAwmQN4Nn8UWRACxkAsgAoAlDz4D5AETgBjNJAxlsZALxkm1efLmGyAZRgI0AOwDmZKO10ASAETdcAM1YBfdyC/eLnT08t4M3kA=) or create a new one with the following code:
```c#
using System;
public class C {
    public void M() {
        Decimal d = 3;        
        String s2 = $"{d:f2}{d:f2}";
    }
}
```
2) Place the caret after the last `}` on line 5 (the string interpolation one).
3) Press backspace 6 times quickly. The line should now look like this:
```c#
        String s2 = $"{d:f2}";
```
4) Press CTRL - Z.

**Expected behavior:** code should now look exactly as the original, without errors.
**Actual behavior:** the code does look exactly as the original, but with errors:

> error CS8076: Missing close delimiter '}' for interpolated expression started with '{'.
> error CS1002: ; expected
> error CS1597: Semicolon after method or accessor block is not valid
> error CS1022: Type or namespace definition, or end-of-file expected

**Comment by ashmind** [comment]
This is a great report -- thanks! I know a possible reason, will look into it soon.
As a workaround for now, you can refresh the page to reset the server state.
