### ISSUE TITLE
Seems to be down right now

### ISSUE THREAD

**Issue by benny-yamagata** [ashmind/SharpLab#1332]
As of this writing May 6, 2024, Sharplab.io seems to not be working.  

Everytime I make any changes, nothing is happening.  At all.  Putting it in Run mode doesnt change anything.  And the console is outputting that the socket state is 0.  

Sorry this isnt a great issue.  Just didnt have another way of alerting without opening one up.

**Comment by ashmind** [comment]
Hi @benny-yamagata -- thanks for reporting.
Is it still happening?

I can't reproduce the issue at the moment.
