### ISSUE TITLE
Roslyn branches are not updated

### ISSUE THREAD

**Issue by cremor** [ashmind/SharpLab#1333]
Similar to #1270, but now it's stuck in January 2024.

**Comment by ashmind** [comment]
Thanks for reporting! Seems the package name produced by Roslyn CI has changed, I'll need to find the right name.

**Comment by ashmind** [comment]
Main should be updating properly now.

For other branches, might depend on various factors.
Please let me know as a separate issue if there is a specific other branch that should update, but does not.

**Comment by jnm2** [comment]
Seems to have broken shortly after this: https://github.com/ashmind/SharpLab/issues/1343
