### ISSUE TITLE
InvalidProgramException results in OverflowException

### ISSUE THREAD

**Issue by Logerfo** [ashmind/SharpLab#135]
#### Steps to reproduce:
1) Open a new [SharpLab](https://sharplab.io) page.
2) Insert the following line of code inside the `M()` method:
```c#
bool b = M() is var x;
```
#### Expected behavior: 
- Decompiled IL should work normally.
- Decompiled JIT Asm should crash due to `InvalidProgramException`. See https://github.com/dotnet/roslyn/issues/20452#issuecomment-311354089
- Decompiled C#/VB should work normally, _I guess_.

#### Actual behavior: 
- Decompiled C#/VB crashes due to `OverflowException`.

**Comment by ashmind** [comment]
Thanks for the report! I'll try to take a look later today.

**Comment by svick** [comment]
For the record, this only happens in Debug mode, e.g. this reproduces the issue: https://sharplab.io/#v2:CYLg1APgAgTABAYTgbwLACg5blALHAWQAoBKFDbSuAIwHtaAbGuAXkNLgEsBnOANwCGAJzgAPANwVsAXwzSgA===.

Now, considering that the compiler actually generates invalid IL in this case (specifically, executing `stloc` when the stack is empty), I think it's fine that the decompiler crashes. The decompiler could generate a nicer exception, but that's about it.

**Comment by Logerfo** [comment]
@svick I tested this with JetBrains' dotPeek decompiler and it returns a comment `// ISSUE: unable to decompile the method.`, but only for the method containing the broken code. Perhaps could sharplab do the same? Also, I'm not really into decompilers, so why does that happen? Is the IL executed in order to achieve the original source?

**Comment by Logerfo** [comment]
Decompilation also fails in release mode if you try a little harder: https://sharplab.io/#v2:D4AQDABCCMDcCwAoEBmKAmCBhCBvJEhUaIALBALIAUAlHgUYwEYD2LANhExALyW0QAlgGcIANwCGAJwgAPBIkbM2nAMa85Q0ZJkBPBYwC+SQ0A==

**Comment by svick** [comment]
> I tested this with JetBrains' dotPeek decompiler and it returns a comment `// ISSUE: unable to decompile the method.`, but only for the method containing the broken code. Perhaps could sharplab do the same?

Yeah, that sounds reasonable too. Though I don't know what is ILSpy's approach to invalid IL in general (ILSpy is the decompiler used by sharplab).

> Also, I'm not really into decompilers, so why does that happen? Is the IL executed in order to achieve the original source?

No, it just tries to understand the IL. And the IL says "read a value from the stack" at a point when the stack is empty. There's just no C# that can be generated for that IL

**Comment by ashmind** [comment]
Thanks for the details! Since it would be an error either way, I'm not sure a possible improvement (limiting it to a single method) is worth the effort. Most usages of SharpLab I've seen were about single method anyways.

It's a valid point, and I'll keep this open for now, but its unlikely I'll find time to improve this in near future.

**Comment by Logerfo** [comment]
The presented code to reproduce this issue is not valid anymore, so you may close this issue if you want. The improvement might be useful for another unknown compiler issues, but who knows...

**Comment by ashmind** [comment]
Thanks, going to close to avoid the effort to reproduce.
