### ISSUE TITLE
Errors should not prevent displaying the syntax tree

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#137]
Roslyn can construct syntax tree for any code, including code with errors. And sometimes, seeing the syntax tree for erroneous code can be useful. Because of that, I think it would be nice if I could use SharpLab to view the syntax tree of code with errors.

**Comment by ashmind** [comment]
@svick Thanks! I agree with this -- in fact I track this one under #110 -- and since you requested it explicitly I'll upgrade it from `someday` to `planned`. Just a note that I'm on a break from OSS for a bit, might not get to it until 16ᵗʰ or so.

**Comment by svick** [comment]
@ashmind Thanks. And I of course understand that people don't always have the time for OSS.
