### ISSUE TITLE
[F# -> C#] Uncaught SyntaxError: Unexpected number in JSON at position 548

### ISSUE THREAD

**Issue by 0x53A** [ashmind/SharpLab#138]
Paste the following file into the left side:

https://github.com/rspeele/TaskBuilder.fs/blob/master/TaskBuilder.fs

The right side does not refresh, it still shows the previous content.

![image](https://user-images.githubusercontent.com/4236651/27955376-d03a948c-6314-11e7-8bdf-c039cc5dafc5.png)

In the chrome debugging tools I can see that there is an unhandled error.

![image](https://user-images.githubusercontent.com/4236651/27955381-d6e85ddc-6314-11e7-836b-62f5f10e0b8a.png)

-----------

This tool is awesome, thanks!

**Comment by ashmind** [comment]
@0x53A Thanks for the report! This seems to be two bugs at once (fails, isn't reported properly), with first being related to the length of this code. I'll try to take a look soon, but can't promise any specific timeline.

**Comment by ashmind** [comment]
@0x53A Fixed. The code still gives an error -- but a proper, compilation error.

**Comment by 0x53A** [comment]
Thanks, that's great, it even shows the error in the left side: 

![image](https://user-images.githubusercontent.com/4236651/28015830-1fd8572c-6572-11e7-9604-a4d7ca7468c5.png)

One nitpick and one question:

Could you show the line number of the error on the right side?
![image](https://user-images.githubusercontent.com/4236651/28015842-3368c290-6572-11e7-9e37-a8a40ce2bf86.png)

And do you have an idea why the code fails to compile? Locally, it's fine.
According to msdn, the ``Unwrap`` extension methods is available starting from netfx40: https://msdn.microsoft.com/de-de/library/dd780917(v=vs.110).aspx

I don't actually care about that specific snipped, I'm just wondering what's the difference between local and sharplab.

**Comment by svick** [comment]
@0x53A My guess is that the issue is that `Unwrap()` is an extension method in the `System.Core` assembly. SharpLab probably doesn't reference it when compiling F# code.

**Comment by ashmind** [comment]
@0x53A
> Could you show the line number of the error on the right side?

Yep, however I don't think manually hunting for a line is the best option -- I'd rather make the errors clickable instead. In either case, I recommend raising a separate ticket, as I will likely forget any discussion happening in closed ones.

> And do you have an idea why the code fails to compile? 
I think @svick is right and it's about `System.Core` -- I'll take a look under #140.
