### ISSUE TITLE
Can't use tuples anymore

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#139]
When I try to use C# 7.0 tuples, it doesn't work anymore.

For example [this code](https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgBgATIIwG4CwAUMgMyYBM6AwugN6HoOanIAs6AsgBQCUt9jAgG4BDAE7oAHugC86Tlihlu+AgIC+hNUA==):

```c#
using System;
public class C {
    public void M() {
        var x = (1,2);
    }
}
```

Produces this error:

> error CS8179: Predefined type 'System.ValueTuple`2' is not defined or imported

This used to work before, and AFAIK, SharpLab explicitly references the `System.ValueTuple` package, so I'm not sure why would this fail.

**Comment by ashmind** [comment]
@svick Thanks for the report. Very surprising -- I'll look into it.

**Comment by ashmind** [comment]
@svick Fixed! My current guess is Windows Update installed 4.7, which breaks System.ValueTuple from NuGet when used in Roslyn.

**Comment by svick** [comment]
@ashmind Thanks.
