### ISSUE TITLE
Navigate to bookmark when already on site fails

### ISSUE THREAD

**Issue by citizenmatt** [ashmind/SharpLab#14]
When already on the site, if I try to navigate to a saved bookmark, the browser's location bar is updated, but the contents aren't - I have to open each bookmark in a new tab to get the right contents. However, if I hit enter on the changed location bar, the contents are updated.

**Comment by ashmind** [comment]
Thanks, I'll take a look.

**Comment by ashmind** [comment]
@citizenmatt Not sure when I can actually fix this (I don't use TryRoslyn much these days).
Pull request would be appreciated though.
