### ISSUE TITLE
F# does not work in branches other than 'NuGet Release'

### ISSUE THREAD

**Issue by vasily-kirichenko** [ashmind/SharpLab#141]
![img_2013](https://user-images.githubusercontent.com/873919/28237668-a21e762e-694d-11e7-8228-f1ed257c1587.PNG)

**Comment by ashmind** [comment]
@vasily-kirichenko Yes, those Roslyn branch builds are not fully stable yet -- but then they aren't useful for F# anyways.

I recommend using "Release (NuGet)" instead, e.g. https://sharplab.io/#v2:DYLgZgzgNAJiDUAfA9gBwKYDsAEBlAnhAC7oC2AsAFBH4bYDCAFAJTYC8V2X2pZARugBO2IgAsAlhAB0AWRbtsLIA===

**Comment by ashmind** [comment]
F# will now always redirect to the default branch (and hide branch selector).
