### ISSUE TITLE
Adding `features/readonly-ref` branch back

### ISSUE THREAD

**Issue by OmarTawfik** [ashmind/SharpLab#142]
Can you please add the branch `features/readonly-ref` of roslyn to the deployment?
This feature branch existed a few weeks ago and was of great use during development, but for some reason it was dropped in the current build. It would be great to have it back.

cc @ashmind

**Comment by ashmind** [comment]
@OmarTawfik Thanks for reporting -- I'll take a look at the build later today/tomorrow.
Normally it shouldn't drop branches that were previously available.

**Comment by ashmind** [comment]
@OmarTawfik I've reviewed it and unfortunately the branch is not currently buildable (requires VS preview which I'm hesitant to install on local). I can try to build latest buildable version -- might be old and not that useful though.

Otherwise, I'm planning to switch to Roslyn NuGet builds in the near future (after a large secret feature I'm working on right now), and to Roslyn build artifacts when those are available (see https://github.com/dotnet/roslyn/pull/20924#issuecomment-317128638).

**Comment by OmarTawfik** [comment]
I see. Thanks for the update. Will post here if something changed.

**Comment by OmarTawfik** [comment]
@ashmind I just checked out the feature branch on a new VM that has VS 15.1 (release) and it built correctly. Can you please tell me what is the issue you're seeing?

**Comment by ashmind** [comment]
@OmarTawfik -- interesting -- might be my fault then. I'll check in the evening, but if you have time, can you pls grab SharpLab, update `Build.config.json` to match that branch only, then run `Build-All.bat`?

**Comment by OmarTawfik** [comment]
I had some build errors restoring SharpLab tools. Will try to root cause it later, but I don't think I'll have time now :(

**Comment by ashmind** [comment]
@OmarTawfik Unfortunately I didn't have time to look at it yet, want to finish my current feature work first and it is taking more effort than expected. However my next priority will be making sure the branches are properly available.

**Comment by ashmind** [comment]
Now that code execution is released, I'm back to this one -- looking at whether I can get it from NuGet / Roslyn builds first -- if not possible I'll try to sort out the build issue.

**Comment by ashmind** [comment]
@OmarTawfik Looked at it again -- the error I'm getting is:
```
CSC : error CS1617: Invalid option '7.1' for /langversion; must be ISO-1, ISO-2, Default or an integer in range 1 to 6.
```

That's from `dotnet build`, version `1.0.4` which is the latest stable.
I tried forcing version 7, but it seems source is actually using 7.1 features (e.g. `default`), so it doesn't compile.

It seems this has to wait for either a stable 7.1 or https://github.com/dotnet/roslyn/pull/20924#issuecomment-320768378.

**Comment by OmarTawfik** [comment]
Aha, so the problem is that the C# compiler included with the `dotnet cli` is older than the one the Roslyn repo is using. This is easily fixable by building Roslyn through with its own toolset instead. This should take care of downloading the appropriate C# compiler and execute it. You can do that by either:

1. `Restore.cmd` then `msbuild Compilers.sln`
2. `Build.cmd` if you don't want to deal with msbuild.

**Comment by ashmind** [comment]
This is now done:
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRKgEwPYDsA2AnuhGADSYgDUAPgAIAMABHQIwDcAsAFB0DMLAExMAwkwDePJtJYC6AFiYBZABRIwTDDgKEmAS1wwmADwCUEqTIC+PK0A=
