### ISSUE TITLE
Broken link (cropped code) in specific case when `||` is used

### ISSUE THREAD

**Issue by Ky7m** [ashmind/SharpLab#144]
I am experimenting with a new `default expressions` feature from C# 7.1 and found case when generated link produces a cropped code. 

**Good case**: https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEDMACFAmDBhDAWACgBvEjSrTFAFgwFkAKFARgAYMoMBeDAEzgAzCAFcANjACURYlQzk58qgEshGJtx59BIiTAwAyQ1wwruusZKkVllRXbswAFggD2AdwwA7OF7YAdACCCADmomBw3jAAchLiAKIAHgDGcAAOMCpu3kzeEJFuQppSUgDctnYAvpUYNcRVQA===

**Bad case**: https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEDMACFAmDBhDAWACgBvEjSrTFAFgwFkAKFARgAYMoMBeDAEzgAzCAFcANjACURYlQzk58qgEshGJtx59BIiTAxIkXDCu66xkqRWWVFt2zAAWCAPYB3DADs4ntgDoAQQQAc1EwOC8YADkJcQBRAA8AYzgABxgVVy8mLwgI1yFNKSkAbhtbAF8KjGriSqA=

**Steps to reproduce**:
1. Open a Good Case link 
2. Replace logical AND operator `&&` to logical OR `||`
3. Duplicate tab or copy link and open in the new tab

**Comment by ashmind** [comment]
Thanks! Very surprising, I'll take a look.

**Comment by ashmind** [comment]
OK, I know what's wrong, should be fixed soon-ish.

**Comment by Ky7m** [comment]
Thank you! Appreciate it!

**Comment by ashmind** [comment]
@Ky7m Fixed -- notes:
1. The bad link should work now -- it was generated correctly, just not loaded correctly.
2. You might need to refresh the browser cache.

**Comment by Ky7m** [comment]
@ashmind, awesome! It works now!
