### ISSUE TITLE
Preprocessor Directives in the IL code

### ISSUE THREAD

**Issue by TarasKovalenko** [ashmind/SharpLab#161]
I try to use simple preprocessor directives for debug and release mode in C#.

For example:

    using System;
    public class C {
        public void M() {
            #if DEBUG
                Console.WriteLine("Debug");
            #else
                Console.WriteLine("Release");
            #endif
        }
    }

This code very simple and clear. 

But when I see into IL code I don't have anything about debug directive.

    .class private auto ansi '<Module>'
    {
    } // end of class <Module>
    
    .class public auto ansi beforefieldinit C
        extends [mscorlib]System.Object
    {
        // Methods
        .method public hidebysig 
            instance void M () cil managed 
        {
            // Method begins at RVA 0x2050
            // Code size 13 (0xd)
            .maxstack 8
    
            IL_0000: nop
            IL_0001: ldstr "Release"
            IL_0006: call void [mscorlib]System.Console::WriteLine(string)
            IL_000b: nop
            IL_000c: ret
        } // end of method C::M
    
        .method public hidebysig specialname rtspecialname 
            instance void .ctor () cil managed 
        {
            // Method begins at RVA 0x205e
            // Code size 8 (0x8)
            .maxstack 8
    
            IL_0000: ldarg.0
            IL_0001: call instance void [mscorlib]System.Object::.ctor()
            IL_0006: nop
            IL_0007: ret
        } // end of method C::.ctor
    
    } // end of class C

It's very interesting to me, why it happens. 

I mean why I don't see anything about DEBUG mode in IL code?

P.S live [example][2]

  [2]: https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgBgATIIwG4CwAUIcgMyYBM6AwugN6HqOZnIAs6AsgBQCUdDTQQGIwAM3QARAKIAhAKoBxAYJXUA9gDsAzmogBTAHQB1AE5hgegDJgNergCIJegEYBXAOb2e+AqsZC9CC09ZT9GKk0dfWMzC2tbBwAlQL0AQ2CvHzCAjRgxUIBfQgKgA===

**Comment by daniel-white** [comment]
I found that the `x-optimize` header is being set (or not) and only the `SetOptimize` method only adjusts the `CSharpCompilationOptions`'s `OptimizationLevel` and not defining the `DEBUG` preprocessor variable. See: https://stackoverflow.com/a/45692185/23528

**Comment by TarasKovalenko** [comment]
@daniel-white Thanks for updating

**Comment by ashmind** [comment]
@TarasKovalenko @daniel-white Thanks for reporting! I should be able to look at it sometime this week.

**Comment by ashmind** [comment]
Done -- works in main branch (NuGet), but might take a bit of time to apply to other branches:
https://sharplab.io/#v2:CYLg1APgAgDABFAjAbgLACgoGYECY4DCcA3hnOQjlACxwCyAFAJQlkXsDEAlgGZwAiAUQBCAVQDibdtMIB7AHYBnWQBsApgDoA6gCcuAFzUAZLvLUMARPzUAjAK4BzC0zToZ5DmpWK1U9+QIFZXVtPUMTM0sAJS81AEMfZ1d/T3lgXj8AXwxMoA=

**Comment by TarasKovalenko** [comment]
@ashmind Thanks a lot ;)
