### ISSUE TITLE
Add option to skip decompilation

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#170]
Sometimes, I want to have a link that shows whether some C# code compiles or not.

If the code doesn't compile, SharpLab works well: the right panel shows the error message(s) and the choice of "Results" doesn't matter.

But if the code does compile, showing the decompiled code, syntax tree or running it is unnecessary, something like "Compilation successful." would be enough.

Would it make sense to include this as an option in the Results combobox?

**Comment by ashmind** [comment]
This is an interesting idea -- on one hand an edge case, on other hand it's easy to do.
I'll see what I can do -- but can't promise any specific timeline.

**Comment by ashmind** [comment]
Done, pls see "Verify Only" in the output modes.
