### ISSUE TITLE
CSharpValidateFormatStringDiagnosticAnalyzer throws NullReferenceException on master

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#176]
When compiling even [very simple code](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABADAAmwEYBuAWAChLsAmfAYUoG9L83CAWfAWQAoBKVuxYV2YwkQCcA8qPYBfSvKA==) on master, the following warning is produced:

> warning AD0001: Analyzer 'Microsoft.CodeAnalysis.CSharp.ValidateFormatString.CSharpValidateFormatStringDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

I don't know if this is an issue with SharpLab or Roslyn, but since the warning doesn't show up in Visual Studio, I thought I would report it here first.

**Comment by ashmind** [comment]
@svick Thanks for reporting -- pretty sure it's a new case of dotnet/roslyn#16644 (code seems similar).
I've reported it as dotnet/roslyn#21886.

**Comment by ashmind** [comment]
@svick Resolved: latest version of MirrorSharp uses reflection to create internal `WorkflowAnalyzerOptions` needed by some analyzers.
