### ISSUE TITLE
Add support for ILAsm

### ISSUE THREAD

**Issue by Suchiman** [ashmind/SharpLab#183]
It would be great if you could fiddle with raw IL on the left hand side.

**Example workflow:**
1. Left (C# Mode): Type some C#
1. Right (IL Mode): Copy the IL
1. Left (switch to IL Mode): Paste IL
1. Right: switch to C# or run mode
1. Left (IL Mode): Keep hacking to do cool things 😎 

Awesome tool btw. 😄

**Comment by ashmind** [comment]
Thanks! This is something I've considered a few time, but couldn't find a great approach.
Do you know any ilasm library (other than Mono ilasm -- I'll look at that)?

**Comment by Suchiman** [comment]
I know that the official ilasm sources are on coreclr, but it's written in C++ unfortunately

**Comment by jamesqo** [comment]
> but it's written in C++ unfortunately

Is that a blocker? You don't have to call directly into the native ilasm library; just do something like `Process.Start` and target `ilasm.exe`, no?

**Comment by ashmind** [comment]
@jamesqo It's possible, but it's not an approach I would take in SharpLab. External process lifecycle is hard or impossible to control perfectly, and scalability and performance will be complicated as well.

I don't mind writing my own parser: that will allow some nice features such as autocompletion -- just not sure about the priorities yet.

**Comment by jnm2** [comment]
This would be really nice. While trying to investigate a binary breaking change, I wanted the ability to take the IL from the output side, paste it in the input side, remove a `conv` opcode, and run it to see how sign extension behaves.

Besides Run and C# decompiler modes, JIT Asm would be the other mode that makes sense.

**Comment by ashmind** [comment]
Hi everyone, thanks to @kkokosa and @vivekbm initial version of ILAsm support is now available.
Thanks for your patience!
