### ISSUE TITLE
AssemblyGuardException trying to use reflection GetProperty (Member is not allowed)

### ISSUE THREAD

**Issue by Logerfo** [ashmind/SharpLab#186]
I don't know if this is actually a bug or a known "not-feature", but here it goes:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABABgAJiBGAbgFgAoYgZkoCZyBhcgb0fIGVW1AGyUALJSoAOABQBKXv0EqYATwAOcAPYAzWQGUYCAJaYA5vIB0AcTgwACgm1aE62QCIAomA3qP8vQMKgC+jCFAA

**Comment by ashmind** [comment]
Thanks for reporting -- this specific method can safely be allowed.

**Comment by ashmind** [comment]
Allowed.

**Comment by Logerfo** [comment]
@ashmind why are the other methods not allowed?

**Comment by ashmind** [comment]
@Logerfo I need to review each method to understand whether it might be used to break sandbox -- and I have to take special care with reflection. It takes a bit of time and so I focus on unblocking explicit requests and logged exceptions first.
