### ISSUE TITLE
AssemblyGuardException: Size of locals exceeds allowed limit

### ISSUE THREAD

**Issue by Logerfo** [ashmind/SharpLab#187]
The following program runs fine if you remove the tuple assignment or the iteration:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABABgAJiBGAbgFgAoMyqgOgBkBLTAR3ocbEAzCwBslAEwsA7OQDejcksojq44gBYWADgAUASnmLlJgG4QE5ADadY5ALzlMcAO4BtALrzyVJOSkAvqwAKgD2XLAG/CYm3DDk3DhwAB4Agg7kpH6JKQBCGbTGMeS6NrBuOWkefmUwFZhJybkeho6ltnWVzTUd9Y2pLTTFSkUxAGahCHAQAMYAFrrmlpzwYAmY1h36o8MsAJy6K3Bg+tHKAYwBQA==

**Comment by ashmind** [comment]
@Logerfo Thanks, I'll review this as a part of #184.

**Comment by ashmind** [comment]
Fixed in #184.
