### ISSUE TITLE
Exception in Finalizer breaks the IL Viewer

### ISSUE THREAD

**Issue by Suchiman** [ashmind/SharpLab#205]
https://sharplab.io/#v2:C4LglgNgPgAgDAAhgRgNwFgBQMDMSBMCAwggN5YKUIB+RAFAJQVXmZXsLAAWATgPYB3BADsApkICCPAOYBXALajhwAKIAPAMaiADsDB9hjDGyoBfLKaA

**Comment by ashmind** [comment]
@Suchiman Thanks for reporting! I can't promise a specific fix time, but I'll try to look at it next week.

**Comment by ashmind** [comment]
Done -- but might take another 20 mins or so to get to alternate branches (non-Default).
