### ISSUE TITLE
Enable generating XML documentation

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#219]
When compiling code that contains incorrect XML documentation comments, no warnings are reported for them. I believe this is because XML documentation generation is not enabled when compiling the code.

For example, consider [this code](https://sharplab.io/#v2:D4ejAIB4GcFcFt4EMBOBPAfDApt8BjFbAMwF4AiAOQHsA7abe7ckLEORVTAWACgABAEzgAwnwDefAL5A):

```c#
/// <summary><see cref="Nonsense"/></summary>
class C
{
}
```

It does not generate any warnings. But if I compile it on my own, while enabling XML documentation generation, I get:

> Class1.cs(1,25): warning CS1574: XML comment has cref attribute 'Nonsense' that could not be resolved

I think XML documentation generation should be enabled when compiling code in SharpLab, so that problems in XML documentation comments are reported as warnings.

**Comment by ashmind** [comment]
Thanks -- this makes sense -- I'll take a look once I get back to SharpLab.
I'm not sure about the performance impact, so can't promise yet.
