### ISSUE TITLE
64-bit asm

### ISSUE THREAD

**Issue by 1tgr** [ashmind/SharpLab#223]
Under JIT Asm mode I only get:
```
; Desktop CLR v4.7.2558.00 (clr.dll) on x86.
```

Is it possible to get disassembly from the 64-bit JIT? It be good to see the results of vectorisation etc.

**Comment by ashmind** [comment]
@1tgr Yep, this is something I am planning to do, but no timeline yet.

**Comment by jnm2** [comment]
I'm interested in both modes. I was curious to compare the asm for testing whether a 64-bit int has exactly one bit set, bit there's no way to see that right now. 😄

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgZgARYCMAbAQEx4DCAsAFADedezB+RpwA9pwDZ4CSUAAqcA7ogDyAMwAqozgAoArgEsAdjDwAPAJRMWjWi2MEA7HgVa8AQgC8eAAw68AMguXXFqwFo8hHc629k4A3PrMAL7heNG4BCR4XLwCwmKSsvLKPJxqAObaekYG0cZY5h52js5uCh41Pn4BeEFVYUWRdFG0QA=

**Comment by roji** [comment]
Very important to understand the low-level details, hope this gets done soon :)

**Comment by ashmind** [comment]
Done: https://sharplab.io/#v2:EYLgHgbALANALiAhgZwLYB8ACAGABJgRgG4BYAKEwGZ8AmXAYVwG9zc39rMpcBZACgCUzVu1GEAnHwIDSZUQF9y8oA==

I might move it a bit in UI later on, but for now this should be good.
