### ISSUE TITLE
Support Span<T>

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#225]
[I tried to use `Span<T>` in SharpLab:](https://sharplab.io/#v2:C4LglgNgPgAgDAAhgRgNwFgBQWYCYEDCWA3lguUgCwICyAFAMoAOAhgHYA8YbwAfAgGcAlAmIIAvlnFA)

```c#
using System;

class C
{
    void M(Span<int> s) { }
}
```

But I got the error:

> error CS0246: The type or namespace name 'Span<>' could not be found (are you missing a using directive or an assembly reference?)

I believe to make this work, it's necessary to reference the System.Memory NuGet package.

I think `Span<T>` is a pretty important part of recent work on Roslyn, so it would be great if SharpLab supported it.

**Comment by ashmind** [comment]
Makes sense, I'll add this to the current milestone.

**Comment by ashmind** [comment]
In a formal sense, this is done.

However the fun part is `stackalloc`, and that requires a newer `Span<T>` (from myget). So far I can't win that against NuGet which ignores my `RestoreAdditionalProjectSources`. I'll close this when either I win or a newer lib is on nuget.org.

**Comment by ashmind** [comment]
The build worked, but now ILSpy is crashing when trying to decompile `Span ... = stackalloc ...` to C#.

**Comment by ashmind** [comment]
OK, all should work now (except for executing `stackalloc`, which is currently not allowed).
