### ISSUE TITLE
[JIT Asm]: jnz To Missing Label

### ISSUE THREAD

**Issue by airbreather** [ashmind/SharpLab#229]
Just discovered SharpLab and [plugged in](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgZgARYCMAbAQEx4BCAogHYDGA9gCZwAKECUiAsAFABvfnhGiRuAiTwBXWlAgAzOHgCWtGHgBKcCMwCS6nGQAUwAJ7wAVHgUqANnCR5G0jWo1M50sHGYBKYTFRIT4gsLxzK2cEFQBzPABeG3s4AGpUgG5A8NFI5XppBES8S2NbB3S/LNCc3MZGOzxaOHikhQg7bmra0RUFPGMCooSk0ws4PwByAFpJgJqekJ6w5ta8GARpOG7lsSHi0vK01Krs2oBffjOc9zwAD2KABh2e2juYABl6gAcQa/CoAB3FQwegACwGQ3muyWu1E9GgyjG8CmcEmfwWcLEwAQOgA1tV/j1WO1pHZUES4Q8kg9rIRHnhUjIGGC4PQ8b5jMiJoNCnhpnhJo85qdMViRPskocUpUXuKRLFGDBGE13l9GN85TlLnxKXtGF4fMxirJwWyOcwue4/GUUvzonE/KK9b1+sZVtDlrCsdT+XcteEdS7xAB2e4BkQ6nVAA=) what I was fooling around with the other day (lightly touched so it looks similar to what the original would look like after #223 with 64-bit registers), and saw an unexpected thing in the JIT Asm output.  The code at `L0040` says `jnz L0128`, but the listing only goes up to `L0052`.

Are my expectations out-of-line with reality, or should that `jnz L0128` actually say `jnz L0023`?

Just in case something changes between now and when you look at this again, here's the repro data:

SharpLab claims to be using dotnet/roslyn@3bf3a10.

# C#
```csharp
public static class BEncodeParser
{
        public static unsafe int ReadInt32(byte* file, out int consumed)
        {
            byte* orig = file++;
            byte cur = *(file++);
            bool neg = false;
            if (cur == (byte)'-')
            {
                neg = true;
                cur = *(file++);
            }

            int x = 0;
            nxtLoop:
            switch (cur)
            {
                case (byte)'e':
                    break;

                default:
                    x = x * 10 + unchecked((byte)(cur - '0'));
                    cur = *(file++);
                    goto nxtLoop;
            }

            consumed = unchecked((int)(file - orig));

            if (neg)
            {
                x = -x;
            }

            return x;
        }
}
```

# JIT Asm Output
```assembly
; Desktop CLR v4.7.2558.00 (clr.dll) on x86.

BEncodeParser.ReadInt32(Byte*, Int32 ByRef)
    L0000: push ebp
    L0001: mov ebp, esp
    L0003: push edi
    L0004: push esi
    L0005: push ebx
    L0006: mov edi, ecx
    L0008: inc ecx
    L0009: mov eax, ecx
    L000b: inc ecx
    L000c: movzx eax, byte [eax]
    L000f: xor ebx, ebx
    L0011: cmp eax, 0x2d
    L0014: jnz L0021
    L0016: mov ebx, 0x1
    L001b: mov eax, ecx
    L001d: inc ecx
    L001e: movzx eax, byte [eax]
    L0021: xor esi, esi
    L0023: cmp eax, 0x65
    L0026: jz L0042
    L0028: lea esi, [esi+esi*4]
    L002b: add esi, esi
    L002d: add eax, 0xffffffd0
    L0030: and eax, 0xff
    L0035: add esi, eax
    L0037: mov eax, ecx
    L0039: inc ecx
    L003a: movzx eax, byte [eax]
    L003d: cmp eax, 0x65
    L0040: jnz L0128
    L0042: sub ecx, edi
    L0044: mov [edx], ecx
    L0046: test ebx, ebx
    L0048: jz L004c
    L004a: neg esi
    L004c: mov eax, esi
    L004e: pop ebx
    L004f: pop esi
    L0050: pop edi
    L0051: pop ebp
    L0052: ret
```

**Comment by airbreather** [comment]
And of course, reading the C# again fresh, there's a [more sane way](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgZgARYCMAbAQEx4BCAogHYDGA9gCZwAKECUiAsAFABvfnhGiRuAiTwBXWlAgAzOHgCWtGHgBKcCMwCS6nGQAUwAJ7wAVHgUqANnCR5G0jWo1M50sHGYBKYTFRIT4gsLxzK2cEFQBzPABeG3s4AGpUgG5A8NFI5XppBES8S2NbB3S/LNCc3MZGOzxaOHikhQg7bmra0RUFPGMCooSk0ws4PwByAFpJgJqekJ6w5ta8GARpOG7lsSHi0vK01Krs2oBffjOc9zwAD2KABh2egHcACxSB/YBCUbypnA5tdwktdqIHkkHtZCI88KkZAx3nB6ABrXzGMbwPyDQp4aZ4SaPOanBbg/ZJQ4pSovC5XMk5TxQby+YqyejItEY4zuHFHfHROJ+UkgsJ9Aarea7MHg+7FaZ3Wk5S58UVBLAAdnuStEKpVQA===) to write that loop, which at least compiles down to the same x86, including the awkward `jnz` to a label I can't find.

**Comment by ashmind** [comment]
Thanks for reporting! Looks interesting, I'll investigate (no specific timeline though).

**Comment by ashmind** [comment]
@airbreather Thanks, seems like all my backwards jumps were incorrect.
Sorted it out, but only redeployed Default, other branches will redeploy in 4-5 hours.
