### ISSUE TITLE
Support ValueTask<T>

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#235]
I tried using the C# 7.0 feature "Generalized async return types" by writing [code that uses `ValueTask<T>`](https://sharplab.io/#v2:D4AQDABCCMCsDcBYAUCkAmCBhFBvFEhUAHBAGoCGANgK4CmIAbADwCWAdgC4B8EA4nU4BJTnQC2AQQDOAT3YBjABQBKCAF5eAFnRJkAXyA==):

```c#
using System.Threading.Tasks;

class C
{
    async ValueTask<int> GetItemAsync() => 42;
}
```

This fails with:

> error CS0246: The type or namespace name 'ValueTask<>' could not be found

I believe the solution is to reference [the System.Threading.Tasks.Extensions package](https://www.nuget.org/packages/System.Threading.Tasks.Extensions/).

**Comment by ashmind** [comment]
Thanks for the request! I've done the dev work, but it seems I can't deploy anything until projectkudu/kudu#2703 is resolved.

**Comment by ashmind** [comment]
Done!
