### ISSUE TITLE
VB Enum Flags Operators.

### ISSUE THREAD

**Issue by AdamSpeight2008** [ashmind/SharpLab#237]
@ashmind  Got favour to ask would mind, including
`https://github.com/AdamSpeight2008/roslyn-AdamSpeight2008/tree/EnumFlagExpression`
into the list on SharpLab.io so people can test it out.

**Comment by ashmind** [comment]
Should be available now -- don't know how to test the feature itself though.
Note that as far as I know latest ILSpy does not support VB decompilation, so once I upgrade to that (probably within a month or so) you will only be able to do VB=>C#, but not VB=>VB.
