### ISSUE TITLE
Connection lost when trying to print no-break space

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#246]
When I try to [run the following code](https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoHaBsKATCqgOw4DeOStphcALKQBwAUAlEgLwB8pATjZsAxgAsAhmA4IAHgEEEHLNgC+QA=), SharpLab keeps displaying "[connection lost, reconnecting…]", never successfully completing:

```c#
using System;

static class Program
{
    static void Main() => Console.WriteLine((char)0xA0);
}
```

The character U+00A0 is NO-BREAK SPACE and is used as thousand separator in cultures like cs-CZ (which is how I discovered this issue).

**Comment by ashmind** [comment]
Very interesting, thanks for reporting! (I have a guess)

**Comment by ashmind** [comment]
Fixed -- but might take some time before all branches get updated.
