### ISSUE TITLE
Project 🔥: Prototype

### ISSUE THREAD

**Issue by ashmind** [ashmind/SharpLab#253]

**Comment by omariom** [comment]
> No description provided!

![image](https://user-images.githubusercontent.com/1781701/38175735-cb97b952-35e9-11e8-913c-f4273b6b651a.png)

**Comment by ashmind** [comment]
Just don't want to build a hype if it doesn't work out. :)

**Comment by ashmind** [comment]
Too much effort to implement at the moment, and since this one succumbed to hype, I'll track separately. :)
