### ISSUE TITLE
Should Verify Only mode emit the results?

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#254]
As far as I understand it, the Verify Only mode only creates the compilation, but does not emit it. This is sufficient if you're interested in issues in the code you're writing in SharpLab. But it may not be sufficient to reproduce bugs in Roslyn, if they're in the emit phase.

For example, here is code (from https://github.com/dotnet/roslyn/issues/25571) where [Verify Only currently succeeds](https://sharplab.io/#v2:C4LgbgpgTglgZgTwD4AEAMACFBGA3AWACh0tsBWAwolAZiwCYMBhKAQwGcALJgGw/aIBvIljooAHFgBsGAPIA7Fh04AKAJQjhhDDp1hWUDOwDuMYAGNOsgEYArCOeAYAvBnkRjGAPZ2HwdZS6OiZmlhgqIRZWvo4a2kFaQUnmHBAYAJLy+jwwACZMHMAAogAe5hAADsAwXvIYAPogIkktRqZR4ZGWNvaxza0J/QMtKexpAHIArjw8AEoQcNAQ8uWl5VU1dRBlldW1TVTxw8coAJzSAHRMXgC2FTwQwBC5KFKUQ8et+oY3CNvrezqrn+u02gU+w2sUAgrAA1uDPgBfD4DKEw+Eo3SjNKZbJ5WQVaCsQFrUG1BoHCFtUKcTrtboxYBxKmJKlY1IYKYzeaLaErCCkjbkkFC+QHTFss6Xa53B5PF5vIgSqnfDC/EWAlwYDVg5UQtFwhHHZGHKkGjGmoImjAmxFAA), but [decompilation fails with an exception](https://sharplab.io/#v2:C4LglgNgPgAgDAAhgRgNwFgBQ8nIKwaZYwDMSATAgMIBOAhgM4AWVEjDWA3lkmTABxIAbAgDyAO1qMmACgCUPbpgQqVANzo0EDAO5hgAYyaiARgCsApgeAIAvAnEWdCAPbmrweYVUrd+owgyfobG7tYKyj5KPjEGjBYIAJLiGhBgACZUjMAAogAeBhYADsBgLuIIAPogPDF12nohgcFGppbhtfVRnV11cQwJAHIArhAQAEoWAGYWNBbihfmFJWUVFgXFpeU1RJG9+zAAnMIAdFQuALZFEBbAFukwQoQ9+/UaWhcAnuvLWxX2P02q28r16JjmdAA1iDXgBfF5dcEWKEwvrxJIpOhpdKiIqzOh/JZA8pVHaghr+JjNRqtMLACLk6Lk1T9IajCbTWbzRYbFYkwF88Q7BHMpDHR5nS7XW73R7PPai1TvBBfAV/OwINXAkXMpEonUxeG7cl66FYF5GhBG2FAA).

Should Verify Only be changed so that it also emits the compilation, so that it surfaces Roslyn issues during the emit phase?

**Comment by ashmind** [comment]
Good point, I agree. I'll update it to do the Emit (no specific timeline).
