### ISSUE TITLE
Chrome WebSocket doesn't support Windows authentication. It breaks WebSockets via NTLM authenticated proxy

### ISSUE THREAD

**Issue by omariom** [ashmind/SharpLab#266]
Seems like Chrome is not going to fix this 3 year old bug.
https://bugs.chromium.org/p/chromium/issues/detail?id=423609

Related discussion: https://stackoverflow.com/questions/44612867/signalr-not-working-with-windows-integrated-authentication

**Comment by ashmind** [comment]
@omariom Thanks for reporting, pretty interesting.

Tbh I don't see this as a SharpLab bug — I think it should be fixed in Chrome.
Given Chrome is open-source, anyone can do it if motivated enough?

**Comment by omariom** [comment]
I didn't mean it was Sharplab's bug. Just wondered if there is an easy way to  fallback to non-websocket  transport.

**Comment by ashmind** [comment]
Yep, what I meant to say is I don't think it should be worked around in SharpLab.  
There is no easy way to fallback at the moment (I'm not using SignalR), and it's quite possible the bug would be fixed by the time I do any complicated fallback.
