### ISSUE TITLE
master is out of date

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#267]
Currently, the version of `master` that's available on SharpLab is https://github.com/dotnet/roslyn/commit/644e1e0e312a5c53e57ef9b0608c2f4ee76f882a from 14 March, i.e. more than a month old.

It seems that no branch was updated since 29 March, so it's probably not specific to `master`.

I don't know what is the cause of this, but it would be nice if the version of `master` used by SharpLab was updated.

**Comment by ashmind** [comment]
Sure, fixed. I don't monitor it well enough, so thanks for raising this.
