### ISSUE TITLE
Run mode does not behave to spec with code throwing an exception in using

### ISSUE THREAD

**Issue by Joe4evr** [ashmind/SharpLab#269]
This caught me off-guard, assuming that `Dispose()` would not get called if an exception occurred, yet all the SO questions about exceptions inside `using`s claimed the opposite.

[Reproduction code:](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEAMABLgIwDcAsAFDW4BMhACtQN7WEfEkBsxALFwAcACgCU7TmyqcZhGAgCeE2YSkqVAVShwxlaeoC+y2QGMIMEwAtCwgKIAPE3AAOMAJYB7TOP0q16mVIATmEAIgBhCHQAc0sYUNE9AKNfQhSZY1JeXAEtHR8ZfxVgsPCvWAwTd0xohKT1AhtMOAB3QgARMQL1IoCuENCAFUsEDxa3GrrjAJgRscJmtocnV09MXWnOdK3jTIZ2whBCAEl2tyhnDygIYAAbOGNewIBmfg7zy+0xQgBeAD5+mEzhcrnAACZTVIpAxAA===)
```cs
using System;

class P
{
    static void Main()
    {
        try
        {
            Use();
        }
        catch (Exception)
        {
            Console.WriteLine("Caught");
        }
    }
    
    static void Use()
    {
        Console.WriteLine("Constructing");
        using (new D())
        {
            Console.WriteLine("Throwing");
            throw new Exception();
        }
    }
    
    class D : IDisposable
    {
        public void Dispose() => Console.WriteLine("Disposed");
    }
}
```
Expected output (also seen in VS2017):
```
Constructing
Throwing
Disposed
Caught
```
Actual output:
```
Constructing
Throwing
Caught
```

**Comment by masonwheeler** [comment]
Looking at the various disassembly options here, it appears that the C# lowering is being performed correctly, but it's generating bad IL.

```
 .method private hidebysig static 
        void Use (
            bool 'throw'
        ) cil managed 
    {
        // Method begins at RVA 0x2084
        // Code size 48 (0x30)
        .maxstack 1
        .locals init (
            [0] class P/D
        )

        IL_0000: ldstr "Constructing"
        IL_0005: call void [mscorlib]System.Console::WriteLine(string)
        IL_000a: newobj instance void P/D::.ctor()
        IL_000f: stloc.0
        IL_0010: ldarg.0
        IL_0011: brfalse.s IL_0023
        IL_0013: ldstr "Throwing"
        IL_0018: call void [mscorlib]System.Console::WriteLine(string)
        IL_001d: newobj instance void [mscorlib]System.Exception::.ctor()
        IL_0022: throw
        IL_0023: leave.s IL_002f
        IL_0025: ldloc.0
        IL_0026: brfalse.s IL_002e
        IL_0028: ldloc.0
        IL_0029: callvirt instance void [mscorlib]System.IDisposable::Dispose()
        IL_002e: endfinally
        IL_002f: ret

        Try IL_0010-IL_0023 Finally IL_0025-IL_002e
    } // end of method P::Use
```

This should have a `.try { ... } finally { ... }` block in the IL, but it's not there.

**Comment by svick** [comment]
@masonwheeler 

> This should have a `.try { ... } finally { ... }` block in the IL, but it's not there.

I think that's an issue with the decompiler, not the IL. Notice how at the end of the IL, it describes the exception handling blocks (`Try IL_0010-IL_0023 Finally IL_0025-IL_002e`) and that decompiling to C# does show the `try`-`catch` block (which it would not do if it wasn't present in the IL).

**Comment by ashmind** [comment]
Resolved in default:
https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoHcBMSACjgN45KUqoBsKALNQBwAUAlBVedlb0sGACenPkm6jRAVQDOAU3ZYeEgL4i+AYwCGwdQAskLAKIAPdbIAOwAJYB7KByWjxE3mgCcLAEQBhTRADmusCebIouqo5IEbxqaHRwjDLyDrzOou5e3nbSAhDq1lD+IWESiAZQsgDuSAAi7CkSaS7UHp4AKrpgNpVWhcVqLsCd3UgV1SZmlrZQCgNU0fNqsYQ1SCBIAJI1VtLmNtKaAEYANrJqTa4AzAy1O3ty7EgAvAB8LV7bu/uyACb9kRFlEA===

Should be in `master` in a few hours if all goes well.
