### ISSUE TITLE
.NET Core - Initial prototype work

### ISSUE THREAD

**Issue by ashmind** [ashmind/SharpLab#273]

**Comment by roji** [comment]
A gentle ping on this - .NET Framework is rapidly becoming irrelevant, especially for the sort of high-perf assembly inspection investigations which SharpLabs is supposed to help with... It would be desirable to be able to see the assembly output from the latest versions of RyuJIT.

**Comment by ashmind** [comment]
@roji Thanks for your interest! This is now available:
https://sharplab.io/#gist:9761ed4fb5bb1ed9a4cf8704123616c7

![image](https://user-images.githubusercontent.com/166396/56714215-41489600-6788-11e9-9fea-23f73879b023.png)

Please report any stability issues separately. Support for x86 will be tracked separately.
Eventually .NET Core will be the default (for all branches), but I'll wait for version 3 to be fully released first.

**Comment by roji** [comment]
Wonderful news, can't wait to try it out!
