### ISSUE TITLE
Improve Explain mode matching (`readonly struct`, `private protected`, etc)

### ISSUE THREAD

**Issue by ashmind** [ashmind/SharpLab#282]

**Comment by svick** [comment]
@ForNeVeR See [ashmind/language-syntax-explanations](https://github.com/ashmind/language-syntax-explanations), which links to [this code with some explanations](https://sharplab.io/#v2:C4LgpgHgDgNghgSwHYBoAmIDUAfAAgBgAJcBGAbgFgAoXAZmICZCBhQgb0M8Oq+PtwAshALIAKZIWTBCcFIXFJgc0vgCUhAEbq2PXl0GEAMqO269hAL5m913lMIRCAXkJowAMzgBXGMEpVzTgR3eQ1JAGdCADc4ACdo1VsuAEhSAE5RKNUyQNzuAK4rAs5rOklFQgAFZwA+Qlp/CyA==). As far as I can tell, it's mostly for new and unfamiliar features of C#.

**Comment by ashmind** [comment]
You can see current list at:
https://ashmind.github.io/language-syntax-explanations/csharp.html

Even though this ticket mentions unblocking `readonly struct` etc, it does not actually include the explanation text for it -- I'll cover that in #289.
