### ISSUE TITLE
Asm missing for methods of types nested in generic classes

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#285]
```cs
using System;
using SharpLab.Runtime;

[JitGeneric(typeof(int))]
public class C<T>
{
    public class D
    {
        public void M()
        {
            Console.WriteLine("hi");
        }
    }
}
```

[Results in](https://sharplab.io/#v2:EYLgHgbALANALiAhgZwLYB8ACAGABJgRgG4BYAKB1wGUALRAJwAcAZRYAOgCUBXAOzgCWqAKaky5ANoApAXADiw3sPoCAxgAo4AT0bCA9gDN1A/gEpTAXXKYAzPgBMuAMIAeACoA+cgG9yASFsHXAARclxw3F8yCJj8O0woXABZdVMw2PCojIzCAE51ACIaAQLTMWzcAF908OqySqA==):

```asm
; Desktop CLR v4.7.2563.00 (clr.dll) on amd64.

C`1[[System.Int32, mscorlib]]..ctor()
    L0000: ret
```

**Comment by ashmind** [comment]
Might be related to #286, I'll take a look.
