### ISSUE TITLE
Shift+Tab does not unindent

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#287]
Slightly surprising since you have some advanced editor features like Alt+drag. It's typical for editors that support block indenting via Tab to support the reverse via Shift+Tab.

Tried on Firefox and Edge.

**Comment by ashmind** [comment]
Good point, tied to the default in codemirror/CodeMirror#2428, I'll apply their fix.

**Comment by jnm2** [comment]
Ah, this is awesome! The little things, right? 😃

**Comment by ashmind** [comment]
Small things are motivating to fix as well, because easy :)

**Comment by tlchatt** [comment]
Seems not to be fixed in current version.
