### ISSUE TITLE
Expose more IOperation properties in the syntax tree

### ISSUE THREAD

**Issue by alrz** [ashmind/SharpLab#302]
From the base type, e.g. `ITypeSymbol  IOperation.Type { get; }`

Or derived interfaces, e.g. `ITypeSymbol ITupleOperation.NaturalType { get; }`

**Comment by alrz** [comment]
Maybe we can expose an stringified form of symbols instead of a member-wise tree for each.

**Comment by ashmind** [comment]
Thanks - I'll look into it. String form certainly makes sense.

**Comment by ashmind** [comment]
Added some more properties.
Skipping `IOperation` properties for now -- not sure if that's confusing.

**Comment by ashmind** [comment]
Clarification: skipping `IOperation`-returning properties, and also all `Syntax` and any lists.
I'll close this one -- please raise a separate ticket if more info is needed.
