### ISSUE TITLE
Optional decimal parameters do not display correctly

### ISSUE THREAD

**Issue by vcsjones** [ashmind/SharpLab#316]
The following C# code:

```csharp
using System;
public class C {
    public void M(decimal w = 5.0m) {
        Console.WriteLine(w);
    }
}
```

Is shown in SharpLab as:

```csharp
public class C
{
    public void M(decimal w = default(decimal))
    {
        Console.WriteLine(w);
    }
}
```

**Comment by ashmind** [comment]
@vcsjones Thanks for reporting! I'm using https://github.com/icsharpcode/ILSpy for decompilation, I'll check if their latest version fixes this, or report the issue to them. No specific timeline though.

**Comment by ashmind** [comment]
This works now, however I decided SharpLab should reflect special case details (`[DecimalConstant]`) instead of a literal value.
