### ISSUE TITLE
Unsafe code may only appear if compiling with /unsafe

### ISSUE THREAD

**Issue by hypeartist** [ashmind/SharpLab#320]
Code containing unsafe blocks fails to run with an error:

> Unsafe code may only appear if compiling with /unsafe

**Comment by jnm2** [comment]
I keep hitting this too. Any way this is a possibility with Unbreakable?

Unbreakable always makes me think of Doctor Who—https://youtu.be/TfMj_tevwbg

**Comment by ashmind** [comment]
It might be a possibility depending on specific operations you are doing -- definitely not for everything.
Can you give some examples of what you wanted to try?

(Unbreakable is likely breakable, but I want to believe it won't be, one day)

**Comment by vladd** [comment]
@ashmind For example, using `sizeof` on custom structures [requires `unsafe`](https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoOBmJAZ2EgGNgkBlHAbxyQaQEsoKAzLbRpaQgQzYBTFKgBsKACxIAsnxYAKAJRIAvAD4RATnmEmAL0EB7NvMqLFnAL44gA).

**Comment by WhiteBlackGoose** [comment]
@ashmind hey, any chance sharplab will allow running code with unsafe blocks? 😅

**Comment by ashmind** [comment]
Hmm, I should definitely allow this now -- I will take a look (no specific timeline promises though).

**Comment by jsk95** [comment]
Unsafe code should work now!
