### ISSUE TITLE
[connection lost, reconnecting…] on Recursive patterns branch

### ISSUE THREAD

**Issue by gafter** [ashmind/SharpLab#322]
See https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMaOQSwG4SoAOsMECAdsgDQwg4A2APgAIAMABCwIwDcAsACgWAZi4AmDgGEOAbyEdFXMSwAsHALIAKAJRyFSgL5DDQA

I don't know why, but it appears this branch is broken.

**Comment by ashmind** [comment]
Fixed -- site got stopped for some reason.

**Comment by jnm2** [comment]
@ashmind The entire site is doing the "connection lost" thing right now.

**Comment by ashmind** [comment]
Right, that's #106 (and #315). Workaround: add `https://` manually.

**Comment by jnm2** [comment]
Thanks, totally missed that. Guess I'll have to start bookmarking it. :D
