### ISSUE TITLE
Run does not support ref returns

### ISSUE THREAD

**Issue by aalmada** [ashmind/SharpLab#323]
I know 'run' is experimental but you're asking for reports.
Here is an example that decompiles correctly but fails in 'run':

https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoHcDMKqAbCgExEDsSOA3jko0aWAKYBmSbAhgCYD2UADYBPJL1YBjAJYBbbkKQBZbgA8AFNKjipchUiEdgAGiRadM+YrDSA5gAtgASiQBeAHwMm3tp0PtgJHdXLjtHJAB+Lg4DIyQQaM4bB2AsbG8vRgJmFAAWIgAOdRdMpFoASBxy8rQATnUVDQRTVCcnNO8AXxxOoA===

Thanks for this awesome tool!

**Comment by svick** [comment]
That error seems to be specific to `ref readonly` returns. When I try regular `ref` returns, I get a different error: https://github.com/ashmind/SharpLab/issues/324.

**Comment by ashmind** [comment]
Thanks! This should be solvable, I'll look into it (no promises of a timeline though).

**Comment by ashmind** [comment]
I've fixed the immediate issue, however it still doesn't let your code run, because
```
ref left >= right ? ref left : ref right;
```
is seen as a dangerous pointer operation.

I'll see if I can make pointer validation a bit smarter.

**Comment by ashmind** [comment]
Hmm, I've underestimated the current algorithm, the only problem was `ref readonly`.
All sorted now (in Default branch), will apply to other branches in a day or two.
