### ISSUE TITLE
BadImageFormatException for method with ref return

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#324]
Consider [the following code](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgARwIwHYkFgBQBvXJIlVANiQEsphKBuQ4hotcsAUwDNLqkBZAQwAeACgCUSALwA+JOy4V6OYtiXEWKACwkAHGMkyBI0YoC+QA):

```c#
class Program 
{
    static int i;
    
    static ref int Max() => ref i;
    
    static void Main() => Max();
}
```

When I try to run it, I get:

> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
> at Program.Max()
> at Program.Main()

**Comment by ashmind** [comment]
Resolved in Default branch, and will be auto-applied to other branches within a day or two.
