### ISSUE TITLE
No deployments recently? (master is 45 days old)

### ISSUE THREAD

**Issue by OmarTawfik** [ashmind/SharpLab#326]
master is 45 days old on sharplab, similar to other branches.
I'm wondering if there is some break in the deployment?
I use SharpLab a lot for testing/developing language features and bugs.
Please let me know if there is something I can help with.

**Comment by OmarTawfik** [comment]
cc @ashmind

**Comment by ashmind** [comment]
Thanks for reporting! Fixed.
