### ISSUE TITLE
Type equality checking

### ISSUE THREAD

**Issue by YYProbe** [ashmind/SharpLab#329]
When I try to compare Type instances aquared via Reflection, the exception is thrown.
Example at https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQBEJinANjASQDsYIFsBjCAgWwAdcIaITYBLAeyIBoYQE4RAD4ABAAwACEQEYA3AFgAUCIBMEgCooYSgN5KJBqdIBsUgCxGAHAAoAlBP2G9iwxICQMyVAkBeCQCIACQhcXA5/BRdXQ08JYF8AgHUOBFwAEwjHaKMATmsoADoAcQgYdQBPOgg7AoBRAEc4KFxka2Bi0oqqu1tbSNcAXyUhxSA=
```using System;
class Test
{
    static void Main() 
    {
    	string a = "Hello";
        string b = "World";
        Console.WriteLine(a.GetType().Equals(b.GetType()));
    }
}
```

Both equality operator and Equals method do that.

**Comment by svick** [comment]
> Both equality operator and Equals method do that.

[Equality operator works for me.](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQBEJinANjASQDsYIFsBjCAgWwAdcIaITYBLAeyIBoYQE4RAD4ABAAwACEQEYA3AFgAUCIBMEgCooYSgN5KJBqdIBsUgCxGAHAAoAlBP2G9iwxICQMyVAkBeCQCIACQhcXA5/BRdXQ08JYF8AgHUOBFwAEwjHaKMATmsoADoAcQgYdQBPOgg7Xz9gYtKKqrtbSNcAXyVOxSA=)

**Comment by YYProbe** [comment]
Nope :/

https://sharplab.io/#v2:C4LgTgrgdgPgAgBgARwIwG4CwAoHOoCGAtgKYDOADgQMYlIAq5wA8gG4lhgCWAJiTgG8cSESgBMSAILDRQ7KIUoAzElZcwwCAQA2SLlGBIAsqgAUAShmKkc69bgB2JBiuKAvnnl24KtRq26+oZGYhauCrZ2Co5IYlhe1h4JSEmucBIAQkggUq6R9ioA9uycvHRBxmaWyRHh3k4ALHF1IkkKqcnpKKgOeS3dAGwoDd0AHKZoCADaALpIBGAA5mTVUflRUkiFAEYAVkgAvEhQJADuSBkW8f0KAMIAFiTUANZGJMD3hTymO7sANEgAEQmQHmeIbUQPJ6vd6fb6/AHAsSg8EQpBQl5vD5fH57RFGJQo/odKIUbisAjAOhoIZwEYYmHY76SLZ47rIUhMgByxBIqzs6yiaAAnKYACSAxhkYD6RZITlwmwKr480huIk1OwUsDy2FfQ6s3YAOgA4u96ABPCgkCym95YuGmZU8VV81EQrgAMyQTr1PEORygEG02n5EMFaJF4uBfqVftdbj0ZGOhUMBApXG0BG22hIGrRikc7o2JLRlutSEMR2dRoAIk8s9woItyyRrprrF6fVWjsArSRCp7TJJzGGNhGIVHAVzU1sStw+FB82i2miSNoyPwO4oJxsoxK2BwFyQoHpTwJgEaAGLB7QJ5cQ1eJVxJJJAA==

**Comment by svick** [comment]
@YYProbe That one is complaining about the equality operator for `MethodInfo`, not `Type`.

**Comment by YYProbe** [comment]
Let
```
string a = "Hello";
string b = "World";
```
`Console.WriteLine(a.GetType() == b.GetType());` works fine
`Console.WriteLine(a.GetType().Equals(b.GetType()));` fails with exception `Unbreakable.AssemblyGuardException: Member System.Type.Equals is not allowed. `

**Comment by YYProbe** [comment]
> That one is complaining about the equality operator for `MethodInfo`, not `Type`.
Really, if I use `ReferenceEqual(method, null)` in the example above everything works fine.

**Comment by ashmind** [comment]
Thanks for reporting! This is a whitelist edge case, obviously I should allow `Type.Equals`.
I'll sort it out (though no specific timeline promises).

**Comment by ashmind** [comment]
Resolved, might take a bit of time to apply to all branches though.
