### ISSUE TITLE
Recursive patterns branch is out of date

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#336]
The "C# 8.0: Recursive patterns" branch on SharpLab is currently on a commit from 14 May 2018. The corresponding branch of Roslyn, [features/recursive-patterns](https://github.com/dotnet/roslyn/commits/features/recursive-patterns) is being updated regularly. Could the version on SharpLab be updated? Thanks.

**Comment by ashmind** [comment]
This should be fixed now.
