### ISSUE TITLE
Entering IL source code

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#342]
While trying to investigate a binary breaking change, I wanted the ability to take the IL from the output side, paste it in the input side, remove a `conv` opcode, and run it to see how sign extension behaves.

Besides Run, other output modes that would make sense are the C# decompiler (fun one for this) and JIT Asm.

This would require an IL parser. Other than that, is there anything to it? These three output modes seem like they already work against compiled IL.

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/ashmind/SharpLab/issues/183.

**Comment by jnm2** [comment]
Good, thanks.
