### ISSUE TITLE
features/NullableReferenceTypes is missing

### ISSUE THREAD

**Issue by 333fred** [ashmind/SharpLab#343]
The features/NullableReferenceTypes branch is missing from sharplab. @ashmind, is there anything you need from roslyn to help restore the branch? Happy to help out if you need it.

**Comment by ashmind** [comment]
> @ashmind, is there anything you need from roslyn to help restore the branch? Happy to help out if you need it.

Thanks! Not for this case (seems to be just csproj/vbproj rename), but I'm still keen to stop building altogether if this is ever gets somewhere: https://twitter.com/ashmind/status/1022780582982344704

**Comment by ashmind** [comment]
The branch is back (for now), but until I solve the upload issue it might disappear again.

**Comment by 333fred** [comment]
@jaredpar is in the middle of moving our build artifacts off of Jenkins and onto Azure DevOps, but this is on his radar to add after we finish the migration.

**Comment by jaredpar** [comment]
Indeed. This has been on my list since you tweeted about it a while back. Then I thought I was just a week from being able to complete the move to VSTS (so optimistic). Now though I'm confident I'm close (it's in master) and I should be able to get to this very soon.

**Comment by ashmind** [comment]
The branch seems stable for a while now, so the upload issue was probably a short-term Azure bug.
