### ISSUE TITLE
Add 'enhanced-using' branch

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#344]
Could you add https://github.com/dotnet/roslyn/tree/features/enhanced-using? It's listed in https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md#c-80.

It would be cool if branches like this one showed up automatically.

**Comment by jnm2** [comment]
Looks like I asked for this in https://github.com/ashmind/SharpLab/issues/331.

**Comment by ashmind** [comment]
Thanks, done, see https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQQHYAsoYMYQAmqcyAlhgOYA+AAgAwAEtAjANwCwAULQMzMAmRgGFGAb26MpzfrQAsjALIAKAJTjpmxpK1SGjAG5QEjKIwC8jDBADujACJlkABwD2yKMAA2ENZy6aAL46UiGMzghkRjAQgg5Obh7eECCMAJKOLu6ePuJhmnzMCpmJvupiwQHSlYFAA===

**Comment by jnm2** [comment]
Thank you! /cc @HaloFour
