### ISSUE TITLE
Inspect/Dump - return the value from the calling extension methods.

### ISSUE THREAD

**Issue by AntiTcb** [ashmind/SharpLab#347]
To make these extension methods more consistent to LINQPad's Dump/alleviating issues when copying code from it, I like to see having them return the value they're operating on, so that method chains such as `someObj.Dump().SomeMethodOfSomeObj().Dump()` are possible. Simple enough change to do myself, wanted to open the issue prior to submitting the PR.

**Comment by ashmind** [comment]
Thanks! I'll definitely accept a PR for `Dump()` (since it's designed to match LinqPad etc anyways).
Not decided about `Inspect()` yet, so maybe just `Dump()` for now.

**Comment by AntiTcb** [comment]
Dump just calls Inspect, so both would need to change. Or, just leaving the Inspect that returns the value as internal. Would that be preferred?
