### ISSUE TITLE
Could the version of F# being used be updated to the latest?

### ISSUE THREAD

**Issue by 7sharp9** [ashmind/SharpLab#348]
It would be nice to have the latest version of F# available!

**Comment by baronfel** [comment]
It _looks_ like it would just be updating `MirrorSharp.FSharp` with new versions of FSharp.Compiler.Service and FSharp.Core. If that's the case I'd be more than happy to submit that PR?

**Comment by ashmind** [comment]
Sure -- happy to accept a PR! Just MirrorSharp is fine, I can upgrade SL pretty easily.

(I vaguely remember trying to upgrade and running into some problems with autocompletion API changes, but I think MirrorSharp has tests on that, so should be easy to verify).

**Comment by ashmind** [comment]
This is now done (thanks to contributor work in ashmind/mirrorsharp#97).
