### ISSUE TITLE
Whitelist multi dimensional arrays.

### ISSUE THREAD

**Issue by Suchiman** [ashmind/SharpLab#351]
https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAGABJgRgG4BYAKHMwGZ8CJ8AmWgdnIG9zcv8bD7MouALIBDAJaoAFAEpO3DmW5LcEuAG0YAXVwjEiXAF5cqAKYB3FanUBWGNc2lF3AL7lnQA===

**Comment by ashmind** [comment]
Thanks! I'll take a look.
Note: might take a while as I'm not currently actively working on SharpLab issues.

**Comment by ashmind** [comment]
Hi @Suchiman -- the new execution model no longer restricts multi dimensional arrays in .NET 6+.

I noticed the link in this ticket is for .NET Framework, and .NET Framework still has the old restriction.
If it is important to support it in .NET Framework specifically, please let me know, as by default .NET Framework is not a priority for SharpLab and major improvements are unlikely to happen there.
