### ISSUE TITLE
Nullable reference type branch not working as expected.

### ISSUE THREAD

**Issue by PathogenDavid** [ashmind/SharpLab#352]
According to the branch info, SharpLab should include the new `#nullable enable` syntax, but [using it results in an error](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAGhhATjIB8ABABgAJuARgDcAWABQkgMRlsufBH4QyeApID0GgNoBbAPYATbBBCChAOkIcYAS10QLAYX276tgggDKEBADdbKmQLdH0yTBw6RmQAChh2CABKAF1JSW4AZn5keLgKGH4AWVovXPzJAG9JfhrBLKQoQzCsWnMBUPD5cQla/mrazKKSspgY4QEyMIisRP7emoBeAD5+Dun+Bf5JzpxugF80iUHhADZBACZ+AAV9BABzBChdSrm68zPuABYiqFsyGNmPVqVSB8yGpXY+X4umGkJg3TBNVevRhELyBU2hhIUGw8ORAyEAE4YqiRiEpvJ+AB+Kn8ABE0wAhHTEiJ+Fp6Uy6fwYqF+AB3KAIMh/O78GBGKC0JgCjxYfjAJRhKj8aQZXgAdgyQn4tmQ/DAtgAHhBDBZAfiaqS4RsthB+eCRjE5DhWeyNPwAOpCkVkMVOLwADhO5wArGYnFAyJMChQwn5fAUXfKsLYYL4oPKJVswqhk2olEhSCoVbd+HGyDlHn904ZxQwlPQhU8IOmEBZLeZidb0eSdvKaZz5My3RyGcPuTEAKqUAhC8tzhACgAWrdXS5gy71CogcYc+qgAp9ov4yqUas12t1+sNJrN/AAkvwoMhkHAHDnzYdEdDYejbWQ9qOnCMR0gAEhAOD6DK/K3FghgjgiiLCN2f75H26yDuOOCIe69IQVBMFwQhdKvAcEh7EAA===):

    error CS1024: Preprocessor directive expected

-------

Somewhat related, you cannot manually add the `NonNullTypes` attribute in run mode because [the assembly guard gets upset](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQDk4BstWFiAJQkiQDsBjCAFQE8AHFAGhhATjIB8ABABgAJuARgDcAWABQkgPTSAxGWy58EfhDJ4CkgNoBbAPYATbBBCChAOkIcYAS10QLAYX276tgggDKEBADdbKmQLdH0yTBw6RmQAChh2CABKAF1JSW4AZn5keLgKGH4AWVovXPzJAG9JfhrBLKQoQzCsWnMBUPClcQla/mrazKKSspgY4QEyMIisRP7emoBeAD5+Dun+Bf5JzpxugF80iUHhADZBACZ+AAV9BABzBChdSrm68zPuABYiqFsyGNmPVqVSB8yGpXY+X4umGkJg3TBNVevRhELyBU2hhIUGw8ORAyEAE4YqiRiEpkp+AB+Kn8ABE0wAhHTEiJ+LJ6Uy6fwYqF+AB3KAIMh/O78GBGKC0JgCjxYfjAVRhKj8OQZXgAdgyQn4tmQ/DAtgAHhBDBZAfiaqS4RsthB+eCRjFFDhWezpPwAOpCkVkMVOLwADhO5wArGYnFAyJMChQwn5fAUXfKsLYYL4oPKJVswqhk5pVEhSOoVbd+HGyDlHn904ZxQxVPQhU8IOmEBZLeZidb0eSdvKaZylMy3RyGcPuTEAKqUAhC8tzhACgAWrdXS5gy71CogcYc+qgAp9ov4ytUas12t1+sNJrN/AAkvwoMhkHAHDnzYdEdDYejbWQ9qOnCMR0gAEhAOD6DK/K3FghgjgiiLCN2f75H26yDuOOCIe69IQVBMFwQhdKvAcEh7EAA===):

    Unbreakable.AssemblyGuardException: Custom types cannot be defined in system namespace System.Runtime.CompilerServices.

**Comment by ashmind** [comment]
Thanks -- I'll take look, don't know what the issue is yet.
Note: might take a while as I'm not currently actively working on SharpLab issues.

**Comment by ashmind** [comment]
Fixed.

**Comment by PathogenDavid** [comment]
Thanks a lot!
