### ISSUE TITLE
Branch commit author doesn't properly handle Unicode

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#356]
The current commit on the features/recursive-patterns branch has been authored by Šimon Koníček, but SharpLab incorrectly displays this name as "+?imon Kon+?-?ek":

![](https://user-images.githubusercontent.com/287848/49328035-c331eb80-f569-11e8-935d-b2433008edc4.png)

**Comment by ashmind** [comment]
Fixed now, thanks @muojp!
Though `features/recursive-patterns` is currently inaccessible due to dotnet/roslyn#32044, you can see it working in `features/nullable-common`.
