### ISSUE TITLE
Point Sharplab against custom branch of Roslyn

### ISSUE THREAD

**Issue by YairHalberstadt** [ashmind/SharpLab#359]
I find Sharplab invaluable when working on Roslyn.

Is it possible to point sharplab in some way against a branch on a personal fork of Roslyn?

Thank you for a great tool!

**Comment by ashmind** [comment]
Thanks! Yes, please submit a PR to [Buld.config.json](https://github.com/ashmind/SharpLab/blob/master/Build.config.json), similar to this change:
https://github.com/ashmind/SharpLab/blob/125af99b66d8ab4bc63e92c2178315d0010ff974/Build.config.json#L8-L12

`Include` should be as specific as possible (please no more than 1 branch per feature).
Note that your branch will only update once per day.

**Comment by YairHalberstadt** [comment]
Thanks
This will mean that everyone will see the branch though, which presumably won't be useful for most people?
