### ISSUE TITLE
features/recursive-patterns is missing

### ISSUE THREAD

**Issue by alrz** [ashmind/SharpLab#366]
It's been a quite some time that it's not there anymore.

**Comment by ashmind** [comment]
Thanks for reporting! As far as I remember, it's dotnet/roslyn#32044 -- I hoped it would be fixed on Roslyn side, but it seems I need to either workaround or implement #362. I plan to do it, but not sure about the timeline yet.

**Comment by alrz** [comment]
@ashmind is it possible to build locally and point to my own Roslyn Binaries path? it's useful for testing branches that are not yet merged to upstream.

**Comment by ashmind** [comment]
@alrz Yes, if you run
```
powershell .\#build\Build-All.ps1
powershell .\#build\Deploy-All.ps1
```
you should get all branches matching Build.config.json (you can add your own repo there if you want).

This will create local IIS sites for each branch, and create `branches.json` that SharpLab uses to find the branches. For main SharpLab map `source\WebApp` to something in IIS (I normally use sharplab.local).

**Comment by alrz** [comment]
Note: features/recursive-patterns has been merged to master since. but it's is also behind a few months.

**Comment by jnm2** [comment]
Is this why there's no option that enables switch expression syntax?

https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGA3AWACgiUAmDAYSIG8iN6MBLAOxgwFkAKFtiASgx0GtQgzFYA7BggYoAd0YwAxgAsh4jCI0bsGALwA+DKQA067fXKGM2c2IC+BUQ3tFXhIA==

**Comment by alrz** [comment]
features/recursive-patterns was not merged to master on `28 Oct`. but it is now.

**Comment by ashmind** [comment]
I've updated `master` to latest, recursive patterns should now be supported.
Please let me know if anything is missing.
