### ISSUE TITLE
Inspect.MemoryGraph times out with recursive graphs

### ISSUE THREAD

**Issue by canton7** [ashmind/SharpLab#371]
I'm afraid I think I broke it... This times out trying to draw: https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIGYAEqCMA2bAJmxwHZMBvAWAChN7stcDUAWTAWQEMBLKACgCUlWgzGYAblzCYARpgC8mKAFMA7pgD2sgFYqAxsADaOALoBuUePqyjABlOK5lutcxXrASSgBnAA4GwAB0HCoAtppgAJ4A4mBcfgAW/LKCLmIAvrQZQA==

**Comment by ashmind** [comment]
Great find, thanks! I tested with other recursive graphs, but haven't thought about collection referencing itself.

Should be fixed now.
