### ISSUE TITLE
Is it possible to add "Features/unmanaged-constructed-types"?

### ISSUE THREAD

**Issue by hypeartist** [ashmind/SharpLab#377]
https://github.com/dotnet/csharplang/issues/1937#issuecomment-461001053

**Comment by ashmind** [comment]
Thanks for raising this! 

I have a feeling this should be in `master` now, but master is outdated as well.
I'm waiting for some more details in #362 before I can fix branch updates.

**Comment by ashmind** [comment]
Updated `master` and latest seems to include functionality from this branch:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABAzAAlgQFcBjGfAWQE8BlGE8gHgBUA+fAdwAtE58W+EPmIA7SKIgBzOCgCwAKADei/Gvx4B+AGYBLOABsUAbkUBfIA

I'm assuming this to be resolved, but please let me know if that is not enough.
