### ISSUE TITLE
Decompile as though using C# 1.0

### ISSUE THREAD

**Issue by davidwengier** [ashmind/SharpLab#385]
I noticed that string interpolation wasn't being decompiled properly (both `$"x{1}x"` and `string.Format("x{0}x",1)` got decompiled to `$"x{1}x"`) so was going to turn that option off in the `DecompilerSettings` that are passed to ILSpy and submit a PR.

Then I noticed how many properties there are on DecompilerOptions and realised that there was probably a better approach than to keep finding and setting individual properties.

Looking at [the constructor of DecompilerSettings](https://github.com/icsharpcode/ILSpy/blob/3806610d0ad0a147c4dc94a7d32bdc8edb6bbdfd/ICSharpCode.Decompiler/DecompilerSettings.cs#L45) it appears that by telling ILSpy that the code was compiled with C# 1.0, all of the options for newer compilers are turned off, which would seem to be what SharpLab aims for with its decompilation - that is, the lowest level of C# possible.

Since this was a simple change, I'll open a PR, but obviously you should feel free to close it and this issue if you don't agree with the approach.

**Comment by ashmind** [comment]
Thanks! This is now deployed to Default, other branches (`master` etc) should get within a day.
