### ISSUE TITLE
Only decompile dynamic partially

### ISSUE THREAD

**Issue by johnkellyoxford** [ashmind/SharpLab#387]
I think it would be nice to be able to see how `dynamic` works under the hood, but currently it still decompiles dynamic calls back into `dynamicVar.methodName()`

**Comment by ashmind** [comment]
Thanks for reporting! I believe this is now fixed (by @davidwengier's work in #386).
It works in Default now, and should work in other branches in a day or so.

Let me know if you see any cases when it doesn't decompile.
