### ISSUE TITLE
TypeLoadException using Span by ref

### ISSUE THREAD

**Issue by juliusfriedman** [ashmind/SharpLab#388]
https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIAYAEqCMBuAWAChUBmbHANmwCYKB2Ygb2MzYutQBZMBZAQwCWUABQBKVuxZF2szAGMAFvzABtALoLlYAM6YAvJigBTAO5aVGppgDkADxsxbDp/cfP3b1y4/ebmAF9CGTk2ADcVTB0AB34oAwtdADoAQR0AZVjRMWDQ8MidABtBeWMEmLik9OLSkRwnShziSVClFR0kgEkoGON5YHFcvIB1MEFgYwAJY0LCgHsRMGMAMyia4xzMAHotiMKIMvk56IBPFrk25O7e/sHzgPPcTh5R8amZ+cWVzEy4gB5LgA+KJZCQhNjSPKYQSrEQVKBJAAyxigAHNgIpMH9MI1zlCMWA5uYTOYUmBURAALYo4AAUTspWiwEEc2ywTx7AARNNZnMAISc1IZLLiJIAYWOJwAKgt4U1wYFiAEgA==

**Comment by ashmind** [comment]
Thanks for reporting! This is very interesting, I'll investigate (might take some time).

**Comment by ashmind** [comment]
This is now resolved (I've also added a small few related things, such as support for `span.Inspect()`).
