### ISSUE TITLE
Unexpected StackGuardException in small code

### ISSUE THREAD

**Issue by Suchiman** [ashmind/SharpLab#389]
I was wondering what happens to the original exception when an exception is thrown and caught inside a finally block so i wrote
```csharp
using System;

public static class Program
{
    public static void Main()
    {
        try
        {
            Test();
        }
        finally
        {
            try
            {
                Test2();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }    
    }
    
    public static void Test()
    {
        throw new Exception("From Test");
    }
    
    public static void Test2()
    {
        throw new Exception("From Test2");
    }
}
```
But i did not expect it to write `Unbreakable.Runtime.StackGuardException: Stack limit reached` to the console 😄
https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYwCYgNQB8ACADAAT4CMA3ALABQt+AzKWRKQEzMDstA3rcQNJNyrfFGIBZAIYBLVAAoAlP0F8agjcTiIAnis3E1BgwBUApgGc4S6uuMBffZoBmcqQBt3euwaPGN2t7+Gn7BmuZWbDZO/o4+wQDGUnAJABbE8gCiYAlmAA5wMgD2qMRmYMrx/qFhguQAnPLlira1xHGxGk4dgk6MzKLiEdaVITGCcKmIRQDuxKhmc9m5BcUKAEQAYtMAtsTD6y3dTn3CLKRDlnBRo6rjApPTcwtLOfmFJfJbu/tXbIetQRxexAA===

**Comment by ashmind** [comment]
Nice find, thanks! This is certainly strange, I'll investigate.

**Comment by ashmind** [comment]
Should be fixed now.
(for some reason exception handlers require extra stack space, and on x64 that extra was too small)
