### ISSUE TITLE
Unable to use index or range syntax

### ISSUE THREAD

**Issue by canton7** [ashmind/SharpLab#390]
Repro:

```csharp
public class C {
    public void M() {
        var te = "test"[0..2];
    }
}
```

Results in:

```
error CS0518: Predefined type 'System.Range' is not defined or imported
error CS0518: Predefined type 'System.Index' is not defined or imported
```

**Comment by ashmind** [comment]
Thanks for reporting! These classes are part of .NET 4.8 / .NET Core 3 which are not released yet.
I'll see if I can provide them anyways, but even if I do `"test"[0..2]` is a `string` feature which can only work when the above is released.

In the meantime you can define them yourself as well, see:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABAzAAmwCZ8BhfAbwFgAofewg7AFnwFkAKASktof/wA3CAnyiAvPgAMAOhlEA3HwYBfWmpq0AdhDBwoABwgBjOIQCMvOgzxi4EFAHstAGwCe+WAgCuxmPgBJLRQ4AA9KAQZlSNtscwA2fABLMAMXJOMk/0cDRAgYR1EgkNCOJK1/YRdvOB5xAD58EIAzCG8XGA5isK4la3oNflsEeydXDy9ffwAlCC0AczNqfvwASFtZhbgu4LDPGBEYJEDd8LhgngpB1XUgA==

However `"test"[0..2]` won't work even then.

**Comment by canton7** [comment]
Ah, of course - I was assuming you were using a master version of corefx. No matter, thanks for responding!

**Comment by Timwi** [comment]
> These classes are part of .NET 4.8 

.NET Framework 4.8 is out now, but these features still do not work. What else do I need to install?
