### ISSUE TITLE
Decompiler unlowers fixed size buffers

### ISSUE THREAD

**Issue by Suchiman** [ashmind/SharpLab#398]
```csharp
internal unsafe struct MyBuffer
{
    public fixed char fixedBuffer[128];
}
```
gets compiled and decompiled to the same thing again, without showing the `[StructLayout(Size=...)]` cheat, i think this worked in the past.

**Comment by ashmind** [comment]
Thanks for reporting! I think I know how to fix it (but still might take a while with other priorities).

**Comment by ashmind** [comment]
Resolved (in Default, other branches might take a day or so).
