### ISSUE TITLE
C# 8.0 Default Interface Methods do not compile

### ISSUE THREAD

**Issue by FiniteReality** [ashmind/SharpLab#402]
Using the C# 8.0 "Default Interface Methods" branch in SharpLab does not seem to work correctly, returning CS8701 (`Target runtime doesn't support default interface implementation.`) when it should at least compile successfully.

Any interface containing a default implementation appears to cause this issue, such as:
```cs
public interface C {
    public int X => 5;
}
```

The syntax tree, however, does appear to work as intended, if you ignore the CS8701 error.

**Comment by ashmind** [comment]
Thanks for reporting! I plan to switch branches to .Net Core 3.0 Preview which should sort this out anyway.
But no specific timeline at the moment.

**Comment by ashmind** [comment]
This is now resolved by #410 (use `master` as that branch is already merged).
