### ISSUE TITLE
Investigate switching Roslyn branches to .NET Core

### ISSUE THREAD

**Issue by ashmind** [ashmind/SharpLab#410]

**Comment by Suchiman** [comment]
Technically it would be cooler if `.NET Core` / `.NET Framework` was a distinct combo box but i take it, this is a design limitation?

**Comment by ashmind** [comment]
In a way -- I can create two sites per branch. But by the time it is done (considering lazy OSS time scale) .NET Framework might be almost irrelevant.

**Comment by RikkiGibson** [comment]
It would be handy to have .NET Core 3 for playing with Nullable because it would make the nullable flow analysis attributes available without having to declare yourself in source.

**Comment by RikkiGibson** [comment]
I think this will also let people start playing with default interface methods through SharpLab.

**Comment by ashmind** [comment]
Done! I cleaned up old branches that are not available on Roslyn build server, but you can try out default interfaces in master:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEDMACAlgO3ggMwgGM4MBJDAbwFgAoDR7PDADQAoBKDAXgD4MAVgDc9AL5A===
