### ISSUE TITLE
"Invalid" JIT Asm when initializing vector registers from scalar value

### ISSUE THREAD

**Issue by airbreather** [ashmind/SharpLab#413]
Link to the live version of this: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgDkBXfGKASzFwG4BYAKGqSUATOQDCfAN59yMylUEA1GGAzQAPABMIDYABsYAPnIKAFFp37yCAJTkAvEYB2MAO7HlqqJu17DJmzy8AL5AA=

# C# Input
```csharp
using System.Numerics;
static class C
{
    static Vector<double> V(double x) => new Vector<double>(x);
}
```

# JIT Asm Output
As of a few minutes ago:
```asm
; Core CLR v4.6.27615.73 (coreclr.dll) on amd64.

C.V(Double)
    L0000: vzeroupper
    L0003: invalid
    L0008: vmovupd [rcx], ymm1
    L000c: mov rax, rcx
    L000f: vzeroupper
    L0012: ret
```

Notice that L0003 is labeled as `invalid`.  I'm guessing that it's actually initializing `ymm1`.

**Comment by ashmind** [comment]
Thanks for reporting! I'll take a look, but it depends on whether SharpDisasm supports this instruction.

**Comment by 0xd4d** [comment]
It's `vbroadcastsd ymm1,xmm1` and it's supported but it thinks the 2nd operand can only be a memory operand so it's decoded as an invalid instruction.

**Comment by ashmind** [comment]
Interestingly, fixed by migrating to 0xd4d/iced.
