### ISSUE TITLE
Version dates are stuck at June 20th or earlier

### ISSUE THREAD

**Issue by RikkiGibson** [ashmind/SharpLab#414]
When I click "master" in the dropdown, it tells me this is the latest commit: https://github.com/dotnet/roslyn/commit/898bed74a765fedf3071c6f25c3804995d39c7fa

However, when I `#error version` [example here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobAZgAI8KBhCgbxIuasuwBYKBZACgEoGTFgF8So4gGJECAPYIKAN0RQAljIB2QA==) I actually see `3.3.0-ci (<developer build>)`. This is odd, because the [version in use](https://github.com/dotnet/roslyn/blob/898bed74a765fedf3071c6f25c3804995d39c7fa/eng/Versions.props) in the commit linked above is actually 3.2.0-beta4.

Any idea what could be going on here?

**Comment by ashmind** [comment]
Thanks for raising it! Fixed.
You can ignore `3.3.0-ci` btw -- all CI builds from Roslyn build server are `3.3.0-ci` for some reason.
