### ISSUE TITLE
Date/commit SHA of the master compiler in use may be inaccurate

### ISSUE THREAD

**Issue by RikkiGibson** [ashmind/SharpLab#420]
We had someone report an issue in Roslyn based on SharpLab behavior, but pulling down the commit SharpLab says it's using for master (https://github.com/dotnet/roslyn/commit/b4cad279d19868389797c7e2b33dc0ed8d1e833b) did not produce consistent behavior between SharpLab and local testing. It's possible a compiler built from this commit is not actually being used.

**Comment by RikkiGibson** [comment]
Also, `#error version` in SharpLab gives version '3.3.0-ci (<developer build>)'. I think it should give '3.4.0-dev (<developer build>)'.

**Comment by ashmind** [comment]
Thanks for reporting! I might not have time to investigate it soon, however I have suppressed the commit info until it's sorted.

**Comment by ashmind** [comment]
I think I found what the issue was, so I'll unsuppress the commit info.
Please feel free to reopen if it reoccurs, but I think it's unlikely (at least until next time I "improve" deployments).
