### ISSUE TITLE
TimeGaurdExecption

### ISSUE THREAD

**Issue by rudrravarjula1234** [ashmind/SharpLab#422]
When i try to re-run the program with inspect stack and heap i am getting these error

**Comment by ashmind** [comment]
Yep, the limit is currently quite restrictive, I'll take a look if I can improve it (or optimize stack/heap commands).

**Comment by ashmind** [comment]
I have improved performance and it should happen way less often now.
If it happens again, please comment with a specific code that timed out and I can reopen.

**Comment by ashmind** [comment]
(should be solved by #438)
