### ISSUE TITLE
Sharp.io seems to be down

### ISSUE THREAD

**Issue by davidglassborow** [ashmind/SharpLab#423]
Currently connecting to sharplab.io leans to a greyed out page, with the message in the title bar "[connection lost, reconnecting…]".

The javascript console shows: 
`WebSocket connection to 'ws://sharplab.io/mirrorsharp' failed: Unexpected response code: 301`

**Comment by ashmind** [comment]
Thanks for reporting! This is likely a known issue (#315).

In the meantime, try going to https://sharplab.io directly. Http site should redirect you to https automatically, but sometimes it doesn't.

**Comment by davidglassborow** [comment]
Very strange, curl shows the correct 301 response, but both latest Chrome and Safari fail on macos 10.14.6.

Thanks for the quick response.
