### ISSUE TITLE
Proposal: Automatically define preprocessor symbols for TFM

### ISSUE THREAD

**Issue by GoldenCrystal** [ashmind/SharpLab#426]
# Proposal

Based on the list of preprocessor symbols listed [here](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks), define appropriate preprocessor symbols to apply on the code that SharpLab will compile:

 * For .NET Framework, define `NETFRAMEWORK` and `NET472` (or whatever version is used)
 * For .NET Core, define `NETCOREAPP` and `NETCOREAPP3_0` (or whatever version is used in the future)
 * Optionally, and if applicable, define `NETSTANDARD` preprocessor symbols that are supported by the selected platform. This may produce unexpected results if mixed with other symbols, though, so it would likely need to be exposed as its own setting.

# Rationale

This would be especially helpful when pasting code that already relies on these symbols.
Today, we can already define the symbols manually with `#define`, but they won't be updated when we switch between .NET Framework and .NET Core for comparing codegen.

# Example code

The [following code](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8B6YgYgBMYAzASwDsYACAOQFEAVAYQHkAlNgEEACsICwAKAACAJgCMksrWqtOvASPHSADEylyAdACEArtWowouANyKY9CssmSpAZj0ymXSQG9JTAL13fV0AWQAKAEp/QL8JJRV2bn4hURiAgEgpAHY9OW0DLlhsDBhwgA40JgwAC1pcKoB1KFpS/RlI23iYABtcGHSmDIBlAAdsegAeMBrsKAA+JmAzCygmAF4mXAxsMABrbB6eiDAmGbmAbXKAXS7A+6Zm1rLl80sq2vrOwfucpZXLAYOBBhhgWvQAOZRLpkeyOaiDAC+g0UylUyQ0aQk91GLQAbiVmPokExihQIPQegBPJhjCbtaazKBVLiLJ5tOQyaxMUgbR4tUowuFObGBQZuPIkqQofnPcJ0qbnBb/N7MrxbHalaKigJxB6BajQJjhBgYJi0PnabkWyYq1YGAAy9ghtWtAGo3dr9bqft7XqsLrRrnzwkrIigub6AsidUwY4igA) makes use of such a preprocessor directive:
````csharp
//#define NETCOREAPP
using System;
#if NETCOREAPP
using System.Buffers;
#endif

public class C
{
    public string M()
    {
#if NETCOREAPP
    	return string.Create(8, this, WriteAction);
#else
    	Span<char> buffer = stackalloc char[8];
        Write(buffer, this);
        return buffer.ToString();
#endif
    }
    
#if NETCOREAPP
    private static readonly SpanAction<char, C> WriteAction; // = Write;
#endif
    
    public static void Write(Span<char> buffer, C state)
    {
        for (int i = 0; i < buffer.Length; i++)
        {
            buffer[i] = (char)42;
        }
    }
}
````

**Comment by ashmind** [comment]
Thanks for reporting! This does make sense and I'll implement it (however no timeline promises).

**Comment by ashmind** [comment]
This is now done, except for two things:
1. This will not work on master and other Roslyn branches until #427 
2. I didn't include `NET472` as correctly detecting .NET Framework version does not seem easy, and .NET Framework support will eventually go away anyway. Please feel free to create an issue just for this if it is still important.
