### ISSUE TITLE
Call `Remove unnecessary parentheses` from sharplab will remove the wrong chars for the right side

### ISSUE THREAD

**Issue by yyjdelete** [ashmind/SharpLab#431]
https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKBQZgAJ1CBhQgb10JuKJQBZCBZACgEpLraeBLAM0KtWMBAFc47dlRw85tbvIC+iwipxKgA===

Click `Remove unnecessary parentheses` from the left bar. Seems SharpLab remove the chars at wrong index.
### Code
```cs
    public void M() {
        if ((true)){
            
        }
    }
```
### Expected:
```cs
    public void M() {
        if (true){
            
        }
    }
```
### Actual:
```cs
    public void M() {
        if (true))
            
        }
    }
```

**Comment by ashmind** [comment]
Good catch, thanks! I'll take a look.

**Comment by ashmind** [comment]
Should be fixed now.
