### ISSUE TITLE
sharplab.io doesn't load on Edge

### ISSUE THREAD

**Issue by Happypig375** [ashmind/SharpLab#433]
![image](https://user-images.githubusercontent.com/19922066/65937037-283bc380-e451-11e9-9df4-176fef5295d8.png)

**Comment by ashmind** [comment]
Thanks for reporting! That's a recent regression.

**Comment by ashmind** [comment]
This is now resolved, please refresh your browser cache if there are any issues.

**Comment by RikkiGibson** [comment]
insert pun about "pushed to edge"
