### ISSUE TITLE
sharplab.io doesn't load on Safari

### ISSUE THREAD

**Issue by reflectronic** [ashmind/SharpLab#434]
| Safari Desktop                                                                                                 | Safari Mobile                                                                                                  |
|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/27514983/66261879-336d5700-e7a3-11e9-814a-80ff658ee84d.png) | ![image](https://user-images.githubusercontent.com/27514983/66261858-c5289480-e7a2-11e9-8995-590d8dd8e3de.png) |

**Comment by ashmind** [comment]
Thanks for reporting! I don't have Safari at home, so I'll do the likely fix, but I can't guarantee it will work at the first try.

**Comment by ashmind** [comment]
@reflectronic Please let me know if the issue is fixed now (might need to clear the cache).

**Comment by reflectronic** [comment]
Yup, works now. Thanks 😄
