### ISSUE TITLE
Inspect.Stack displays intra-field padding in wrong place

### ISSUE THREAD

**Issue by tgjones-unity3d** [ashmind/SharpLab#442]
In this example:

https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUBgBjwwGYACAbzzJrNXIGdhIBjYMgWQE8BlZiNtVpVctMXXIAjLsACmZAIIBuIeIlkAllHYAhFaNoBfVXXTpKJsQEkoDAA6y2AOj4BDFgGsAFFFkB3Tl5+Ni8ASlD9MWNcQyA===

with this struct:

``` csharp
public struct MyStruct
{
    public byte A;
    public int B;
}
```

There are 3 bytes of implicit padding between `A` and `B`. However, `Inspect.Stack(new MyStruct());` puts these 3 bytes of padding at the end. I *think* this used to work correctly, so I think it might be a regression.

**Comment by ashmind** [comment]
Thanks for reporting! I'll prioritize this as I don't want people to learn incorrectly (no specific time promises though).

**Comment by ashmind** [comment]
Resolved.

**Comment by tgjones-unity3d** [comment]
Wow, that was extremely fast! Thank you 🥇
