### ISSUE TITLE
Attributes on generic constraints are omitted from the IL syntax view

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#444]
C# has no syntax for attributes on generic type parameter constraints, but doesn't ILAsm syntax let you express that? It was causing a lot of confusion in when decoding nullability attributes emitted by Roslyn: https://github.com/ApiApprover/ApiApprover/issues/54#issuecomment-546739595.

I would have expected to see `.custom instance` somewhere in https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwGIA7AV11wENhcYACGY62gWACh2ABAJgEZ2uAZjqdeSEdzoBhdgG92dRSOGjxnFHQBiECLwA8AFQB8ACgCUdAO4ALGLDoG6IOgEkAItgDOABwifm9LJ0AL4KSpwqYiIa2hDchqYWNnb0js7uXr7+NDAA/HRBoWxFQA===

```
.class public auto ansi abstract sealed beforefieldinit C
    extends [System.Private.CoreLib]System.Object
{
    // Methods
    .method public hidebysig static 
        void Foo1<([System.Private.CoreLib]System.IDisposable) T> () cil managed 
    {
        // Method begins at RVA 0x207f
        // Code size 1 (0x1)
        .maxstack 8

        IL_0000: ret
    } // end of method C::Foo1

    .method public hidebysig static 
        void Foo2<([System.Private.CoreLib]System.IDisposable) T> () cil managed 
    {
        // Method begins at RVA 0x207f
        // Code size 1 (0x1)
        .maxstack 8

        IL_0000: ret
    } // end of method C::Foo2

} // end of class C
```

If it's not possible in ILAsm syntax, could you add it as comments?
Actually, could it be added to the decompiled C# as comments, too?

```cs
public static class C
{
    public static void Foo1<T>() 
        where T : IDisposable // [constraint: NullableAttribute(1)]
    {
    }

    public static void Foo2<T>()
        where T : IDisposable // [constraint: NullableAttribute(2)]
    {
    }
}

```

**Comment by ashmind** [comment]
Thanks for reporting! This part of decompilation is handled by ILSpy, so I recommend trying it in latest ILSpy, and if it does not work there either, reporting at https://github.com/icsharpcode/ILSpy/issues.

If/once they support it, I can update to their latest.

**Comment by ashmind** [comment]
Seems like this is fixed in both IL and C# in latest ILSpy, closing.
