### ISSUE TITLE
Make framework drop down less missleading

### ISSUE THREAD

**Issue by yahorsi** [ashmind/SharpLab#447]
Hello!

Currently framework selection dropdown is very misleading.
E.g. what is .NET Framework, what version, is it X32 or X64 compiler
Whar default 3.3.1 means? Same for x64 and x64 profiler.

Thanks!

**Comment by ashmind** [comment]
Thanks -- it's a good point. I'll take a look at improving it.

**Comment by ashmind** [comment]
Improved it a bit.
Notes:
- I still want to have a Default as a default for when you don't care about a specific platform. So probably won't add more details there.

- Not sure if I can improve x64 -- I could say .NET Core, but once .NET 5 comes out, I'll have to update. Both default and x64 are basically "latest .NET".

- Not sure much can be added to x64 (Profiled). I would prefer not to have it as a separate item as you only need it for `Inspect.Allocations`, but it's a technical constraint at the moment.

**Comment by ashmind** [comment]
Since this ticket has several things, it's a bit hard to track -- I'll close with the current improvements, but please feel free to create new tickets for specific suggestions and we can discuss further.
