### ISSUE TITLE
Invalid decopmilation: accessibility level for CompilerGenerated method

### ISSUE THREAD

**Issue by Vasar007** [ashmind/SharpLab#451]
May be I do not know something about `[CompilerGenerated]` classes but the follow code is decompiled to invalid code (as I think):

```csharp
using System;

namespace Program
{
    public sealed class Handle
    {
        private readonly Func<int> _func;
        public Handle(Func<int> func)
        {          
            _func = func;
        }
    }

    public static class Program
    {
        private static void Main()
        {
            int F() => 42;
            var handle = new Handle(F);
        }
    }
}
```

The decompiled code has class `<>c` with method `<Main>g__F|0_0` which is inaccessible due to its protection level in `Program.Main` method.

```csharp
using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Security.Permissions;

[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
[assembly: AssemblyVersion("0.0.0.0")]
[module: UnverifiableCode]
namespace Program
{
    public sealed class Handle
    {
        private readonly Func<int> _func;
        public Handle(Func<int> func)
        {
            _func = func;
        }
    }
    public static class Program
    {
        [Serializable]
        [CompilerGenerated]
        private sealed class <>c
        {
            public static readonly <>c <>9 = new <>c();
            private int <Main>g__F|0_0()
            {
                return 42;
            }
        }

        private static void Main()
        {
            Handle handle = new Handle(new Func<int>(<>c.<>9.<Main>g__F|0_0));
        }
    }
}
```

Should be:

```csharp
internal int <Main>g__F|0_0()
{
    return 42;
}
```

**Comment by svick** [comment]
[The IL version](https://sharplab.io/#v2:C4LglgNgPgAgTARgLAChUDsCGBbApgZwAdMBjXAAhgQHZUBvVcpygZnP10wlwBNK5yACUzoe3RswYpmM8oQBOYAG6ZgFeZx4B7dBACelAKwAeMOmAA+cgH0AZgFd0JANwTZrISLG4AFDBNmluQOTgCUbrJ07jIR0TYhJOQAvMGOLrHMAL4R2WjSzPAsEVJxCsqqFFQAbJQALOQAsphmPuH57iVxzIHkAGKtyVa1cK7tXSry5AAWXtzJ5Oi4AO6eotw+vaGjcbkyuZlAA) of the method is:

```cil
.method assembly hidebysig 
    instance int32 '<Main>g__F|0_0' () cil managed 
```

Since `assembly` in IL means the same as `internal` in C#, I think this is indeed a bug in the decompiler used by SharpLab (i.e. ILSpy).

**Comment by ashmind** [comment]
Thanks for reporting! As @svick mentioned, this is something to raise with ILSpy -- please feel free to raise, otherwise I'll raise it myself later (might take a while though).

**Comment by Vasar007** [comment]
@ashmind, I raised an [issue in ILSpy repository](https://github.com/icsharpcode/ILSpy/issues/1863). It seems that they partially fixed the problem. See more in the issue.

**Comment by ashmind** [comment]
This seems to be resolved by recent ILSpy update, closing.
