### ISSUE TITLE
Add proper PWA support (enable PWA installation)

### ISSUE THREAD

**Issue by Sergio0694** [ashmind/SharpLab#452]
Hello, congrats for the project, it's incredibly well done and I've been using it for months, it has become an incredibly valuable tool for me and I appreciate your hard work on it! 😄

I was wondering if it'd be possible to make sharplab.io a proper PWA, so that it could be installed on devices that support the feature (eg. Android devices). Right now trying to add sharplab.io to the home page results in a simple shortcut being added to the home page, and clicking on it simply opens the website in a browser tab. This is the expected behavior for websites that don't properly support the minimum PWA specifications, otherwise the website should be opened in a standalone window (eg. like Twitter on mobile). I've tried both with Chrome and Edge Chromium, same result.

I've run a test on the website using Lighthouse and [got this report](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fsharplab.io%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext):

![image](https://user-images.githubusercontent.com/10199417/70160200-673cfe00-16ba-11ea-8955-154e65ca46c5.png)

Here's the [checklists guide](https://developers.google.com/web/progressive-web-apps/checklist?utm_source=lighthouse&utm_medium=unknown) from Google on PWAs.
Looks like simply adding a manifest should fix most of the issues and hopefully that'll be enough to have the app open in a standalone window.

Thanks again for your hard work!

**Comment by ashmind** [comment]
Thanks for the feedback and the idea! This makes sense -- I'll take a look. I always thought it would be separate app by default, but I think last time I tested it was before the manifest standard existed, so no surprise the behavior is different.

@jsk95 let me know if you want to take a look.

**Comment by ashmind** [comment]
@jsk95 Pls let me know if you still want to finish this or if I should take it.

**Comment by Sergio0694** [comment]
Hey @ashmind - glad to hear you're still looking into this issue!

I've had the chance to use sharplab.io quite a bit on mobile during the last few weeks, and I gathered more feedbacks to share on that front! Opened two issues for that:

- Glitchy text editor (https://github.com/ashmind/SharpLab/issues/476)
- Inconsistent/too large text size (https://github.com/ashmind/SharpLab/issues/477)

Hope this helps! 😊

**Comment by ashmind** [comment]
OK this should work now! The icon might be a bit cropped, but that would be a separate issue.
@jsk95 thanks for your help with this!

**Comment by ashmind** [comment]
Note that I opted for `minimal-ui` which show a browser bar on top, as that's the only way to get a shareable link for your code. Later I might add a mobile button for that -- then I would be able to further slim down browser UI.
