### ISSUE TITLE
Allow GetElementType to be used to run

### ISSUE THREAD

**Issue by YohDeadfall** [ashmind/SharpLab#455]
There should be no security issues to allow getting an element type. For instantiated arrays it's possible to workaround the limitation:

```csharp
public static class C {
    public static void Main() =>
        new [] { 1, 2 }.GetType().GetElementType().Inspect(); // Not allowed

    public static void Main() =>
        new [] { 1, 2 }.GetElementType().Inspect(); // Okay

    public static Type GetElementType<T>(this T[] array) =>
        typeof(T);
}
```

**Comment by ashmind** [comment]
Thanks for reporting! Seems safe enough, I don't see an issue with allowing it. No specific timeline though, but I am happy to accept a PR -- it should be added to https://github.com/ashmind/SharpLab/blob/b16c4cc623207f795c2c150b3c3f759a9f148d79/source/Server/Execution/Unbreakable/ApiPolicySetup.cs#L108-L121.

**Comment by ashmind** [comment]
Deployed -- thanks for the work! Seems that Roslyn branch build is currently broken, so those ones might take a while.
