### ISSUE TITLE
Cannot run when declaring a type with an indexer

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#457]
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEBmAAlgEMATCPAGwE8yBnDXMDMgMQggFgAUAG8hZcWVJkIwAFYxOZDAAsAliwDaqvF23UYCALpkAvAD4yeHPXoBuIQF8hQogCYSQ0YImTXrsRJePk6CDkA

```cs
public readonly struct Foo
{
    public object this[int index] => null;
}

public static class Program
{
    public static void Main()
    {
    }
}
```

> Unbreakable.AssemblyGuardException: Type System.Reflection.DefaultMemberAttribute is not allowed.

**Comment by ashmind** [comment]
Thanks for reporting! Should be an easy fix, though I am not sure when I will have time to take a look. In the meantime, I am happy to accept a PR to https://github.com/ashmind/Unbreakable (which handles this).

**Comment by ashmind** [comment]
Resolved (work done by @YohDeadfall) -- deployed now, though only to Default and various architectures, "Roslyn branches" are not deploying properly, for unrelated reasons.
