### ISSUE TITLE
The JIT disassembler does not recognize the FMA instructions.

### ISSUE THREAD

**Issue by teo-tsirpanis** [ashmind/SharpLab#458]
Writing

``` csharp
using System;
public static class C {
    public static double M(double a, double b, double c) {
        return Math.FusedMultiplyAdd(a, b, c);
    }
}
```
produces
```
; Core CLR v4.700.19.51502 (coreclr.dll) on amd64.

C.M(Double, Double, Double)
    L0000: vzeroupper
    L0003: invalid
    L0007: invalid
```

I guess the [FMA instruction set](https://en.wikipedia.org/wiki/FMA_instruction_set) opcodes are not recognized in the JIT ASM view.

**Comment by ashmind** [comment]
Thanks for reporting! This is handled by [SharpDisasm](https://github.com/spazzarama/SharpDisasm), but I am not sure how active the project is. I'll take a look, though no promises on timeline at the moment.

**Comment by YohDeadfall** [comment]
Probably it make sense to use [0xd4d/iced](https://github.com/0xd4d/iced).

**Comment by ashmind** [comment]
Thanks! Don't think it existed when I picked SharpDisasm. Should be reasonably easy to migrate.

**Comment by ashmind** [comment]
Sorted by migrating to iced, thanks for the tip!
