### ISSUE TITLE
'Stack push size exceeds allowed limit' in async method

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#460]
[Repro](
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyUBuauxsgOgBUALWAEMAJgEs8AczY0GTAKzT2JejxgBnDGvrUA3tXoHGJZQF4AfPTwwA7ivWaAFAEpe951wDiMDAEFrg0QwYKHcvDAAldRwAGwxnaUNtKkSiAGZGAA5GJDsNZ31DPWTExgBOegAzaBhBMD56BwA3QSh6UTa8SxtcjABRPBwAW2DBYGiYZycCxKKSwyYuJlKHUScEkoBfafotqm21GvHhIx7+oZGxmHoQegBJHzUATzwwM+GoUfGAHnEMM23ZiU0ncHs9XgN3oIMNAfng/vQwqCXm8RtCQttEgBhQQvGDRaJQ0QQPA8CAAaxgnTAOLAeIJGCJJPJlPoJi6tmxuPxhOJpIpeEmrP+xTmVlsqg0KI+aIcYvoABEhoNHvLgJiIINBjjhJN1gZdvsMLgwBhThDUdBriCnsjzdKYb9hTMMfQhMJidFHgqlSq1RqtXhjmBBsI9YZFZrfZERMEAPyumrCYKKEXzdK/eiYnBQWBw+g6egSbwsegABygomaQXoBwwJYNqYMwIlfTtUOgDgjytV6s12voweEU0b+ZdBgwfFEai4g9ZA5DYcSbuCc4G+MXhizOcpprZtA3DbmwKIWQAaoJojgYEQkF9gBAINELABZCCNGAAORgCF8NrA+RHQE5lECoGmXVoTDZNdomHOYDCAuDwLnIhykHLhegQGB/xcdU8AqUQJGzGA/ACOIKgvA41jHHZqGokCGhQhMYygLhox1HDiXwwjYBIwIHHI6JKNguCELmLdc13JikxYsJz0vCYqJHFIAHZ6CNK8N31ai8QORhVIEg4D1okdjzPC8rxvBUp1LCADiRbCXVEmjU0PQwDgvGBjlIb1Ix7f1tQBF170fNo1HCfA8HECQ5wMmAUyPdIT2yL4uyjRNggsDCsIAuYnIMECVjCiKoqcNSBAgWw5VuPBmmiURhAAeVLVFGQw2lSwZYkHAAIh8aI3S9XA8EiyRusUuiiuGqK53UuLqMYm8uHlPFBEeBwyFoDi8IIojeLIiiYHGpS9PZHzu2ANjgniF0G22VyDHco4TlS1VLqgQKRwzdo2TgMh4qBRKshvO8Hyfeg2Jyko8rKbIlpWtaNq2rjdv8PjYsUuD6AAaix0RNJO9ovnoVIjL2Ez0zzWTzIUoU2jDXYNiAA==)

> Stack push size in method `System.Void` `Tests/TestEnumerator/<MoveNextAsync>d__7::MoveNext()` exceeds allowed limit.

```cs
      public async ValueTask<bool> MoveNextAsync()
      {
        if (reader == null)
        {
          reader = await cmd.Exec().ConfigureAwait(false);
        }

        if (await reader.Read().ConfigureAwait(false))
        {
          Current = reader.GetValue();
          return true;
        }
        else return false;
      }
```

**Comment by ashmind** [comment]
Thanks for reporting! This one might take a bit of time. SharpLab does not currently allow Tasks, so even if I increase stack size limit, it might not help.

**Comment by ashmind** [comment]
Hi @jnm2, this now runs successfully (new Run mode is less restrictive overall).
