### ISSUE TITLE
Master and feature branch compilers don't seem to be working

### ISSUE THREAD

**Issue by RikkiGibson** [ashmind/SharpLab#461]
Hi there, I tried using the compiler in the dropdown list named "master (31 Dec 2019)", as well as the compiler named "C# Next: attributes on local functions (9 Jan 2020)" and they both seem unable to connect to the compilation service (they just turn gray and say "connection lost").

I figured you might want to know just in case there was something that could be restarted or something to get these working again.

**Comment by ashmind** [comment]
Thanks for reporting! Something interesting is happening there, might take some time to investigate.

**Comment by ashmind** [comment]
All branches should now be working and be up-to-date.
