### ISSUE TITLE
Error when running setup.ps1

### ISSUE THREAD

**Issue by NRKirby** [ashmind/SharpLab#464]
I get the following error when I try running the `setup.ps1` script

> C:\Projects\OpenSource\SharpLab\source\Native.Profiler\Native.Profiler.vcxproj(30,5): error MSB4019: The imported project "C:\BuildCustomizations\masm.props" was not found.

I ran the C++ tools installer in Visual Studio but I'm still getting this error. 

Can you advise what I need to do to fix this?

**Comment by ashmind** [comment]
Thanks for reporting! Not sure yet, will need to investigate.
@jsk95 You've seen that one as well?

**Comment by jsk95** [comment]
This is probably related to https://github.com/dotnet/sdk/issues/10239

**Comment by jsk95** [comment]
We can go back to msbuild or move out the cpp project. I vote for later 😄

**Comment by jsk95** [comment]
After resolving that, there is another error.
I believe https://github.com/ashmind/SharpLab/blob/dd481aa0238ca519a07fa372237876adb5aeb846/%23scripts/setup.ps1#L55

should just be Server.

**Comment by jsk95** [comment]
@ashmind Mind if I separate out the profiler?

**Comment by ashmind** [comment]
@jsk95 I would prefer to fix the build/setup instead -- separating feels like postponing the problem?

**Comment by jsk95** [comment]
@ashmind pick ur poison

1. switch back to msbuild
2. move out cpp proj
3. wrap cpp proj with a csproj

**Comment by ashmind** [comment]
@jsk95 Seems like I already did something for CI -- could do something similar:
https://github.com/ashmind/SharpLab/blob/master/%23scripts/ci.ps1#L9-L16

**Comment by ashmind** [comment]
@NRKirby This should be resolved now (thanks @jsk95!)
