### ISSUE TITLE
The master branch is not usable

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#468]
Repeat of https://github.com/ashmind/SharpLab/issues/461?

**Comment by jnm2** [comment]
Come to think of it, I haven't happened to see it working in the last year at all, I don't think.

**Comment by ashmind** [comment]
Unlucky :) I've seen it working right after I fixed #461.
Anyways seems like some infrastructure problem, I restarted the Web App and it works now as well.

Not the same as #461 -- might need to add more logging later to find out the root cause.

**Comment by ashmind** [comment]
Thanks for reporting!

**Comment by ashmind** [comment]
Added some monitoring so maybe next time I'll notice any issues faster.

**Comment by jnm2** [comment]
Thanks, I really appreciate it!
