### ISSUE TITLE
DllNotFoundException - Unable to load DLL 'SharpLab.Native.Profiler' or one of its dependencies

### ISSUE THREAD

**Issue by tebeco** [ashmind/SharpLab#470]
Hi ;)

Few days ago, i tried to show SharpLab.io to teamates after i remember about this tweet :
https://twitter.com/ashmind/status/1127430933924143109?s=20
![image](https://user-images.githubusercontent.com/2266487/75609480-45acb080-5b09-11ea-94ff-f47b2e760444.png)

So i attempted to re-create a simple scenario but i end up with an exception being throw :
![image](https://user-images.githubusercontent.com/2266487/75609503-77be1280-5b09-11ea-9e79-dd6f3a0ac56d.png)
```
System.DllNotFoundException: Unable to load DLL 'SharpLab.Native.Profiler' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at SharpLab.Server.Execution.Runtime.ProfilerNativeMethods.StopMonitoringCurrentThreadAllocations(Int32& allocationCount, Void*& allocations, Int32& totalAllocationCount, Int32& totalAllocationBytes)
   at SharpLab.Server.Execution.Runtime.AllocationInspector.InspectAllocations(Action action) in C:\projects\sharplab\source\Server\Execution\Runtime\AllocationInspector.cs:line 27
   at Inspect.Allocations(Action action) in C:\projects\sharplab\source\Runtime\Inspect.cs:line 75
   at Program.Main()
```

I hae no idea if this is related to the fact that the intellisens list `Inspect.Allocations` twice :
![image](https://user-images.githubusercontent.com/2266487/75609524-aa680b00-5b09-11ea-9920-77f8a0fe151f.png)
i just type `Inspect.Allocations` <== note that there is no `(` yet
if i play with `up` `down` arrow, both tooltip display `Allocation(Action action)`

Now if i do press `(` i can see either `Action ...` or `Func<T>` ....
![image](https://user-images.githubusercontent.com/2266487/75609558-ebf8b600-5b09-11ea-9f25-2e74f91b467a.png)

**Comment by ashmind** [comment]
Thanks for the detailed report! This is fixed now, though I noticed that in latest version it reports some unexpected allocations, so might need a bit more work to be 100% useful.

**Comment by tebeco** [comment]
\o/
weeeeeee
