### ISSUE TITLE
Allow Unsafe.SizeOf in Run mode

### ISSUE THREAD

**Issue by YohDeadfall** [ashmind/SharpLab#471]
`Unsafe.SizeOf<T>` is only one way to obtain the actual size of a type. `sizeof` works only at compile time, and `Marshal.SizeOf<T>` throws for non-interop types.

**Comment by ashmind** [comment]
Thanks for raising! Yep this makes sense -- I'll discuss this one within your pull request.

**Comment by ashmind** [comment]
Decided to implement this inside SharpLab after all, sorted in 9611b3f95c2a7dd5c4994ef7707fc782c6034c34.
