### ISSUE TITLE
Unbreakable.AssemblyGuardException: Member System.Delegate.GetInvocationList is not allowed.

### ISSUE THREAD

**Issue by Keboo** [ashmind/SharpLab#472]
The following code which tries to use Delegate.GetInvocationList() does not run.

```
using System;
public class C {
    public static event Action BarEvent = delegate { };
    public static void Main() {
        foreach(Action d in BarEvent.GetInvocationList())
        {
            BarEvent -= d;
        }
    }
}
```

**Comment by ashmind** [comment]
Thanks for reporting! This is fair enough, I don't think there is a reason to block this one (though I'll check the allocations). No promise of any specific timeline though.

**Comment by ashmind** [comment]
Hi @Keboo, this is now allowed (new Run model no longer block specific methods).
