### ISSUE TITLE
Adjust the text size on mobile (like GitHub)

### ISSUE THREAD

**Issue by Sergio0694** [ashmind/SharpLab#477]
Hello, I've noticed that the font size in sharplab.io on mobile is pretty large, especially when compared to the same document opened on GitHub mobile. This makes it more difficult to navigate snippets, as way less text can fit on the screen and on a single line, requiring often panning around.

Would it be possible to reduce the font size on mobile to be the same as GitHub mobile, or alternatively to add a way to manually adjust the font size on mobile? By that I don't mean to zoom in/out the whole page, but just to change the font size in the two text views in sharplab.

Here's a screenshot showing the same exact file opened in both sharplab.io and GitHub mobile. You can see the text in sharplab is larger, and in particular it seems like the font size in the text editor is larger than the text in the IL output, which also makes the two views not consistent on that front.

![image](https://user-images.githubusercontent.com/10199417/77165314-515d1880-6ab2-11ea-8fc5-65f3ea14282b.png)

Hope this helps, keep up the good work! 😄

**Comment by ashmind** [comment]
Thanks for the report! Yep, I kind of adjusted it to the sizes that worked well on _my_ mobile screen, and editor is intentionally larger to provide more precise selection. I'll see if I can provide a size selector/zoom option, doesn't seem impossible but will need to investigate UI patterns for this.

**Comment by ashmind** [comment]
Implemented 3 changes:
1. Default text size is same in both code areas (should be close to GH size)
2. There is a text size toggle in the footer (mobile only)
3. Removed restriction on pinch-to-zoom
