### ISSUE TITLE
Incorrect JIT asm when accessing static fields

### ISSUE THREAD

**Issue by Sergio0694** [ashmind/SharpLab#479]
Hi, I've noticed some weird behavior in the JIT asm window when using code that accesses static fields (both in non-generic and in generic classes). Consider this example:

```csharp
public class C
{
    public static int M()
    {
        return Test.SomeField;
    }
}

public class Test
{
    public static int SomeField;
}
```

This results in the following x64 asm:

```asm
C.M()
    L0000: sub rsp, 0x28
    L0004: mov rcx, 0x7ffb3056cb40
    L000e: xor edx, edx
    L0010: call 0x7ffb8827d930
    L0015: mov eax, [rax+0x8]
    L0018: add rsp, 0x28
    L001c: ret
```

I'm not really sure how is sharplab producing that, but it doesn't seem correct. What is all that code doing, and why is there even a function call? As far as I know, static fields just have a static address in memory once the type is JITted, and in fact using a Release x64 build in Visual Studio and showing the disassembly from there shows this:

```asm
; return Test<int>.SomeField;
00007FFF99AC1642  mov         ebp,esp  
00007FFF99AC1644  mov         eax,dword ptr [7FFF99B84E80h]  
00007FFF99AC164A  pop         rbp  
00007FFF99AC164B  ret  
```

Now of course the prologue/epilogue wouldn't be there in an actual Release build with the method being inlined, but still, the field here is effectively just read with a single `mov` instruction, as expected. Why is the output in sharplab so different in this case?

[Here is](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAIBlAC2ygAcAZbYAOgCUBXAOwwEt8MANwBYAFDjiAZnLEATOQDC4gN7jyG2TOIBGJOT69yAWQAUASnIBeAHzkAKjFwZWAMT4wANgBNRYzeTqmgDaAFJ8GADiMNwwUHxgphgAnvQwEABmpoYY5uYAukEa0rJ6BkbGADz2NhbWdo7O1TZuHj5+AL7iktoKjRiqRVql+jnk7l6+4l0SYiXyDk4YzYP+mvNlYxPt00A==) another sharplab.io test with also a generic class with a static field.

Thank you for your time! 😄

**Note:** possibly related to #197 and #384?

**Comment by dynamite7** [comment]
I have also noticed this, doesn't happen in .**NET Framework** platform and doesn't get as optimized.
I was afraid it was in an actual release build  because community say static variables are fast but Sharplab was displaying bigger JIT asm than fields.

**Comment by rsw0x** [comment]
Appears to be caused by making the assembly unloadable in the AssemblyLoadContext.

Assembly I get with it disabled:
```asm
    L0000: push rbp
    L0001: mov rbp, rsp
    L0004: mov rax, 0x7f5f6ec408ac
    L000e: mov eax, [rax]
    L0010: pop rbp
    L0011: ret
```

**Comment by Sergio0694** [comment]
A small update on this - as mentioned by Tanner Gooding the code generated by sharplab.io is technically correct, just without the tiered compilation. Basically:
```asm
L0004: mov rcx, 0x7ffb3056cb40 ; pass the type handle
L000e: xor edx, edx            ; 0
L0010: call 0x7ffb8827d930     ; static T initializer
```
Quoting him:
> I would need to look at a JIT dump to confirm, but my expectation is that the call is the static initializer. That is, the thing that allocates the space for the static and initializes the value to zero (or w/e value you set it to). It will effectively be a nop if called repeatedly and Tiered Compilation will ultimately remove it (after ~30 invocations of M1, assuming you are on .NET Core 3.1 or later).

So what @rsw0x is seeing is the "correct" code after the tiered compilation kicks in.
It'd be nice to be able to somehow force it in sharplab.io too, but that's probably asking too much.
Anyway, at least we know what's going on now! 😄

**Comment by ashmind** [comment]
Thanks for the investigation/report! As for the tiered compilation, I have #445 for that though I don't have a good approach yet. If this is just tiered compilation, should I close in favor of #445?

**Comment by Sergio0694** [comment]
Hey @ashmind - no problem! Also commented in one related issue citing this particular case, it case it helps. And sure, I'll close this issue and we can continue in just #445 since those are related.
Thank you for your time! 😄
