### ISSUE TITLE
Allow unsafe for decompilation

### ISSUE THREAD

**Issue by Yen** [ashmind/SharpLab#483]
There are several issue already about using unsafe contexts in run mode but I mainly need access to the decompiled JIT results to see what different code is generating in a performance critical situation.

Is this something that can be enabled in situations where the code will not be executed and just decompiled for viewing?

**Comment by ashmind** [comment]
Thanks for the report! Strange, I thought I already allow it.
I'll look into it (but no timeline promises).

**Comment by Yen** [comment]
Nope, you are 100% right, I forgot to add the unsafe keyword. 🤦

Thanks
