### ISSUE TITLE
Regression: Links no longer initialize page with saved language (always C#)

### ISSUE THREAD

**Issue by GrahamTheCoder** [ashmind/SharpLab#484]
### Repro steps
[Open the UI](https://sharplab.io/)

For me it's already broken at this point because it's trying to use the csharp compiler for a vb snippet:
![image](https://user-images.githubusercontent.com/2490482/79386380-f3610b00-7f61-11ea-8d28-a1808bcb8cf5.png)

Switch to CSharp language, then back to VB
It's now fixed, let's write some code:
```vbnet
Imports System

Public Class ReproLanguageIssue
    Public Shared Sub Main()
        Console.WriteLine("Hello")
    End Sub
End Class
```
Save the link:
https://sharplab.io/#v2:DYLgbgRgNALiBOBXAdlAJiA1AHwJIFsAHAe3hgGcACAZQE9yYBTfAWACh2AFRCYASwDGlAMLAAhuSoAlRoXjEAMmOQBzRGJWNckxI3aUDlbr0E0AFmPiM0NHpQCyYvsgAUASn2Gvw4snLFgRgA6AHV4PiYFZ0YXACIACUZgYGJYjzYvAFFkG2oedmybUQlydiA==

Open it in a new incognito window to be sure no cache stuff is getting involved - broken again:
![image](https://user-images.githubusercontent.com/2490482/79386628-5357b180-7f62-11ea-9dca-688a4e4649d8.png)

### Details
* Pretty certain this used to pick the correct compiler on first visit and when visiting a link
* I haven't checked FSharp, but I assume it's the same
* Let me know if you need anything else or if it's just me hitting this

Thanks for the great tool by the way, it's very useful for sharing repros for my VB/CS code converter:
e.g. https://github.com/icsharpcode/CodeConverter/issues/562#issuecomment-614218207

**Comment by ashmind** [comment]
Thanks for reporting! Preserving links is quite critical to me so I'm looking at this as a priority.

**Comment by ashmind** [comment]
Should be OK now! (might need browser cache refresh)

**Comment by GrahamTheCoder** [comment]
Yep, verified working, thanks 😁
