### ISSUE TITLE
Edge is broken again

### ISSUE THREAD

**Issue by Happypig375** [ashmind/SharpLab#485]
![image](https://user-images.githubusercontent.com/19922066/79458993-346e2380-8025-11ea-98de-8bf82e62f248.png)

Previous: #433

**Comment by ashmind** [comment]
Thanks for reporting! What version of Edge are you using?

**Comment by ashmind** [comment]
Should be sorted now for Edge versions > 14.

**Comment by Happypig375** [comment]
Fix verified. Thanks!

**Comment by ashmind** [comment]
@Happypig375 Question related to this issue: are you using Edge 12-18 with SharpLab?
Wanted to let you know I am looking to drop support for it in nearest future.
