### ISSUE TITLE
Incorrect JIT asm w/ intrinsics (eg. Sse2, Avx2)

### ISSUE THREAD

**Issue by Sergio0694** [ashmind/SharpLab#487]
Hello, I've noticed that `sharplab.io` seems to struggle quite a bit when showing the JIT asm for code using intrinsics (eg. `Vector256<T>`, `Vector128<T>` and the various `Sse2`, `Avx2`, etc. classes), which results in the asm code beind displayed incorrectly, often including `invalid` tokens and a bunch of incorrect instructions. I've prepared a [repro here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgylWoxbtOASRZRWTXNPnLV1eszYcaujPsPGaADQAcSRUtMAmAMzKA3srkwZQ+akjkzLjYAGYw5AYY5AAyENgAJgCCTOmiDPgA6qwYABYA8hIiMYIQAO4AFLAxCSzkUKQAlEEhgUoh/eQAajBgGNBeAKxIADyJAHzkEuQAvOQAqoaxnJm4syxoQyNjUJMz83ONMM3tHR4DId33xADsizR5hcXllVDVdfW3R7kAC+ylBnhUYWoEWIXkOo3GUwAoggMDAHBBDAEgQBtACyMFKEHS2n4gnqBKJJLJZT4bExuBomQA5szYLgjJVdIIDAZmR0ALpA4hQqgRRLkD5FUoVKo1BqlVi4eHHU57DALSoIqBdPo9IH9YbaqheFzqzUZdJUFaS3AwLxM9Lpepa440ADihNStREAIOrugHsJaz4fF9HUBevuRuOJrN80WJVYzJK1tWojtDo2fGwYAA1gAJZMlF2W2g7WyoP2LMtM3CVlAAjp12w+LwAu73FXQOPmmtOuHpzOO50SJMpqj+suRrvdqC9hNj4uD23294lBgxaowUsDg6kBBUGddmM9019iSWsJDteZJ279Jef3jkpeSMGkIvfvpHw0AAqECiGA2CCNgUAdkC4LgkAA===) that shows the issue both with a standalone method, and when the method is inlined into another method, in case it makes a difference.

In particular, you can see that this line:

```csharp
Vector128<int> vadd1 = Sse2.Add(vector.GetLower(), vector.GetUpper());
```

Is displayed as follows:

```asm
L000b: invalid
L000f: rol byte [rcx], 0xc5
L0012: invalid
L0014: or ebp, eax
L0016: int1
L0017: inc al
```

In particular it would seem that one of the APIs that causes this issue in `sharplab` is the [`Vector256.GetUpper()`](https://source.dot.net/#System.Private.CoreLib/Vector256.cs,ced05af3542e9224) extension, which should translate to [`_mm256_extracti128_si256`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=6014,6011,5143,6011,5214,6002,2457,2428,2428,2428,2457,2457,2457&text=_mm256_extracti128_si256&techs=AVX2) in this case.

This makes it particularly difficult to inspect/optimize code when these APIs are involved. I'm not sure if this is an issue with the `sharplab` backend in particular or something help, hope this helps! 
Keep up the amazing work! 😊

P.S. not seeing a donation link anywhere, if you ever get one just ping me, I use `sharplab` all the time and the least I can do for a fellow developer is to offer you a beer! 🍻

**Comment by ashmind** [comment]
Thanks for reporting and good feedback! I have some ASM improvements planned, but didn't get to them just yet.

**Comment by Sergio0694** [comment]
No problem, happy to help! Looking forward to those improvements then! 😄

**Comment by ashmind** [comment]
Sorted by migrating to Iced.

**Comment by Sergio0694** [comment]
@ashmind that's great, thank you so much! 🚀

Watch out though, the website seems to fail to load the moment, maybe something went wrong when integrating that PR with the different JIT disassembler? 🤔

![image](https://user-images.githubusercontent.com/10199417/82146693-5e954a00-984c-11ea-803f-10a08675b6e5.png)

**Comment by Sergio0694** [comment]
@ashmind FYI the new disassembler is a bit better but still has many issues 🤔

Consider [this sample](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgBgARYCMAdAEoCuAdjAJZhzECS1CNlUNAxlANwCwAKFwESFanQbMYrdlyjEAGgA4AbPwGCsAZhEqCAJjwARGlHSk4ABwQB7QQG9BeZwR1E95NjDwBRAB7SEJwwpBCUAOZwABSe1HgAbhAANuRwSHjAAJ7weLAQCDDpWTlJcBEwABYAlE4ujgIujQQA7HgAQmA0JG00MABiNHBJACb+gcFRiSlpuTD5hXil5dXqjQC+grXO2rp4sd4AynAhYZExXgnJqUXZcLPzNyVl4ZXp+3gAZkkQ4VA1DXUtk19kCmi4KjRwhUejAoHgALx4KKEch4AA8aMWz0qVTwAFo8CikKCwYsbBBhgBZaAAawReAhUJhcIx9wKxIBpJcsBsCDg1KgdMRUS+PzhADIGZDob0/ujMXkCuoSdtWh0usQAIKUYYAORsMCiSXJVNp6SmqVxGFmvP5tNWLg2nLwQJ27jwFwAKnBYAA1ODBXn6ACsKii/sDCBDKjRXgAfAkAzBef9GvUuRHkwhCPolLHqAnEsNhoR6QcoHB9Fri5Mk7ziABxY4AGRsAHdEFEqua6whG8cAKqWSydqpVZXOxpYVpFkvET02A6cZL5LsO5xOtZAA=), there are 3 different errors in the disassembly with 3 different APIs.

In particular, the original issue with the `Vector256<T>.GetUpper()` extension is still there:

```csharp
public static int TestVector256(Vector256<int> vector)
{
    Vector128<int> vadd1 = Sse2.Add(vector.GetLower(), vector.GetUpper());

    return vadd1.ToScalar();
}
```

Gives:

```asm
DisasmRepro.TestVector256(System.Runtime.Intrinsics.Vector256`1<Int32>)
    L0000: sub esp, 0x10
    L0003: vzeroupper
    L0006: vmovupd ymm0, [esp+0x14]
    L000c: invalid
    L0010: rol dword [ecx], 0xc5
    L0013: stc
    L0014: inc cl
    L0016: vmovupd [esp], xmm0
    L001b: mov eax, [esp]
    L001e: vzeroupper
    L0021: add esp, 0x10
    L0024: ret 0x20
```

Note that incorrect blob from `L000c`.
Should I report this in the `Iced` repo, or is this something on Sharplab's end? 🤔

**Comment by ashmind** [comment]
Hmm -- I didn't add the disclaimer this time, but your sample is targeted at Roslyn `master`. Roslyn branches lag a bit behind main deployment (sometimes by months tbh). Fortunately I just fixed the branch build, but the `master` branch still has SharpDisasm -- hopefully only until tomorrow.

If you try the same sample in Default you'll see no `invalid`:
https://sharplab.io/#v2:C4LghgzgtgPgAgBgARwIwDoBKBXAdsASygFN0BJfAJwNwgIGMIBuAWAChEUMd8jSLg1WgwjoAGgA4AbKzbs4AZi5SUAJiQARAhEhRMxAA6UA9uwDe7JFZRK0K7DWBIAogA9BYesExhcAc2IACgd8JAA3MAAbbGIAGiQAIwBPYGIkCGAwSmB45NSkSOJ/YAALAEpLaws2a1qUAHYkACEoAgwmgmAAMQJiSIATNw8vQIjouPTM7PjC4vLZWoBfdkqrRWUkEKcAZWJvXwDgx3ComNyUtIysnMSLgqK/UvitpAAzSLA/CAqaqtW6rb/OrWEoEPwlDrACBIAC8SECqGwSAAPMj7nMykgALRIRGxIHAgrGMD9ACykAA1rCkKDwZDoajJtd8b9CdYMsZKMRyRAqXDAu9PtCAGQ0sEQzrfFFoq7ZWQEtaNFptdAAQVw/QAcsZgIFIsSyZT4mMYpiYJNOdzKQtrMtWUh/us7EhjgAVYgZABqxC8nNUAFYpIFvb7KAGpMjHAA+cI+4Ccn61apskPxyioVQSSP4GMRfr9VDU7YQYiqNX50ZxznoADiewAMsYAO7ESiBMrGquUWt7ACqBgMrfbZXl9tqcEaeYL6Fdxm29CiWXbNqsdsWQA==

**Comment by Sergio0694** [comment]
Oh I see, thanks for clarifying. Switching to `master` or `x64` works absolutely fine like you mentioned, this is awesome! Thank you so much for your work, `sharplab.io` just got even better! 😄 🍻
