### ISSUE TITLE
Setup Instructions to run on LocalHost

### ISSUE THREAD

**Issue by AdamSpeight2008** [ashmind/SharpLab#488]
Do you have any instructions I can following to run **SharpLab.io** on a local host?

**Comment by ashmind** [comment]
Good question -- not at the moment. Theoretically `sl setup` should get you into a reasonable state, but practically I haven't checked it in a while. I'll see what I can do.

Do you want to just run it (in which case I might look at docker) or do local development?

**Comment by ashmind** [comment]
OK, now that I fixed `sl setup`, these instructions should cover it:
https://github.com/ashmind/SharpLab/blob/main/CONTRIBUTING.md#getting-started

Please let me know if you run into any issues -- otherwise I'll close this soon (we can create follow-up items or reopen later).
