### ISSUE TITLE
Decompiler unlowers hash switch statements

### ISSUE THREAD

**Issue by Suchiman** [ashmind/SharpLab#489]
The decompiler will reconstruct a hash based switch statement but shows compiler generated members like ComputeHashCode, [e.g. see this Code.](https://sharplab.io/#v2:EYLgHgbALAPgAgJgIwFgBQcDMACR2DC6A3utmbjgMoAuATgJYB2A5tgLIAUcSADNgNYBTAJ4BKUuRJpyM7AGcA7vWoBjABbYOQsRNnYpevSoCGcwdgBEAaRFILIXAHZLdgNy7DZE2cs3hCeydLAPdpT3Jvc2sRTEC4ZwtY0PCI0yi/KDiEzOSU7EjfEQBWLMsS3JSC6OEIUotaivCqv0c61sbPABNBADNjAFcAG2oQDzygiwB+Cw7yAF8PBbQ5oA)
[Sometimes it doesn't though](https://sharplab.io/#v2:EYLgHgbALAPgAgJgIwFgBQcDMACR2DC6A3utmbjnFNgLIAUcSADNgNYCmAngJSnklpyQ7AGcA7gEsALgGMAFtjocefYdgFq1MgIYj22AEQBpLkgMhswAE7ttrANyrNZHXsMnOCc5Zt3Hg53JXfWMuTG9rWwcnZ2D3LigI32iAwOw40M4AViSo/zSXXRCPCFy/GM0MjwB2MpSC7AATdgAzbQBXABspEAq0qTkrAHsxbAA7dlGAOSGpAGV2gAdFoaspdkaAUTAZdkWpCSGxum58zQBfJ0u0c6A)

**Comment by ashmind** [comment]
Thanks for reporting! I'll need to check what ILSpy options I am using and whether they have anything to force desugar this.

**Comment by ashmind** [comment]
Released (except for "Roslyn branches", that will deploy in a day or so).
