### ISSUE TITLE
Branch dropdown isn't updated

### ISSUE THREAD

**Issue by tannergooding** [ashmind/SharpLab#510]
Sharplab.io is now getting the latest builds of Roslyn 🎉, however the dropdown still shows the old branch information. For example, `master (9 Mar 2020)` indicates it is commit `441c154` which is Roslyn `v3.6.0-2`: https://github.com/dotnet/roslyn/blob/441c154b27eafc9ed04feda1786f0f07ce448f14/eng/Versions.props#L8-L10

However, if you `#error version` it outputs the actual build is `3.7.0-ci (<developer build>)`: https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAxIhB7BAAgDdEoBLPAOwFgAoIA===

This only looks to be an issue for branches that were already in the dropdown (such as `master` and `C# Next: Function pointers`). New branches, such as `features/UsedAssemblyReferences`, show the current latest date.

**Comment by ashmind** [comment]
Interesting, thanks for reporting! There is a bit of CDN cache, but that would not explain why you are seeing new branches properly... I'll take a look in the future.

**Comment by tannergooding** [comment]
Looks to have updated to `master (16 May 2020)` and similar for other branches now. There may still be an issue here but it is less obvious if that is the case since there isn't a way to get the SHA from the compiler build being used.

**Comment by ashmind** [comment]
I've monitored it for a few days and it seems to be consistently up to date now, so I expect it's just a caching issue. There still might be discrepancies in the future, but should not be by more than 24 hours.
