### ISSUE TITLE
How to use Decompile for top-level programs?

### ISSUE THREAD

**Issue by rstm-sf** [ashmind/SharpLab#519]
Hello!

How to use Decompile for top-level programs? Now only Run and Syntax Tree are [working](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGUCWBbADgGwgAUEB7AcwSm2QBoYQE4A7WgExAGoAfAAQEYAdAICcACgBEACQCSAQgkBKANxA===). For other options, reports the following: `error CS9004: Program using top-level statements must be an executable.`

**Comment by ashmind** [comment]
Thanks for reporting! That makes sense, I'll need to adjust the compile target.
I'll take a look, but might take some time.

**Comment by ashmind** [comment]
This should now be resolved: SharpLab will detect if there are any top-level statements and compile them in exe mode.
