### ISSUE TITLE
Desugar lock

### ISSUE THREAD

**Issue by Suchiman** [ashmind/SharpLab#521]
I'm not sure if this has ever worked before but `lock` is syntactic sugar over `Monitor`:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKFygZgAJ0iBhXAb1yNpOJQBYiBZACgHtgArOAYxhEOAShp1qOOlKIAbDnwDWRTqMnTaE9epQYAnGwBEATzgQAFkWARgRoifMHhAbjHqAvq6IecboA

**Comment by ashmind** [comment]
Thanks for reporting -- this certainly makes sense. Not sure if ILSpy already supports it, but I'll take a look.

**Comment by ashmind** [comment]
This is now released in Default branch:
https://sharplab.io/#v2:D4AQTAjAsAULIGYAE4kGFYG9ZNy5IALEgLIAUA9gEYBWApgMYAuSFAlDntjHr0gDYUGAaySUOPPrm5SpICAE4yAIgCedAIYALJFQ1VVSdduVsA3JykBfS0hswrQA

Your original link to `master` is not yet updated -- if all goes well `master` will auto-deploy that change in 5 hours.
