### ISSUE TITLE
sharlab.io is down

### ISSUE THREAD

**Issue by paulomorgado** [ashmind/SharpLab#525]
> HTTP Error 500.32 - ANCM Failed to Load dll
> Common solutions to this issue:
> The application was likely published for a different bitness than w3wp.exe/iisexpress.exe is running as.
> Troubleshooting steps:
> Check the system event log for error messages
> Enable logging the application process' stdout messages
> Attach a debugger to the application process and inspect
> For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028526

**Comment by ashmind** [comment]
Thanks for reporting -- I'll update my uptime monitor to more aggressive notifications.
Restart seems to have fixed it.
