### ISSUE TITLE
Debug/Release selector stopped working?

### ISSUE THREAD

**Issue by canton7** [ashmind/SharpLab#526]
It seems the Debug/Release selector stopped working?

If you toggle it, nothing in the right-hand pane reloads (with the IL and JIT views, you'd normally expect to see some difference). It also doesn't change the URL. If you refresh the page, it reverts to Release.

Tested in FF 76.0.1 and Chrome 83.

**Comment by ashmind** [comment]
Thanks for reporting! This should be fixed now (might need to clear cache if it does not work at first).

**Comment by canton7** [comment]
Confirmed, thanks for the quick fix!
