### ISSUE TITLE
Switching from decompile to run and back leaves the program as an executable

### ISSUE THREAD

**Issue by 333fred** [ashmind/SharpLab#530]
Repro steps:

1. Open https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABAjAOjwE4AKAIgAk4AbagewAIB3OhalAQjIEoBuIA=. This is just `System.Console.WriteLine("Hello World!");` on the top level as a demonstration. Compilation will fail with `error CS8805: Program using top-level statements must be an executable.`
2. Switch to `Run`. The program will run.
3. Switch back to `C#`. The program now shows the decompiled source.

I'm not sure of the reasoning here: is it because the compilation result is cached, so the already-produced dll is just shown? It would be neat if sharplab was able to detect that a top-level statement was being used and automatically switch to compiling an executable, or otherwise exposed that as an option.

**Comment by ashmind** [comment]
Hmm, this is interesting and shouldn't really behave like this -- it already has auto-detection, but somehow the detection does not work for the first open. E.g. if you add a space without switching mode, it works.

I'll take a look (no timeline promises though).

**Comment by ashmind** [comment]
Ah OK, this is why, the error code in master is different so error suppression after switching the build mode does not work:
https://github.com/dotnet/roslyn/commit/b6091e22447af6f9ef554f50450405b415b85de0#diff-152582e34df01d1d13dba934c25d0858L1924-R1925

**Comment by ashmind** [comment]
OK this should be sorted now.
