### ISSUE TITLE
Sharplab.io cert expired today

### ISSUE THREAD

**Issue by Izumemori** [ashmind/SharpLab#533]
<img src="https://i.izumemori.dev/4jdcabe.png">

> Websites prove their identity via certificates, which are valid for a set time period.
> The certificate for sharplab.io expired on 6/17/2020.

**Comment by Suchiman** [comment]
![](https://media1.tenor.com/images/a793b0e07f5860b304ccc7e3a9a10b1b/tenor.gif?itemid=13729593)

**Comment by ashmind** [comment]
Thanks for reporting! Hopefully resolved now.
