### ISSUE TITLE
Array.Reverse not allowed

### ISSUE THREAD

**Issue by DigitalAutomationDeveloper** [ashmind/SharpLab#535]
```
int[] arr = new int[] { 1,2,3,4 };
Array.Reverse(arr);
```
This gives an error: **Unbreakable.AssemblyGuardException: Member System.Array.Reverse is not allowed.**

**Comment by ashmind** [comment]
Thanks for reporting! Yep I will allow it (but no specific timeline promises, depends on when I get to it).

**Comment by ashmind** [comment]
Done (might take until tomorrow to deploy if you are using Roslyn branches).
