### ISSUE TITLE
Syntax tree for F# seems to have stopped working

### ISSUE THREAD

**Issue by 7sharp9** [ashmind/SharpLab#537]

**Comment by 7sharp9** [comment]
Given:
```FSharp
open System
type Person = {
    Name: string
    DateOfBirth: DateTime
}

let inline _name f { Name = a; DateOfBirth = b } = (^``Functor<'T>`` : (static member Map : _ * _ -> _) (f a: '``Functor<'T>``), (fun a' -> { Name = a'; DateOfBirth = b }))
```

There is no output shown on the right.

**Comment by ashmind** [comment]
Thanks for reporting! I'll take a look.

**Comment by ashmind** [comment]
Hmm, I can't reproduce this. What browser are you using? Any errors in browser console?

**Comment by 7sharp9** [comment]
Hmm, just checked and I got the AST output, so I guess I was just a bad day :-)

Is there anyway you could add the ray art output test rather than the simplified tree view as there is details in the raw test that's quite useful for meta programming where you are building an AST.

**Comment by ashmind** [comment]
Sure — I can take a look at adding that (no time promises).  Can you create a separate issue for it and give examples on details you want to see?
