### ISSUE TITLE
For C# 9 (master etc) Appears to be missing System.Runtime.CompilerServices.IsExternalInit

### ISSUE THREAD

**Issue by jbtule** [ashmind/SharpLab#543]
https://sharplab.io/#gist:5e4b99a37f98fd0588544f4aa7caaf6f

Using the record syntax, get error

> error CS0518: Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported

probably issue with any c# 9 feature based on init only properties.

**Comment by ashmind** [comment]
Thanks for reporting! I'll take a look in the future, however in the meantime you can do this:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoEgNwgQAIAzAezqoF4qA7OAdyoAVEo7WACgBEAKTpxhSKrgAMASgDc5SlWCqW9RhwCWMABZUA3gEEA5nGa0GAOnOX0VfFQC+y0sQRwAxnQQoePgEqQWx8WSoAOQgwOGkdVhgqeyUSElYYuCgABwhvSzCbACUAV0SdWJsAYTowbJ0AG0QAZUQyHXyoYxIqXqpsAGZ+3CoASSgAUQAPeAQMhtHWPWMXEhcgA===

**Comment by RikkiGibson** [comment]
First let me say: thank you for creating and maintaining this awesome tool. It would be really nice to get this fixed, perhaps by adopting .NET 5. I have been copy/pasting the IsExternalInit type definition a whole lot into SharpLab windows :smile:

**Comment by ericsampson** [comment]
It would definitely be nice to get this fixed now that .NET 5 is out, as I started playing around with some C#9 features in sharplab yesterday and had to paste the IsExternalInit type in as well, which many people won't know to do.
Where would the change need to be made to support this?

**Comment by ashmind** [comment]
Completely agree -- there is a PR for it at #577, and I aim to look at outstanding issues soon-ish, including this one.

**Comment by ericsampson** [comment]
Thanks! I'm not familiar with this codebase, or I'd have given it a shot :)
Thanks again for this tool, it's so useful.

**Comment by ashmind** [comment]
This is now resolved using @teo-tsirpanis work in #577.

**Comment by ericsampson** [comment]
Thanks @ashmind amd @teo-tsirpanis !! 👍
