### ISSUE TITLE
Disassembly Visual Bug -- "vmovdqu [rdx], xmm0" vs "vmovdqu rdx, xmm0"

### ISSUE THREAD

**Issue by hopperpl** [ashmind/SharpLab#549]
I'm not sure if this is the right place,as I don't know who (project) generates the asm disassembly.

The JIT code is working fine. It's just a wrong visual print of the asm instruction below.

**L0022: vmovdqu [rdx], xmm0      <--- this should be: vmovdqu rdx, xmm0**

---

Code:

    using SharpLab.Runtime;
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.CompilerServices;

    public unsafe class C {

        private readonly byte* m_Pointer;
        private readonly uint m_Length;
        public uint Position;

        [DoesNotReturn]
        private static void ThrowReadError() => throw new ArgumentException(nameof(Position));

        [JitGeneric(typeof(Guid))]
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public T GetStruct<T>() where T : unmanaged
        {
            uint P = Position, S = (uint) Unsafe.SizeOf<T>(), Q = P + S;

            if (Q > m_Length)
              ThrowReadError();

            Position = Q;
            return Unsafe.Read<T>(m_Pointer + P);
        }
    }

Assembler:

        ; Core CLR v4.700.20.26901 on amd64

          ....

        C.GetStruct[[System.Guid, System.Private.CoreLib]]()
            L0000: sub rsp, 0x28
            L0004: vzeroupper
            L0007: mov eax, [rcx+0x14]
            L000a: lea r8d, [rax+0x10]
            L000e: cmp r8d, [rcx+0x10]
            L0012: ja short L002e
            L0014: mov [rcx+0x14], r8d
            L0018: mov eax, eax
            L001a: add rax, [rcx+8]
            L001e: vmovdqu xmm0, [rax]
            L0022: vmovdqu [rdx], xmm0      <--- this should be: vmovdqu rdx, xmm0
            L0026: mov rax, rdx
            L0029: add rsp, 0x28
            L002d: ret
            L002e: call C.ThrowReadError()
            L0033: int3

Config:

        {
            "version": 1,
            "target": "JIT ASM",
            "mode": "Release",
            "branch": "core-x64"
        }

**Comment by ashmind** [comment]
Thanks for reporting! I am using https://github.com/0xd4d/iced for disassembly btw.

**Comment by hopperpl** [comment]
Sorry, I take it back.

After more investigation, this code is correct. The code optimizer is pretty impressive now, and the struct is put on the stack, as parameter rdx. So, writing to [rdx] and then return rdx is correct.
