### ISSUE TITLE
Roslyn updates have stalled out since 25th July 2020

### ISSUE THREAD

**Issue by RikkiGibson** [ashmind/SharpLab#551]
I noticed that the master branch on sharplab.io still has a build from the 25th of July. It would be really handy if we could get this up to date. Please let me know if I can assist in any way.

**Comment by ashmind** [comment]
Thanks for reporting! I'll take a look today.
Btw you can see those builds at https://github.com/ashmind/SharpLab/actions?query=workflow%3Aroslyn-branches.
