### ISSUE TITLE
Highlight implements Keyword in IL

### ISSUE THREAD

**Issue by dogac00** [ashmind/SharpLab#552]
Hello,

The "implements" keyword is not highlighted in generated IL. Can you refer to me the source code where syntax highlighting occurs? Maybe I can be of some help.

Thank you.

**Comment by ashmind** [comment]
Thanks for reporting! Highlighting code is here:
https://github.com/ashmind/SharpLab/blob/main/source/WebApp/components/internal/codemirror/mode-cil.ts

**Comment by ashmind** [comment]
Resolved by #554 (thanks!)
