### ISSUE TITLE
New decompiler option: UseRefLocalsForAccurateOrderOfEvaluation

### ISSUE THREAD

**Issue by dgrunwald** [ashmind/SharpLab#563]
On https://github.com/icsharpcode/ILSpy/issues/2115 I just introduced this new option.
It's disabled by default for languages <=C# 5 (which don't have `ref locals`), which means the decompiler will sometimes generate slightly inaccurate code in order to avoid ref locals.

This affects code such as:
```c#
ref int elem = ref GetArray<int>()[GetIndex()];
elem = GetValue<int>();
```
when decompiled with `UseRefLocalsForAccurateOrderOfEvaluation=false`, the decompiler will produce:
```
GetArray<int>()[GetIndex()] = GetValue<int>();
```
which has different semantics: with the ref-local any NullReferenceException or IndexOutOfBoundsException happens before `GetValue` is called; but without it the exception only happens after the `GetValue` call.

So after the next ILSpy release, SharpLab should probably enable this option to accurately represent what's happening in the IL.

**Comment by dgrunwald** [comment]
There's also a few more C# 1 options for syntax sugar that you'll want to disable:
* [ForEachStatement](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCWAdgC4DaAuugIYBOXAlAUmJD0AMwD2XAKYcAxgAt0dJulor6nHvwC+hYjqRagA=)
* [SparseIntegerSwitch](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7ICQhamcAbGQAzoDKADgIYBOAzgKYCSAdgC7sBzds1oB3AJa8AxgAsAFOL7pxASiKECSYiTgBOOQCIGLDj35CRE6TJDoD6MMpUBudYVZXZ6BWq3FN2oRSjBzoALRwVFHRVCBuxFAA7HYRNAC2ADbcBq5+xMGhqbHxJMkGYTIArtzAzOzAOfEF7OFwcXkJZRGNHc3oxR2ldlQ9gX1tJUl2cKPafTDtgUMGMLP5IS0ALIuBUwaba0Eb6JEDS3tVNXUNuWPHp1E72nv83Oi8MgD2layMNYfjaITQYvdhvD7fX41dB/YDoT7cdgA46KXgAOgAsowAB4ANUYGUq7CenTsqMxOPxhKRt20wHYADNGJUMrwSctWJ80uwPooBOh2BkOGsAL7qMVIEVAA===)
* ForStatement
* DoWhileStatement

And on the other end of the spectrum, C# 9 InitAccessors and FunctionPointers should probably be enabled as they aren't mere syntax sugar.

Whether to enable `NativeIntegers` is a tricky question, there's some syntax sugar involved with the attribute; but the arithmetic with `nint` is a lot cleaner (and closer to the IL) than the hacks the decompiler uses to do arithmetic with `IntPtr`.

**Comment by ashmind** [comment]
Thanks! This kind of information is extremely useful as I easily overlook those edge cases.
I'll revisit this when next ICSharpCode.Decompiler is released and probably apply all at once.

**Comment by ashmind** [comment]
Thanks again, applied new settings to the site after the update.

> Whether to enable NativeIntegers is a tricky question, there's some syntax sugar involved with the attribute

I wonder if it means there is a benefit in having a separate setting for attribute vs arithmetic.
