### ISSUE TITLE
Allow BitOperations

### ISSUE THREAD

**Issue by YohDeadfall** [ashmind/SharpLab#564]
The `BitOperations` class has no dangerous methods and useful for bit operations on numerics. Under the hood it has software implementation if a hardware version isn't available. Therefore, it can be allowed in SharpLab or Unbreakable.

I would like to take the issue if it's okay, but first I should know in which project do that.

**Comment by ashmind** [comment]
Thanks for raising! Given it's completely risk-free I think Unbreakable.
