### ISSUE TITLE
Allow ArrayPool

### ISSUE THREAD

**Issue by YohDeadfall** [ashmind/SharpLab#565]
`ArrayPool` is another safe API which isn't available in SharpLab. Open PR in Unbreakable, right?

**Comment by ashmind** [comment]
Yep, I think I am going to simplify the rules, and put everything except e.g. reflection into Unbreakable by default.

However as a policy `ArrayPool` is a bit complicated:

1. `Shared` must not be allowed (shared state)
2. `Rent()` must use `CountArgumentRewriter("minimumLength")`
3. `Create()` needs a custom rewriter that can counts its allocations correctly.
This is the most complicated it as total allocations seem to be `maxArraysPerBucket * Utilities.SelectBucketIndex(maxArrayLength)`. I am not sure what's the best approach here (repeating the internal algorithm is also not great as it can change).

Probably some kind of pessimistic estimate.

**Comment by YohDeadfall** [comment]
> Yep, I think I am going to simplify the rules, and put everything except e.g. reflection into Unbreakable by default.

Not only reflection, but also any unsafe code including some methods from `Unsafe` and friends.

**Comment by ashmind** [comment]
Hi @YohDeadfall, SharpLab Run model has changed and should now allow `ArrayPool` without issues.
