### ISSUE TITLE
Weird branching logic

### ISSUE THREAD

**Issue by CollinAlpert** [ashmind/SharpLab#569]
I stumbled upon this behavior by accident. When I declare a bool as false and then use it in an if-branch, the condition gets evaluated as 0 == 0, which is obviously true. However, if I don't leave the branch empty, everything looks like I'd expect. Is this behavior intended? If so, why?

![image](https://user-images.githubusercontent.com/14217185/95344776-4b961b80-08ba-11eb-90a2-728aca42f497.jpeg)

**Comment by ashmind** [comment]
Looks like a decompiler bug -- I'll take a look when I have a moment.

**Comment by ashmind** [comment]
I updated to the latest IlSpy, but seems like it is present there as well.
It does look like a bug to me, so I recommend raising it in https://github.com/icsharpcode/ILSpy/issues.

**Comment by CollinAlpert** [comment]
I have raised it [here](https://github.com/icsharpcode/ILSpy/issues/2262).
