### ISSUE TITLE
Multidimensional arrays do not pass Unbreakable.

### ISSUE THREAD

**Issue by teo-tsirpanis** [ashmind/SharpLab#570]
Example:

``` csharp
public static class Program {
    public static void Main() {
        var xs = new int[5,9];
    }
}
```

**Comment by ashmind** [comment]
Thanks for reporting! This is also tracked by #351, so I'll close this one.
I remember trying to support them a while ago and running into some issue with my architecture in Unbreakable, but I will definitely take another look at some point.
