### ISSUE TITLE
csharp syntax highlighting broken inside of interpolated strings

### ISSUE THREAD

**Issue by binki** [ashmind/SharpLab#571]
```csharp
using System;
using System.Collections.Generic;
public static class Program {
    public static void Main() {
        Console.WriteLine("normal string");
        Console.WriteLine($"x={new HashSet<string>{{"a"},}.Contains(null)}");
    }
}
```
https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMAWAbjwwGYiBvPI5k9dBplr0gTgAoARFAD2YALYBDADYlMBAQEoquLt0z8AJAIAeAXnpQApgHciACQkBnABYBlQ8AA8pAgD569ARIEBfGD4A6AGFhKGAJAEsoSz4oCCkpBR9FZS4fPB8gA==

I expect at least the `"a"` to be highlighted in the same way that `"normal string"` is, but it isn’t. Also, the subexpression between `{` and `}` is highlighted like a string instead of like normal code.

I am only looking at the symptoms, but it seems like you might be using a syntax highlighting library (CodeMirror?) which doesn’t understand C#. It might be better to use Roslyn’s AST instead if possible. Or switch to whatever GitHub is doing because it seems to be doing better ;-) (the editor preview I see is below).

![GitHub C# syntax highlighting in editor preview tab](https://user-images.githubusercontent.com/82626/95766878-ec515600-0c81-11eb-9ead-42f9d40013a9.png)

**Comment by ashmind** [comment]
Thanks for reporting! It is something I aim to fix in next editor version, but it is taking a while due to CodeMirror changes.
This issue is also tracked by #325, so I'll close this one to deduplicate.
