### ISSUE TITLE
Every edit causes a new page to be saved in browser history

### ISSUE THREAD

**Issue by Therzok** [ashmind/SharpLab#573]
Title is pretty much it. This is on Google Chrome/macOS if it makes any difference.

Every edit will cause a new entry to be saved in the browser history, and you can end up with hundreds of history items on sharplab.io. It seems like every edit generates a new page based on the checksum.

**Comment by ashmind** [comment]
Thanks for reporting! I am not a fan of this experience, but I could not resolve it before (in #321).
I'll close this one to deduplicate, and we can discuss further in #321.

@jsk95 Maybe your extension can help here?
