### ISSUE TITLE
Positional records are not yet supported

### ISSUE THREAD

**Issue by BillWagner** [ashmind/SharpLab#575]
See https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobAZgAIE4BjAewRQoAVEo6A7ACm3wAYKAMQCWCWADkIYOEgq8BAGWgxJ0gJQBuIA=

This record type should be valid with C# 9:

```csharp
using System;
public record Person(string FirstName, string LastName);
```

The output indicates that the required attribute for a positional record parameter is missing:

```
error CS0518: Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported
error CS0518: Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported
```

**Comment by lomholdt** [comment]
I see the same problem. Saw someone on StackOverflow who just [implemented the missing type](https://stackoverflow.com/a/62656145) and then [it works in SharpLab as well](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobAZgAIE4BjAewRQoAVEo6A7ACm3wAYKAMQCWCWADkIYOEgq8BAGWgxJ0gJQBuEiQ5S4UAA4QacOfgB0AJQCuHGMOnmAwnTAHhAG0QBlRADdhEygSAG8SCgi5SjwKAEkoAFEAD3gEXQ9YjmEYEIBfElygA===).
I am not sure what would be needed to actually fix the problem though.

**Comment by lomholdt** [comment]
Also this seems to be a duplicate of #543 :)

**Comment by BillWagner** [comment]
> Also this seems to be a duplicate of #543 :)

Yes, thanks @lomholdt I searched for "positional record" not `IsExternalInit`. Closing as duplicate. Leaving comments to help others find the issue and workaround in #543
