### ISSUE TITLE
Unbreakable: unblock Dictionary<TKey, TValue>.Keys and .Values and `KeyValuePair<TKey, TValue>`

### ISSUE THREAD

**Issue by canton7** [ashmind/SharpLab#578]
Trying to iterate `Dictionary<TKey, TValue>.Keys` and `.Values` gives:

```
Unbreakable.AssemblyGuardException: Type System.Collections.Generic.Dictionary`2/KeyCollection/Enumerator is not allowed.
Unbreakable.AssemblyGuardException: Type System.Collections.Generic.Dictionary`2/ValueCollection/Enumerator is not allowed.
```

Please consider allowing these two types.

Repro:

```cs
var dict = new Dictionary<String, String>();
foreach (var key in dict.Keys)
{
}
foreach (var key in dict.Values)
{
}
```

[Link](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABAJgEYBYAKGIAYACY8gFgG4abMIw4oAHCAGM4DAMIB7TFAkAbOAEF+/KtQDeNBlqakAzJu0bq2k011NyANiYsGAWQgBLTAApmdANoBdBhAQBzKABKA1MGIzCwgDc/BhxHIRgGAF4GTDgAdwYAEQSYRyk/AE8AHgBlGARnfyQGCqrMfwA+FyCOY0iTADMJBDhhAAsGFxiEBgBrOCKGZzi8gDoAaSng0M7wtc6AX03Inr7B4dGJqZnMOcT5gDUIWXQ+EI71jaf1ndeTd8+aLaA==)

----------

`KeyValuePair<TKey, TValue>` is also not allowed:

```cs
var kvp = KeyValuePair.Create(1, 2);
```

[Link](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEAMABLgIwAsA3ALABQuATAMyEDethHx99r7n/ANwgJCAawEAHQgF5CAaTgBPAGoQANujgAFCAEsEAOgDCCOBHgAKEkkL0AlNRr8AvrWdA===)

**Comment by ashmind** [comment]
Thanks for reporting! That does make sense, I'll take a look when I have a moment.

**Comment by ashmind** [comment]
This is now resolved in "Default". It will be eventually resolved in `master` (when that builds), so I'll close it now.
