### ISSUE TITLE
Update the default platforms to .NET 5 and C# 9

### ISSUE THREAD

**Issue by jnm2** [ashmind/SharpLab#579]
If you select "Default" or "x64," you should be able to use C# 9 features and the new types in .NET 5 that they require, such as IsExternalInit. .NET 5 was shipped on Nov 10.

**Comment by teo-tsirpanis** [comment]
Tracked by #577.

**Comment by ashmind** [comment]
This is now resolved using @teo-tsirpanis work in #577.
Actually x64 might not have deployed fully, but let's see -- can always create new ticket for x64 if it does not deploy after next few changes.
