### ISSUE TITLE
Environment.StackTrace doesn't work in Run mode

### ISSUE THREAD

**Issue by Kinrany** [ashmind/SharpLab#581]
I was trying to compare recursion in C# and F#, so I tried to use `Environment.StackTrace` to examine the current stack. Turns out this throws an exception. Funnily enough, the exception does include stack trace 🙂

**Comment by ashmind** [comment]
I was going to say it's a security concern, but then 🤔 you are right about the exceptions -- so it's not really.
Yep I'll allow it (when I have time).

**Comment by ashmind** [comment]
Hi @Kinrany, this is now allowed (by moving to a new Run mode, which does not block individual properties anymore).

**Comment by Kinrany** [comment]
Thank you!
