### ISSUE TITLE
Unbreakable: Detect C# compiler bomb

### ISSUE THREAD

**Issue by znakeeye** [ashmind/SharpLab#584]
The code below will likely crash your server. You should try to catch this dangerous construct early in the compilation step! Well, actually before compilation occurs 😃 

```c#
public class X<A,B,C,D,E>{class Y:X<Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y>{Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y y;}}
```

See more details [here](https://codegolf.stackexchange.com/a/69200/83543).

**Comment by ashmind** [comment]
Thanks for reporting! That's unfortunate, I'll have to investigate.

**Comment by ashmind** [comment]
This is now resolved (hopefully).
