### ISSUE TITLE
x64 profile not working

### ISSUE THREAD

**Issue by nathan-alden-sr** [ashmind/SharpLab#587]
It seems that on the live website, the x64 profile is not working properly.

![image](https://user-images.githubusercontent.com/1189759/102780937-cd97cb80-4364-11eb-9cee-82c135bbe9f1.png)

I can change to other profiles like Default and such, but this is the only profile that shows the `[connection lost, reconnecting...]` message.

I'm seeing this in the console:

> Firefox can’t establish a connection to the server at wss://sl-a-core-x64.azurewebsites.net/mirrorsharp.

Browser shows this for the `https` version:

![image](https://user-images.githubusercontent.com/1189759/102781684-14d28c00-4366-11eb-9c53-d1c70a9c5dbc.png)

**Comment by ashmind** [comment]
Great catch! Fixed.
