### ISSUE TITLE
MemoryGuardException when GetBytes() parameter string longer than 42 characters 

### ISSUE THREAD

**Issue by demoded** [ashmind/SharpLab#598]
Don't know may be this is a deliberate limitation, but getting next exception with simple code:
```csharp
Console.WriteLine(Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes("1234567890123456789012345678901234567890123")));
```

```
Unbreakable.Runtime.MemoryGuardException: Total allocation limit reached (collections and strings).
   at Unbreakable.Runtime.Internal.RuntimeGuard.EnsureCount(Int64 count)
   at Unbreakable.Runtime.Internal.RuntimeGuard.GuardCount(Int64 count)
   at Unbreakable.Runtime.Internal.RuntimeGuard.FlowThrough.GuardCountIntPtr(IntPtr count, RuntimeGuard guard)
   at <Program>$.<Main>$(String[] args)
```

**Comment by ashmind** [comment]
This is a bit tricky -- it's a combination of
* `"1234567890123456789012345678901234567890123"` -- 43 chars
* `System.Text.Encoding.UTF8.GetBytes(...)` -- 43 bytes
* `Convert.ToBase64String(...)` -- 60 chars

I do agree that in this specific case it is too restrictive, but adjusting it will require some consideration.
I'll look into it when I have a moment.

**Comment by ashmind** [comment]
Hi @demoded, this is now resolved, and memory restrictions in new Run mode are not as restrictive overall.
