### ISSUE TITLE
Invasive webapp

### ISSUE THREAD

**Issue by Carpall** [ashmind/SharpLab#599]
While I wite something in the editor the url of the website continues to get updated, and this destroys my history
![image](https://user-images.githubusercontent.com/65513900/111904608-0fa9d980-8a48-11eb-81c0-1c4e7a3ef4f5.png)
please fix it placing a buton here
![image](https://user-images.githubusercontent.com/65513900/111904638-30722f00-8a48-11eb-8ab1-d6407e7ba56b.png)
for link generation

**Comment by ashmind** [comment]
Thanks for reporting! This is the same as #321 -- though the suggestion for an explicit button is fair enough.
I might look into optionally disabling it as you suggested, but that would be within #321, so I'll close this one.
