### ISSUE TITLE
Why is System.Console.WriteLine not allowed to be used as a delegate?

### ISSUE THREAD

**Issue by xparadoxical** [ashmind/SharpLab#601]
Just a question, but why is System.Console.WriteLine not allowed to be used as a delegate? You can circumvent this very easily by calling it in a delegate, but it's annoying.

**Comment by ashmind** [comment]
Thanks for reporting! This is certainly a bug -- I'll take a look when I have a moment.

**Comment by ashmind** [comment]
This is now resolved.
