### ISSUE TITLE
how to define enum type

### ISSUE THREAD

**Issue by drearyrainDeng** [ashmind/SharpLab#605]
i try to add code like this.but error 
‘enum emSendRecvResult : byte
{
    Success = 0,
    ConnectFail,
    SendFail,
    RecvFail,
    RecvTimeout,
    NoSession
};’
![20210402092209](https://user-images.githubusercontent.com/35326823/113369889-0ba98000-9395-11eb-8e48-0ff275f21556.jpg)

**Comment by ashmind** [comment]
Thanks for asking! This is a general C# error, and not a SharpLab one.
The error reported should provide additional information -- the enum should be placed _after_ Console call.

**Comment by drearyrainDeng** [comment]
thanks, got it,  but it is confuse for me before! why define customous type should after Console call(it guess default domain is function Main until new type be defined, i dont know it from any guide  )
