### ISSUE TITLE
https://sharplab.io/ - seems to be down - it is not working "connection lost"

### ISSUE THREAD

**Issue by bernd5** [ashmind/SharpLab#614]
I'm not sure where to open an issue - but I like SharpLab very much and it is now already some time down / not working:
![grafik](https://user-images.githubusercontent.com/26689688/121740189-08e9aa80-cafd-11eb-8d78-e0db49053aac.png)

It would be great if it could be fixed soon.

Thanks

**Comment by RikkiGibson** [comment]
I noticed that the "Default" compiler seems to be working: https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyDMABGgQMIEDeOB1RhyALAQLIAUAlBVTQL47dA===
But not the "main" one: https://sharplab.io/#v2:EYLgtghglgdgNAFxFANnAJiA1AHwAIBMAjALABQeAzAASHUDC1A3udW7TXgCzUCyAFAEpmrdgF9yYoA=

**Comment by ashmind** [comment]
Thanks for reporting! I think this might be resolved now -- I'll keep open for a bit to monitor.

**Comment by TomasMalecek** [comment]
I see the same issue now. It has been like that for almost 24 hours. Again, `main` does not work and `Default` does.

What version is the `Default` one, anyway?

**Comment by ashmind** [comment]
@TomasMalecek Thanks for reporting -- that one is separate (new) problem, I will take a look soon (though might be worth a new ticket so it does not get forgotten). Default is a relatively outdated NuGet version (no self-update), you can see specific version by doing `#error version`.

**Comment by ashmind** [comment]
This is now resolved. I'll lock this one so that new issues can be created separately.
