### ISSUE TITLE
Adding a couple of branches/tags

### ISSUE THREAD

**Issue by jcouv** [ashmind/SharpLab#72]
Thanks a lot for TryRoslyn. Many folks on the Roslyn team use it frequently to test out code quickly on different versions.

Now that VS2017 has shipped, the master branch has the common fixes for dev15.3, while feature branches have features that will eventually be merged.
But I was wondering if it might be possible to add a couple of entries to the drop-down:
- one for dev15.0 (tag `Visual-Studio-2017`)
- one for VS2017 update 3 (tag `Visual-Studio-2015-Update-3`)

Cheers,
Julien

PS: the contact page on your blog seems broken. I received a mail delivery failure message.

**Comment by ashmind** [comment]
@jcouv Sure -- long term I want to avoid specific versions, but I don't mind to have them while useful.
Can you add them into https://github.com/ashmind/TryRoslyn/blob/master/Build.config.json and make a PR? If not I'll take a look at adding them over the weekend.

The build runs once a day, so after they are added it will take a day for them to appear (if built successfully).

**Comment by ashmind** [comment]
@jcouv And thanks for reporting the blog issue -- I'll take a look, but for now if you want to send an email please use ashmind/at/gmail/dot/com.

**Comment by jcouv** [comment]
Sure.
Can you clarify why you'd rather avoid specific versions?

**Comment by ashmind** [comment]
Sure. Each version I support adds two overheads:
# The build and publish is not currently parallelized, so each version makes it slower. Normally it's fine, but if I am fixing an issue it becomes hard to push fix into all branches promptly.
# Each branch creates a new Azure web app, but there is no auto-delete, so it sits there until I remove it.

Given this, I wanted to focus on most interesting branches -- preferably ones that get fresh changes worth following. Feature branches are good for this -- they'll have some new and shiny features, and once they are merged they will stop affecting build.

Specific versions tend to sit around for longer, and it's hard for me to judge when they become irrelevant and ready to be deleted.

**Comment by ashmind** [comment]
@jcouv After starting on this, I realized I misread the ticket and those are tags not branches. Unfortunately the build does not support tags at all at the moment, and I likely wouldn't have time to add them in the near future.

I can accept tag support as a PR though.

**Comment by ashmind** [comment]
Given the requested tags are likely obsolete, I'll close this one.
Please let me know if they are still needed.
