### ISSUE TITLE
main branch does not seem to be working

### ISSUE THREAD

**Issue by 333fred** [ashmind/SharpLab#728]
For example, https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTCDMACZPAYUwG9M9KD8EAWPAWQAoBKCq8jK7vANwgBOeAC4BTAM7CUeALx4AJACIAKhOF4AZgHstsvKQBiOgHQBBAL7HFAbnaVzmB1gyiYAVzB4jWspgCQpnoADI6YmEA===

This just hangs, eventually getting a "connection lost, reconnecting" message in the status bar. Other branches appear to be ok, but not main.

**Comment by 333fred** [comment]
```
connection.js:35 WebSocket connection to 'wss://sl-b-dotnet-main.azurewebsites.net/mirrorsharp' failed: 
Et.<computed> @ connection.js:35
Et @ connection.js:102
en @ mirrorsharp.js:6
mounted @ app-code-edit-stable.ts:47
```

This eventually pops up in developer tools.

**Comment by ashmind** [comment]
Thanks for reporting! Seem like overnight branch update got stuck somehow.
I'll rerun, and close this if resolved -- but that's not a full guarantee, the overnight build is not 100% stable overall.

I hope to take a look at resolving its problems sometime when I have a moment.

**Comment by ashmind** [comment]
For now `main` is back online, so I'll close this one, but I'll keep future stability in mind.
