### ISSUE TITLE
Can't run F# code in Default mode

### ISSUE THREAD

**Issue by svick** [ashmind/SharpLab#735]
When I attempt to Run F# code in Default mode, I keep getting:

> Warning: Could not find any code to run (either a Main method or any top level code).

[This happens for top-level code, e.g.:](https://sharplab.io/#v2:DYLgZgzgNALiBOBXAdgHwA7wJbJmZABAESA8G4CD7RQA)

```f#
printfn "🌄"
```

[It also happens with explicit `EntryPoint`:](https://sharplab.io/#v2:DYLgZgzgNALiBOBXAdgHwNoB4CiybwE8AFAewEs8A+AXQFgAoYAUxgAIBbAQwtc/gHMIrALwNW41gAd4FGGGSsARIB4NwCD7isRIAMDIA===)

```f#
[<EntryPoint>]
let main args =
    printfn "🌄"
    0
```

If I switch to .NET Framework, both approaches start working.

**Comment by ashmind** [comment]
Thanks for reporting -- good catch. I'll take a look.

**Comment by ashmind** [comment]
This is now resolved.
