### ISSUE TITLE
Empty lines do not appear in the Results pane

### ISSUE THREAD

**Issue by wqnvlz** [ashmind/SharpLab#751]
Running the following code ([SharpLab link](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIEYB0GCcAKAIgDMB7EggSgG4BYAKA23X2vsd0ICMBDMSqoA=)):

```cs
System.Console.WriteLine("foo");
System.Console.WriteLine();
System.Console.WriteLine("bar");
```

should result in:

```
foo

bar
```

but the Results pane shows:

```
foo
bar
```

It seems this is caused by each line being placed in a separate `<pre>` tag in the output `<div>`; the empty lines result in empty tags that have no effect.

I also noticed that this sometimes doesn't occur when a run completes with "Legacy execution limits apply (due to a container run failure)." When that happens, all of the output appears inside a single `<pre>` tag.

**Comment by ashmind** [comment]
Thanks for reporting this! Makes sense that the fallback works correctly, but I'll need to fix the new one.

**Comment by ashmind** [comment]
This one is resolved as well.
