### ISSUE TITLE
{"flow":[...]} is appended when output does not have trailing newline

### ISSUE THREAD

**Issue by wqnvlz** [ashmind/SharpLab#753]
Run the following code ([Sharplab link](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAIEYB0BhA9lAZ1wBsBTTAdTAEthSAKAIgDNddGBKAbiA=)):

```cs
System.Console.Write("foo");
```

The Results pane shows:

```
foo#{"flow":[1]}
```

**Comment by ashmind** [comment]
Good catch -- thanks for raising this!

**Comment by ashmind** [comment]
This is now resolved.
