### ISSUE TITLE
Support syntax tree visualizer

### ISSUE THREAD

**Issue by alrz** [ashmind/SharpLab#77]
Something similar to what LinqPad does, that'd be pretty awesome. (even a textual representation can be helpful though).

**Comment by ashmind** [comment]
@alrz Sounds like a good idea, can't promise any specific timeline though.

**Comment by ashmind** [comment]
@alrz Can you please link to some screenshots of good visualizers?
What information would be essential?

For context, I just prototyped something that would be useful for me, but I'm thinking whther I should go with a simple tree instead (this one can't really show trivia well):
![tryroslyn-ast-prototype](https://cloud.githubusercontent.com/assets/166396/25696538/a6aaa458-310b-11e7-847d-92e85526289a.png)

**Comment by alrz** [comment]
http://www.linqpad.net uses a tree,

![image](https://cloud.githubusercontent.com/assets/3105979/25699243/afb87bbc-30d7-11e7-85f3-053673b918ae.png)

Also check out https://astexplorer.net.

**Comment by ashmind** [comment]
@alrz OK, one more question -- what if I do something like https://roslynquoter.azurewebsites.net/ instead? Provides the same info, but also demonstrates the code to create a Syntax Tree as well.

**Comment by alrz** [comment]
That was actually what I had in mind when I said a textual representation, but forgot to provide the link. That'd be definitely useful. Thanks!

**Comment by ashmind** [comment]
An update: tried to be too smart here, got stuck for a while and lost some motivation -- so this might be on a backburner for a week or two.

**Comment by ashmind** [comment]
@alrz
I wasn't able to do the quoter within a reasonable time, so I did the UI first.  
Current version at the 'edge': 
https://edge.sharplab.io/#v2:C4LghgzsA0AmIGoA+BXCBLAdgcwAQGUBPKAUwFsBuAWACgAHFAIwBt0BjXN5yCXAYVwBvWrlG4GLdrgBuAe3SxcAWQAUASiFituEWIC+tPUA

I plan to release this to the main site very soon (day or two).  
No hover yet, I'll probably do a separate ticket for that.

**Comment by ashmind** [comment]
Done! Please raise new issues if you find any bugs/improvements.
