### ISSUE TITLE
Support IOperation explorer

### ISSUE THREAD

**Issue by alrz** [ashmind/SharpLab#78]
Similar to #77 but on bound nodes.

**Comment by ashmind** [comment]
@alrz What's the best current doc on `IOperation` and bound nodes?

**Comment by alrz** [comment]
Apparently, according to [wiki](https://github.com/dotnet/roslyn/wiki/Getting-Started-Writing-a-Custom-Analyzer-&-Code-Fix), it's pretty much an in-progress feature. I can see that build-in analyzers also use reflection to invoke the internal `GetOperationInternal` method. :(

**Comment by ashmind** [comment]
Thanks, I'll mark as external for now, until their work part is stabilized.

**Comment by ashmind** [comment]
@333fred Thanks -- I'll take a look (depending on other priorities).

**Comment by ashmind** [comment]
@alrz @333fred How do I get the root of `IOperation` tree? Does it have a root?

**Comment by alrz** [comment]
>`IOperation`: Root type for representing the abstract semantics of C# and VB **statements and expressions**.

So I guess we can't have a single root, but for every method body, getter/setter and field initializer.

**Comment by ashmind** [comment]
Would it work if I implement that within current syntax tree for now, and split later if needed (separate ticket)?

**Comment by alrz** [comment]
Having this within current syntax tree would make it easier to find a specific IOperation, so I think it's still a good way to do this, (without having a symbol tree on top - could be a separate feature but I'm not knowledgeable in that area)

**Comment by ashmind** [comment]
Done:
<img src="https://user-images.githubusercontent.com/166396/39657208-e6179baa-5059-11e8-8829-cb4f6205cbe2.png" width="200">

If anything is missing, please raise as new bugs/suggestions.
