### ISSUE TITLE
`Console.Write` produces extra un-explanatory output

### ISSUE THREAD

**Issue by Youssef1313** [ashmind/SharpLab#799]
https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUBQMID2MAzjQDYCmAdAOrJQIsAUAIgASLJkxoACAO41kTDAICUAbiA===

![image](https://user-images.githubusercontent.com/31348972/133289753-fe5e705d-0712-410e-b6e8-fe404ffba532.png)

**Comment by ashmind** [comment]
Thanks for reporting! This is same as #753 -- I'll take a look.

**Comment by ashmind** [comment]
This is now resolved.
