### ISSUE TITLE
Console.Read or Console.ReadLine crashes the container

### ISSUE THREAD

**Issue by KeterSCP** [ashmind/SharpLab#803]
**Steps to reproduce**
- Paste this code to the sharplab editor:

```
using System;

class Program
{
    static void Main(string[] args)
    {
        Console.ReadLine(); // Can be Console.Read();
    }
}
```
- Run the results

**Expected behavior**
- If input reading is not yet supported, there could be a message informing about that.

**Actual behavior**
- `(Container crashed, next container will be available in 15 seconds)` message appears
- After trying to run this code again, `Unbreakable.AssemblyGuardException: Member System.Console.ReadLine is not allowed.` exception is thrown (even after 15 seconds).

**Comment by ashmind** [comment]
Thanks, good point! I'll look to add an Analyzer for this, or find another workaround.

**Comment by ashmind** [comment]
Resolved (input reading is not yet supported, the read will produce a message explaining that)
