### ISSUE TITLE
Is there any plans to allow adding nuget packages for Run?

### ISSUE THREAD

**Issue by jsk95** [ashmind/SharpLab#810]
As per title, kind of like https://codesandbox.io/s/npm-playground-oobyv?file=/src/index.js in JS world.
I can see nuget package owners asking for re-production steps for bugs and being able to post a simple sharplab example would be very handy.

Had to do something similar when I had to verify some specific behaviour differences between different versions of react and preact.

**Comment by ashmind** [comment]
Thanks for raising this! Current primary issue for NuGet packages is #224, so I'll track it there.
Just as an update though, this is something I can take a look at it once I finish #724, though I can't promise it can actually work within the current hosting constraint.

If you would be interested in implementing Blazor Run mode, that part might be even easier.
