### ISSUE TITLE
Can I run sharplab on my own server?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [ashmind/SharpLab#813]
Is it allowed to run my own instance of sharplab on my domain and server? Provided all the copyrights and license requirements met

**Comment by vzarytovskii** [comment]
I believe, [BSD 2-Clause "Simplified" License](https://github.com/ashmind/SharpLab/blob/main/LICENSE.txt) allows both private and commercial use.

**Comment by ashmind** [comment]
Hi -- thanks for your question! As @vzarytovskii mentioned, yes you can.
One example is https://try.peachpie.io.

If it is a public server, I generally ask for the following (which is a good will thing and not enforced by the license):
- Change the colors in some way, so there is no style confusion with SharpLab
- Keep the author link in the footer
