### ISSUE TITLE
main branch is not updating

### ISSUE THREAD

**Issue by RikkiGibson** [ashmind/SharpLab#816]
It looks like the main branch stalled out around 3rd of September. https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQGYACLEgYRIG8CT6zT0AWEgWQAoBKGuhgXwL8gA=

It would be great if this could be brought back up to date. Please let me know if there's any way I can assist.

**Comment by ashmind** [comment]
Thanks for reporting! I'll take a look.
Generally you can see what happened here:
https://github.com/ashmind/SharpLab/actions/workflows/roslyn-branches.yml

In this case it seems I need to upgrade System.Buffers and System.Memory -- I remember trying to automate this part before, but probably never fully got to it.

**Comment by ashmind** [comment]
This is now resolved.
