### ISSUE TITLE
Error CS5001, "[...] does not contain a static 'Main' method [...]"

### ISSUE THREAD

**Issue by AlmightyLks** [ashmind/SharpLab#817]
Came across this and I am not sure if I am doing something wrong here or not

![image](https://user-images.githubusercontent.com/54688434/135214491-9174a7fa-411a-4985-9ef1-8184961d93ed.png)

Pretty simple to replicate:

https://user-images.githubusercontent.com/54688434/135214043-6f3b48fa-07f6-45bf-8a0c-dac52aa94f04.mp4

**Comment by ashmind** [comment]
Probably not something on your side -- I've seen this before, but not without switching modes -- I'll double-check.

**Comment by ashmind** [comment]
This should be resolved now (in Default; "main" might take more time).
I might not have covered all the flows though, pls feel free to open a new ticket if you find a new case.
