### ISSUE TITLE
Inspect.Stack, Inspect.Heap and Inspect.MemoryGraph are broken in the new container runner

### ISSUE THREAD

**Issue by ashmind** [ashmind/SharpLab#874]

**Comment by tswierkot** [comment]
Same with Inspect.Stack
https://sharplab.io/#gist:5dd52b497575ec1f24a46f6c9287e144

**Comment by maxild** [comment]
@ashmind Are there anyway to run an older version of sharplab.io where Inspect.Allocations, Inspect.Heap and Inspect.Stack works?

BTW Inspect.MemoryGraph seem to work https://sharplab.io/#gist:60efbb474a099f43f98d62a4aee3f8e3

**Comment by ashmind** [comment]
Interestingly, cannot reproduce this anymore. `Inspect.Allocations` is still broken, but I'll track that separately, e.g. in #920.
