### ISSUE TITLE
F# 6 support

### ISSUE THREAD

**Issue by gsomix** [ashmind/SharpLab#883]
It seems F# 6 (released with .NET 6) is not supported.

```fsharp
let a = [1;2;3]
let b = a[0] // works in F# 6
```
https://sharplab.io/#v2:DYLgZgzgNAJiDUAfYBTALgAgIYYLwYG0BGAbgCYSBmAXQFgAoVTAIz2wIAZqMB6HjAO4B7AE4BrCBgCWAOwwAxAMQYAbEA==

**Comment by Happypig375** [comment]
I'd love if the branches in the F# compiler repo is available in SharpLab just like Roslyn too.

**Comment by ashmind** [comment]
Thanks for reporting! F# releases generally include breaking changes to the compiler API surface, so I rely on external contributors who know it better than me to update it. All F# updates over last few years were done by @baronfel (much appreciated).

Fortunately I can see there is a PR for this at ashmind/mirrorsharp#177 (thanks @Lanayx), so once that's fully done F# 6 should be available.

**Comment by ashmind** [comment]
F# branches might be quite challenging to implement due to the same reason (breaking changes), as current branch system is not well designed to support branches with incompatible APIs (it uses same MirrorSharp version in all branches).

**Comment by baronfel** [comment]
From the incompatible API side, the F# community is working on locking down the FCS API specifically for reasons like this, so I'd hope to see progress in that front more and more over time!

**Comment by ashmind** [comment]
This is now done -- thanks @Lanayx.
Note that link in the thread will still show an error due to the aggressive cache, but you can try this one:
https://sharplab.io/#v2:DYLgZgzgNAJiDUAfYBTALgAgIYYLwYG0BGAbgCYSBmAXQFgAoVTAIz2wIAZqMg==

**Comment by Happypig375** [comment]
@ashmind Running the provided link fails due to FSharp.Core not being found.

**Comment by ashmind** [comment]
I see, Run mode probably has a different version of F#. I'll take a look.

**Comment by ashmind** [comment]
This is now resolved.
