### ISSUE TITLE
Nullable enable by default?

### ISSUE THREAD

**Issue by RikkiGibson** [ashmind/SharpLab#885]
I think new code in .NET uses `<Nullable>enable</Nullable>` at this point. It would be great if we didn't have to always remember to put `#nullable enable` at the top, and in scenarios where we need to check the behavior in a disabled context we can always put `#nullabel disable` at the top.

**Comment by ashmind** [comment]
Thanks for the suggestion!
Good point, I was waiting for default templates to include this, now that they do I can switch it on as well.

**Comment by ashmind** [comment]
This is now deployed.
