### ISSUE TITLE
Lambda not called in array initialisation

### ISSUE THREAD

**Issue by rawling** [ashmind/SharpLab#9]
Putting the following input in the standard C class/M method

```
Func<int, int> getInt = s => s;
var list = new [] { 1, 2, 3, getInt(1) };
Console.WriteLine(list[3]);
```

results in decompiled C# output containing

```
int[] array = new int[] {
    1,
    2,
    3,
    0
};
Console.WriteLine(array[3]);
```

in debug mode and

```
Console.WriteLine(new int[] {
    1,
    2,
    3,
    0
}[3]);
```

in release mode. The IL output looks like it does show a lambda call.

**Comment by ashmind** [comment]
Interesting, thanks for reporting. I'm away for a few days — I'll take a look when I'm back.

**Comment by ashmind** [comment]
It's a bug in ILSpy decompiler. My current plan for this:

1. Try to write my own decompiler based on Expressive
2. Find out it is too hard or time consuming
3. Return to ILSpy and fix the bug

Please feel free to submit a fixed version of ILSpy while I'm wasting my time on 1.

**Comment by ashmind** [comment]
Might take some time to deploy.
I've unrolled the syntax for array initializers, so you'll see actual initialization instead of `{ ... }` now.
