### ISSUE TITLE
System.Text.Json is missing from net6.0?

### ISSUE THREAD

**Issue by kasperk81** [ashmind/SharpLab#912]
```c#
using System;
using System.Text.Json;

Console.WriteLine("json is not missing");
```

fails:
```
    error CS0234: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)
```

**Comment by ashmind** [comment]
Thanks for reporting! Currently there is a predefined set of assemblies used -- eventually I plan to provide a way to load arbitrary ones. In the meantime I might add Json to the list.

**Comment by bschwehn** [comment]
Could you add System.Collections.Immutable as well?

**Comment by ashmind** [comment]
This one is now resolved (including `System.Collections.Immutable`).

**Comment by light-traveller** [comment]
What about `System.ComponentModel.DataAnnotations`?
