### ISSUE TITLE
Code that could cause stack corruption or arbitrary memory access is allowed to be run

### ISSUE THREAD

**Issue by vexx32** [ashmind/SharpLab#914]
Disclaimer: yes, code is cursed. Nobody should be running this. I'm guessing this is an oversight as I'm pretty sure most unsafe operations aren't allowed to actually run in SharpLab.

```csharp
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

public struct ListOfTheDamned<T>
{
    private T _start;
    
    public ref T this[int index]
        => ref Unsafe.Add(ref MemoryMarshal.CreateSpan(ref _start, 1)[0], index);
}

public class Program
{
    public static void Main()
    {
        var list = new ListOfTheDamned<byte>();
        list[0] = 255;
        
        for (int i = 0; i < 100; i++) {
            System.Console.WriteLine(list[i]);
        }
    }
}
```

Use of other types for the cursed list can also work, but may simply corrupt the stack and cause exceptions to be thrown. I've tried it with strings as well, that sometimes works and sometimes throws exceptions.

**Comment by ashmind** [comment]
Thanks for reporting!
These operations are now allowed (except in .NET Framework).

The code is isolated on process level using Windows AppContainer Isolation + JobObject resource restrictions.
You now have full access to the memory of your process, however you should not be able to see anyone else or read or affect the hosting process.

**Comment by vexx32** [comment]
Ah, okay, awesome! Was a bit surprised it let it run, but that makes sense. Thanks!
