### ISSUE TITLE
Update roslyn version - enable auto update

### ISSUE THREAD

**Issue by bernd5** [ashmind/SharpLab#939]
Currently the used roslyn main is from 27.01.2022 - it would be great if it could be updated more frequently...

**Comment by ashmind** [comment]
Thanks for reporting! The version does auto-update, however auto-update is not set up to resolve certain dependency issues.
I will look into resolving those, however fully automatic fix might be a separate scope -- something I am happy to accept a PR for.

**Comment by ashmind** [comment]
This is now resolved. It will keep auto-updating until it runs into a similar issue, hopefully for another month or 2.
