### ISSUE TITLE
Main branch timeouts

### ISSUE THREAD

**Issue by KeterSCP** [ashmind/SharpLab#955]
As title says, on `main` branch there is always `connection lost, reconnecting…` message. Seems like https://github.com/ashmind/SharpLab/issues/814 strikes back

![image](https://user-images.githubusercontent.com/38229504/161547866-61e9d556-578a-4c67-99b0-b0c1e4665bfc.png)

**Comment by ashmind** [comment]
Thanks for reporting! Seems deployment failed so the site was left stopped -- I'll rerun.

**Comment by ashmind** [comment]
Hmm, the build is fine, but there is another issue -- I'll take a look later today.

**Comment by ashmind** [comment]
All good, issue should be resolved now.

**Comment by KeterSCP** [comment]
Thanks, @ashmind for the quick fix!
