### ISSUE TITLE
Missing System.Runtime.CompilerServices.Unsafe class

### ISSUE THREAD

**Issue by atynagano** [ashmind/SharpLab#958]
https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+Ug9gEYBWApgMYAuiAsgBRFlWL4CUm2uXIA7MhADoASgFcAdpQCWAW1IDU+aQAdJAG1IAnAMqaAbpPKkAzgICqYowEMAZnICCRgDyMKlAHwNWAbk44AvrB+QA==

```cs
using System;
public class C {
    public object M(object o) {
        return System.Runtime.CompilerServices.Unsafe.As<object>(o);
    }
}
```

`error CS0234: The type or namespace name 'Unsafe' does not exist in the namespace 'System.Runtime.CompilerServices' (are you missing an assembly reference?)`

Currently we can't use Unsafe class on Default and x64. I don't know why.
The class existed in previous versions.

**Comment by Wraith2** [comment]
This likely to be caused by Unsafe moving into corelib/jit https://github.com/dotnet/runtime/pull/64861 Unsafe still exists but there isn't an IL implementation in coreclr anymore the jit handles it.

**Comment by Naine** [comment]
That seems unlikely to me for two reasons:

- That change should only affect .NET 7. Sharplab is still using .NET 6.
- The error comes from Roslyn, saying the type does not exist. Following that PR, the type exists in `System.Runtime`/`S.P.CoreLib`, with type forwards in `S.R.CS.Unsafe.dll`. The IL implementations are throwing, but that should not affect Roslyn's ability to find the type.

The error makes it seem that the `S.R.CS.Unsafe.dll` assembly is being excluded from the references supplied to Roslyn.

**Comment by ameisen** [comment]
The lack of `Unsafe` and the inability for `static` variables to workhas been leading me to have to use `LINQPad` more than `SharpLab` lately.

**Comment by ashmind** [comment]
This is now resolved -- please use https://sharplab.io/#v2:D4AQTAjABAsAUCAzFcUDCUDe8q5cgewCMArAUwGMAXKAWQApjzqoCBKLHPbkAdhQgA6AEoBXAHZUAlgFsygtARkAHKQBsyAJwDKWgG5SKZAM6CAquOMBDAGbyAgsYA8TSlQB8jNgG4uuAL7w/kA= to confirm as your original link is cached (including error) and there is no easy cache drop at the moment.
