### ISSUE TITLE
`BadImageFormatException` when calling a method that returns a `ref struct`

### ISSUE THREAD

**Issue by DaZombieKiller** [ashmind/SharpLab#963]
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHzxgHcACAZQAoBKAOgFlaBuAWAChYAzMgZw1xgMlMgG8yAAQDMIpjTIBeAHxkMACwCWvZmQC+QA==)
```cs
new S().M();
ref struct S { public S M() => this; }
```
```
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at S.M()
   at <Program>$.<Main>$(String[] args)
```

**Comment by ashmind** [comment]
Thanks for reporting! I'll take a look.

**Comment by ashmind** [comment]
This is now resolved -- you can see the result here:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHzxgHcACAZQAoBKAOgFlaBuMgWAChYAzMgZwy4wGSmQDeZAAIBmUUxpkAvAD4yGABYBLPqwC+QA==

(your original link will still have the error cached due to limitations of SharpLab cache)
